include/zmq.h

resolve #1325 Alignment issue with zmq_msg_t on SPARC CPU

---

builds/qt-android/build.sh

Solution: copy changes from latest zproject

Problem: qt-android build script out of date

---

tests/test_connect_delay_tipc.cpp
tests/test_filter_ipc.cpp
tests/test_immediate.cpp
tests/test_req_relaxed.cpp
tests/test_security_curve.cpp
tests/test_security_null.cpp
tests/test_security_plain.cpp
tests/test_spec_dealer.cpp
tests/test_spec_pushpull.cpp
tests/test_spec_rep.cpp
tests/test_spec_req.cpp
tests/test_spec_router.cpp
tests/testutil.hpp

Solution: raise timeouts from 100-150 msec to 250 msec

Problem: test cases are failing on slower PCs (eee PC)

---

Makefile.am
include/zmq.h
src/client.cpp
src/client.hpp
src/mechanism.cpp
src/server.cpp
src/session_base.cpp
src/socket_base.cpp
tests/test_client_drop_more.cpp
tests/test_client_server.cpp
tests/test_server_drop_more.cpp

also include implementation for dropping mutli part messages and test for client-server and dropping of multi part messages.

problem: client socket is missing

---

CMakeLists.txt

problem: jenkins build failed

---

CMakeLists.txt
builds/cmake/Modules/FindAsciiDoc.cmake
tests/CMakeLists.txt

Revert "Bzimmerman cmake"

---

builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj.filters
src/clock.cpp
src/clock.hpp
src/condition_variable.hpp
src/mailbox_safe.cpp

OSX issue: https://github.com/zeromq/libzmq/issues/1351
Solution, add OSX implementation of `clock_gettime()` and update VS project files.

Problem: build break in OSX, VS2010, VS2012

---

doc/zmq_setsockopt.txt

Fix for issue #1287: ZMQ_XPUB_NODROP documentation

---

src/signaler.cpp
tests/test_disconnect_inproc.cpp

Solution: add settle pause after zmq_connect
Fixes #1340

Problem: issue #1144, 1377

---

builds/qt-android/build.sh

Solution: Build libsodium from latest master branch. Fixes 1386.

---

.gitignore
AUTHORS
Makefile.am
src/proxy.cpp
tests/CMakeLists.txt
tests/test_proxy_terminate.cpp

This is the fix for issue #1382. Once it is merged I shall backport this to 4.1 and 4.0 repositories.

Fix for issue #1382

---

Makefile.am

Solution: fixed this in Makefile.am

Problem: incomplete specs for test_proxy_terminate

---

doc/zmq_socket.txt

This commit fixes issue #1402.

doc/zmq_socket.txt: Remove note about ZMQ_PAIR being experimental.

---

src/socket_base.cpp
src/thread.cpp
tests/test_srcfd.cpp

HPUX build and gmake check issues solution (#1412)

---

Makefile.am

Problem: tests/test_socketopt_hwm fails and breaks CI

---

src/decoder.hpp

Fix initialization order.

---

Makefile.am
include/zmq.h
src/curve_client.cpp
src/curve_server.cpp
src/gssapi_mechanism_base.cpp
src/options.cpp
src/options.hpp
src/session_base.cpp
src/stream_engine.cpp
src/stream_engine.hpp
tests/CMakeLists.txt
tests/test_heartbeats.cpp

This commit adds ZMTP connection heartbeats described in
http://rfc.zeromq.org/spec:37/ZMTP.

Add ZMTP connection heartbeats

---

.gitignore

Sorry, forgot to add the new tests to .gitignore

ignore unbind tests

---

src/decoder.hpp

[decoder.hpp] Fix misspelled inclusion

---

src/stream.cpp
tests/test_client_server.cpp
tests/test_srcfd.cpp
tests/test_stream_disconnect.cpp

I traced memory leaks found using AddressSanitizer down to these.

Fix several missing msg_t::close calls.

---

doc/zmq_setsockopt.txt

This PR fixes a few minor issues with socket option documentation.

Documentation fixes for socket options.

---

src/zmq.cpp

Remove type-pun in zmq.cpp to resolve issue #1500.

---

Makefile.am
builds/Makefile.am
configure.ac
doc/zmq_ctx_set.txt
tests/test_stream.cpp
tests/testutil.hpp

Solution: added to test_stream.cpp

Problem: lack test case for large stream messages

---

src/err.cpp
src/ip.cpp
src/socks_connecter.cpp
src/tcp.cpp
src/tcp_connecter.cpp
src/tcp_listener.cpp

changing some camelCase variable names to snake_case in previous commit

changing some camelCase variable names to snake_case in previous commit

---

include/zmq.h

solution: moving new poller field to the end of the struct

problem: new field is breaking existing code

---

include/zmq.h

apply a change to LIBZMQ_DELETE macro (related to issue #1524)

apply a change to LIBZMQ_DELETE macro (related to issue #1524)

---

include/zmq.h
src/zmq.cpp
tests/test_thread_safe_polling.cpp

solution: remove the new field and use existing fd field instead.

problem: new poller field in zmq_pollitem_t is changing the api

---

src/xpub.cpp

Fixes tests that were introduced in a previous pull request. See https://github.com/zeromq/libzmq/pull/1539#issuecomment-132968987

Fixes failing tests regarding XPUB sockets.

---

include/zmq.h
src/blob.hpp
src/clock.cpp
src/condition_variable.hpp
src/ctx.hpp
src/gssapi_mechanism_base.cpp
src/gssapi_server.cpp
src/gssapi_server.hpp
src/mtrie.cpp
src/pgm_socket.cpp
src/pipe.cpp
src/socket_base.cpp
src/thread.cpp
src/xpub.cpp
src/xpub.hpp
src/zmq.cpp
tests/test_connect_rid.cpp
tests/test_srcfd.cpp
tests/test_stream_disconnect.cpp
tests/test_thread_safe.cpp
tests/test_xpub_manual.cpp
tests/test_xpub_welcome_msg.cpp

Solution: Convert to spaces and remove trailing whitespace in these files.

Problem: Source files contain mixed tabs and spaces.

---

include/zmq.h
src/client.cpp
src/dealer.cpp
src/pair.cpp
src/pull.cpp
src/push.cpp
src/router.cpp
src/server.cpp
src/stream.cpp
src/tcp.cpp
src/tcp_address.cpp
src/xsub.cpp

rename ZMQ_UNUSED macro to LIBZMQ_UNUSED

rename ZMQ_UNUSED macro to LIBZMQ_UNUSED

---

src/xpub.cpp
tests/test_xpub_manual.cpp

The patch fixes lingering subscriptions that occur upon disconnection on XPUB sockets with option PUB_MANUAL when used in a XPUB-XSUB proxies.
I added the test case as suggested.

Problem: lingering subscriptions on XPUB sockets (#1566)

---

src/xpub.cpp
src/xpub.hpp
tests/test_xpub_manual.cpp

The patch fixes the issue #1568.

Fixed missing subscriptions on XPUB with manual subscriptions

---

src/socket_base.cpp

Unaligned access would cause SIGBUS on architectures that do not allow it.
Furthermore, the (now unneeded) fix for HPUX appears to have a bug in that the defined union may have padding bytes inserted.

avoid dereferencing uint32_t on unaligned address

---

src/signaler.cpp

fixed zmq assertion in signaler.cpp under ubuntu

---

src/lb.cpp

Issue : zeromq asserts if send fails for multi part msgs.
Goal : Provide graceful handling of send failure for this scenario while maintaining atomicity principle for multipart msgs.
For details, Please follow discussion here
https://github.com/zeromq/libzmq/issues/1588#issuecomment-142730046

Issue 1588 : Rollback in case send fails for multipart msg

---

src/ypipe.hpp

micro typo in comments (is -> if).

fix a typo in ypipe.hpp

---

configure.ac

enable static libraries on mingw

---

builds/msvc/vs2008/libzmq/libzmq.vcproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj.filters

Added missing socket_poller.cpp file to msvc solutions.
also fixes issue https://github.com/zeromq/libzmq/issues/1624

Added missing socket_poller.cpp file to msvc solutions.

---

src/signaler.cpp

See issue #1608.
This is an old issue with Windows 7. The effect is that we see a latency
ramp on the first 500 messages.
* The ramp is unaffected by message size.
* Sleeping up to 100msec between sends has no effect except to switch
off ZeroMQ batching so making the ramp more visible.
* After 500 messages, latency falls back down to ~10-40 usec.
* Over inproc:// the ramp happens when we use the signaler class.
* Client-server over inproc:// does not show the ramp.
* Client-server over tcp:// shows a similar ramp.
We know that the signaller is using TCP on Windows. We can 'prime' the
connection by doing 500 dummy sends. This potentially causes new sockets
to be delayed on creation, which is not a good solution.
Note that the signaller sends zero-byte messages. This may also be
confusing …

Problem: Windows 7 TCP slow start

---

src/options.cpp
src/options.hpp

1. make `tcp_recv_buffer_size` and `tcp_send_buffer_size` unsigned
2. make base a double value

Solution: fix compilation errors

---

src/router.cpp
src/router.hpp

Fix pipe terimation in router while reading message

Problem: router socket can do pipe handover while reading multipart message

---

doc/zmq_getsockopt.txt
doc/zmq_setsockopt.txt
include/zmq.h
src/config.hpp
src/options.cpp
src/options.hpp
src/pgm_socket.cpp

Add new option ZMQ_MULTICAST_MAXTPDU to set PGM_MTU.

---

configure.ac
src/socket_base.cpp

Solution: fix them! :-)
Fixes #1655

Problem: build failures due to include outside ifdef and wrong default in autotools

---

configure.ac
src/vmci_address.cpp
src/vmci_address.hpp

Don't build VMCI by default.

---

doc/zmq_vmci.txt

Problem: zmq_vmci man page claims to be zmq_ipc man page

---

.travis.yml

Solution: change .travis.yml to build "android" instead of "qt-android"

Problem: travis CI tries to build "qt-android"

---

builds/android/Dockerfile
builds/android/build.sh

Build success message + Build zmq for android with a Dockerfile.

Build success message + Build zmq for android with a Dockerfile

---

src/yqueue.hpp

Clang's UndefinedBehaviorSanitizer catches this in the tests.

Fix alignment of initial chunk in yqueue

---

src/v2_decoder.cpp

Problem: Windows build gives warning on v2_decoder.cpp:130

---

builds/msvc/vs2010/inproc_lat/inproc_lat.props
builds/msvc/vs2010/inproc_thr/inproc_thr.props
builds/msvc/vs2010/local_lat/local_lat.props
builds/msvc/vs2010/local_thr/local_thr.props
builds/msvc/vs2010/remote_lat/remote_lat.props
builds/msvc/vs2010/remote_thr/remote_thr.props
builds/msvc/vs2012/inproc_lat/inproc_lat.props
builds/msvc/vs2012/inproc_thr/inproc_thr.props
builds/msvc/vs2012/local_lat/local_lat.props
builds/msvc/vs2012/local_thr/local_thr.props
builds/msvc/vs2012/remote_lat/remote_lat.props
builds/msvc/vs2012/remote_thr/remote_thr.props
builds/msvc/vs2013/inproc_lat/inproc_lat.props
builds/msvc/vs2013/inproc_thr/inproc_thr.props
builds/msvc/vs2013/local_lat/local_lat.props
builds/msvc/vs2013/local_thr/local_thr.props
builds/msvc/vs2013/remote_lat/remote_lat.props
builds/msvc/vs2013/remote_thr/remote_thr.props

Solution: add Iphlpapi.lib to libraries to link against

Problem: performance tests don't link on Windows/MSVC

---

builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj

Problem: includes timer.cpp/hpp instead of timers.cpp/hpp

---

builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj

Solution: fix and try again.
(We could start to think of using zproject to generate these build
scripts as the only difference is C/C++)

Problem: still one error in vcxproj files

---

builds/android/build.sh

Solution: use parallel make (-j 4) and don't build man pages.

Problem: Android build is too slow

---

src/socket_poller.cpp

solution: check if the socket is not dead before accessing it.
In general it might be good practice to destroy the poller before destroying the sockets.
Fixes https://github.com/zeromq/czmq/issues/1299

problem: when socket is destroyed before zmq_poller is the zmq_poller is accessing a dead socket

---

appveyor.yml

Solution: Use stable branch of libsodium

Problem: Windows CI fails due to libsodium build failure

---

src/condition_variable.hpp

problem: condition variable setting invalid timeout

---

src/server.cpp

Problem: typo

---

Makefile.am
configure.ac
src/poller.hpp
src/thread.cpp

Work of Svante Signell, quoting him:
"I did manually issue configure, make and make check in the git directory, and they passed fine. It seems like even the git version, 4.2.0?, should build when packaged."

Last bits of Hurd support

---

src/tcp_address.cpp

Make it ready to enable ipv6 for AIX or HP/UX

Family is not set when resolving NIC on android.

---

builds/msvc/vs2008/libzmq/libzmq.vcproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj

Solution: add these new classes to MSVC project files

Problem: radio/dish class broke Windows builds

---

.gitignore
CMakeLists.txt
Makefile.am
src/address.cpp
src/radio.cpp
src/radio.hpp
src/session_base.cpp
src/socket_base.cpp
src/udp_address.cpp
src/udp_address.hpp
src/udp_engine.cpp
src/udp_engine.hpp
tests/test_udp.cpp

suggested solution: add udp/multicast support to zeromq.
```C
void *ctx = zmq_ctx_new ();
void *radio = zmq_socket (ctx, ZMQ_RADIO);
void *dish = zmq_socket (ctx, ZMQ_DISH);
zmq_bind (radio, "udp://127.0.0.1:5556");
zmq_connect (dish, "udp://127.0.0.1:5556");
```

Problem: no udp/multicast support in zeromq

---

builds/msvc/vs2015/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj.filters
include/zmq_utils.h

Altered VS2015 files to enable building of the library.
To note, if this is accepted, I includes a commit to add zmq_utils.h back to where it belongs

Added "udp_address" and "udp_engine" to VS2015 project

---

Makefile.am
builds/cygwin/Makefile.cygwin
builds/mingw32/Makefile.mingw32
builds/msvc/vs2008/libzmq/libzmq.vcproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2015/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj.filters
src/options.cpp

- zmq_utils.h was removed
- udp_address.cpp and udp_engine.cpp were added
Solution: patch all affected build scripts

Problem: various errors in build scripts

---

builds/msvc/vs2010/libzmq/libzmq.props
builds/msvc/vs2010/local_thr/local_thr.vcxproj
builds/msvc/vs2010/remote_lat/remote_lat.vcxproj
builds/msvc/vs2012/libzmq/libzmq.props
builds/msvc/vs2012/local_thr/local_thr.vcxproj
builds/msvc/vs2012/remote_lat/remote_lat.vcxproj
builds/msvc/vs2013/libzmq/libzmq.props
builds/msvc/vs2013/local_thr/local_thr.vcxproj
builds/msvc/vs2013/remote_lat/remote_lat.vcxproj
builds/msvc/vs2015/inproc_lat/inproc_lat.props
builds/msvc/vs2015/inproc_lat/inproc_lat.vcxproj
builds/msvc/vs2015/inproc_thr/inproc_thr.props
builds/msvc/vs2015/inproc_thr/inproc_thr.vcxproj
builds/msvc/vs2015/libzmq/libzmq.props
builds/msvc/vs2015/local_lat/local_lat.props
builds/msvc/vs2015/local_lat/local_lat.vcxproj
builds/msvc/vs2015/local_thr/local_thr.props
builds/msvc/vs2015/local_thr/local_thr.vcxproj
builds/msvc/vs2015/remote_lat/remote_lat.props
builds/msvc/vs2015/remote_lat/remote_lat.vcxproj
builds/msvc/vs2015/remote_thr/remote_thr.props
builds/msvc/vs2015/remote_thr/remote_thr.vcxproj

Fixed VS2015 build

---

src/dealer.cpp
src/options.cpp
src/req.cpp
src/router.cpp
src/stream.cpp
src/sub.cpp
src/xsub.cpp
src/zmq.cpp

It's undefined behavior, and ubsan flags it.

Don't call memcpy with 0 size and NULL pointer(s)

---

builds/msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2012/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2013/libzmq/libzmq.vcxproj.filters
doc/zmq_recv.txt
src/dealer.cpp
src/options.cpp
src/req.cpp
src/router.cpp
src/stream.cpp
src/sub.cpp
src/xsub.cpp
src/zmq.cpp
tests/test_msg_ffn.cpp
tests/test_timers.cpp

Refinement of #f4fe375

---

src/thread.cpp

Change to detect POSIX Thread priority support properly

---

src/gssapi_mechanism_base.cpp

Fix to build with libgssapi_krb5 support

Fix a typo in "Add ZMTP heartbeats" changes

---

Makefile.am
configure.ac

and `--with-tweetnacl` for explicitly requesting build with tweetnacl
closes #1781

fallback on tweetnacl if libsodium is not found and not explicitly requested

---

.gitignore

Problem: old filenames in .gitignore

---

.travis.yml

Solution: remove libsodium and no curve builds from cmake and android

Problem: too many CI builds

---

.gitignore
CMakeLists.txt
builds/gyp/.gitignore
builds/gyp/platform.hpp
builds/gyp/project.gyp
configure.ac
src/tweetnacl.c
src/tweetnacl.h

Also: raised socket limit to 16K on Windows in CMakeLists.txt

Number of fixes for gyp builds

---

src/socket_base.cpp

problem: dynamic cast is causing issue when compiling for nodejs

---

.gitignore
builds/Makefile.am
builds/msvc/Makefile.am

Problem: make dist is borken

---

configure.ac

Problem: Fix unportable `==` operator for `test`

---

builds/msvc/vs2010/inproc_lat/inproc_lat.vcxproj
builds/msvc/vs2010/inproc_thr/inproc_thr.vcxproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2010/local_lat/local_lat.vcxproj
builds/msvc/vs2010/local_thr/local_thr.vcxproj
builds/msvc/vs2010/remote_lat/remote_lat.vcxproj
builds/msvc/vs2010/remote_thr/remote_thr.vcxproj
builds/msvc/vs2012/inproc_lat/inproc_lat.vcxproj
builds/msvc/vs2012/inproc_thr/inproc_thr.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2012/local_lat/local_lat.vcxproj
builds/msvc/vs2012/local_thr/local_thr.vcxproj
builds/msvc/vs2012/remote_lat/remote_lat.vcxproj
builds/msvc/vs2012/remote_thr/remote_thr.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj

Solution: Corrected ToolsVersion setting where needed.

Problem: Visual Studio Toolset was incorrectly set in VCXPROJ files

---

tests/CMakeLists.txt
tests/README.md

Solution: Modified CMakelist.txt to build correctly for Windows

Problem: Tests do no build in Windows environment

---

Makefile.am
ci_build.sh
doc/Makefile.am

Solution: add it to Makefile.am file list

Problem: make dist does not tar up macros.hpp

---

builds/android/README.md

add some doc for docker android compilation

add some doc for docker android compilation

---

src/dist.cpp

[Issue 1419](https://github.com/zeromq/libzmq/issues/1419)

Fix issue #1419 segfault when using a XSUB/XPUB proxy.

---

src/array.hpp
src/ypipe_conflate.hpp

Fix typos similar to #1894

---

CMakeLists.txt
builds/cmake/Modules/ZMQSourceRunChecks.cmake
builds/cmake/ci_build.sh
tests/CMakeLists.txt

Problem: CMake CI does not run make test, and there is no checking for TIPC

---

src/select.cpp

problem: udp is failing on windows

---

.gitignore
CMakeLists.txt
Makefile.am
include/zmq.h
src/gather.cpp
src/gather.hpp
src/mechanism.cpp
src/scatter.cpp
src/scatter.hpp
src/session_base.cpp
src/socket_base.cpp
tests/CMakeLists.txt
tests/test_scatter_gather.cpp

solution: add new socket types, scatter and gather which are thread safe.
@hintjens thought it might make you smile a little.

problem: push-pull socket types are not thread safe

---

tests/test_term_endpoint.cpp
tests/test_unbind_wildcard.cpp

please let the CI run, I want to check if this fixed the problem

problem: Tests are failing on windows

---

src/signaler.cpp
src/zmq.cpp

Problem: unistd.h redundantly included twice

---

RELICENSE/README.md

Problem: need to collect grants to relicense under MPLv2
Solution: kick off process by creating a directory to collect grants to relicense under MPLv2

RELICENSE: Start collecting MPLv2 license grants

---

RELICENSE.md

Solution: kick off process with grant from iMatix

Problem: need to collect grants to relicense under MPLv2

---

doc/Makefile.am
doc/zmq.txt
doc/zmq_socket.txt
doc/zmq_udp.txt
src/socket_base.cpp
src/udp_address.cpp
src/udp_address.hpp
tests/test_udp.cpp

also solving: no way to specify bind address when using Radio with UDP

problem: no documentation for Radio-dish and UDP

---

src/decoder.hpp

Problem: style issues in decoder.hpp

---

m4/ax_check_compile_flag.m4
m4/ax_code_coverage.m4
m4/ax_cxx_compile_stdcxx.m4
m4/ax_cxx_compile_stdcxx_11.m4

**Solution:**
Update them from the latest archive located at:
git://git.savannah.gnu.org/autoconf-archive.git

Problem: autoconf-archive m4 macros out of date

---

src/tcp.cpp
src/tcp_connecter.cpp
src/tcp_listener.cpp

Problem: tune_tcp* related code has style issues

---

builds/msvc/configure.bat
include/zmq.h
src/precompiled.hpp

+ problem: zmq_msg new methods are not marked as draft

problem: no way to enable draft on windows

---

.gitignore

Problem: Not all GCOV extensions in .gitignore

---

src/config.hpp
src/options.cpp
src/stream_engine.cpp
tests/test_setsockopt.cpp

problem: zeromq performance got worsen by some changes

---

AUTHORS

Solution:
Plug myself in, should the commit and BDFL overlords approve.
Special-copy-to:
@hintjens, @somdoron, @bluca.

Problem: Not shamelessly plugged into AUTHORS

---

src/zmq.cpp

**Solution:**
Wrap and clean it.

Problem: style issues with comment in zmq_poll

---

AUTHORS

**Solution:**
Sort the list and strip the trailing whitespace.

Problem: AUTHORS file is not sorted

---

tests/test_timers.cpp

problem: timers test is flapping on windows

---

src/session_base.cpp

Problem: UDP engine code not indented properly [style]

---

configure.ac

Problem: style/typo issue

---

src/socket_base.cpp

Reverts zeromq/libzmq#1975
problem: patch is no good

Revert "problem:Socket try to access closed mutex"

---

.gitignore
CMakeLists.txt
Makefile.am
include/zmq.h
src/dgram.cpp
src/dgram.hpp
src/mechanism.cpp
src/session_base.cpp
src/socket_base.cpp
src/udp_engine.cpp
src/udp_engine.hpp
src/zmq_draft.h
tests/CMakeLists.txt
tests/test_dgram.cpp

continue @Bitiquinho work on #1986

problem: no way to send raw udp messages with zeromq.

---

src/socket_base.cpp
src/udp_address.cpp
tests/test_dgram.cpp
tests/test_udp.cpp

solution: enforce that dish and gram can only bind and radio can only
connect

problem: udp doesn't enforce correct usage of bind/connect

---

src/socket_base.cpp
src/udp_engine.cpp
src/udp_engine.hpp

@bluca I think this is the issue, however I'm not sure...

problem: no way to send raw udp messages with zeromq

---

AUTHORS

Problem: my name is not in the AUTHORS file

---

tests/test_srcfd.cpp

Problem: Wrapping issue in test for SRCFD [style]

---

builds/msvc/vs2008/libzmq/libzmq.vcproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj
builds/msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2012/libzmq/libzmq.vcxproj
builds/msvc/vs2012/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2013/libzmq/libzmq.vcxproj
builds/msvc/vs2013/libzmq/libzmq.vcxproj.filters
builds/msvc/vs2015/libzmq/libzmq.vcxproj
builds/msvc/vs2015/libzmq/libzmq.vcxproj.filters
src/udp_engine.cpp

This also cleans up some implicit narrowing casts and msvc filters.

Problem: unresolved dgram externals in msvc builds.

---

src/windows.hpp

**Solution:**
Wrap to lte 80 chars and fix it.

Problem: style broken in src/windows.hpp

---

src/vmci_connecter.cpp

It may even cause BSOD on Windows.

VMCI family does not support non-blocking sockets.

---

builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

Problem: Android CI NDK version and C++ ABI are outdated

---

src/fd.hpp

(and probably other MSVC versions)

Fix build error in MSVC11

---

builds/cygwin/Makefile.cygwin
builds/mingw32/Makefile.mingw32
builds/msvc/vs2008/libzmq/libzmq.vcproj
configure.ac

Solution: Set FD_SETSIZE to 16k for all other build definitions.

Problem: FD_SETSIZE not set to 16k for all build definitions

---

src/ipc_listener.cpp

sent the previous pull request too soon, sorry

Fix copy/paste error

---

CMakeLists.txt

See CMake bug for details.
https://gitlab.kitware.com/cmake/cmake/issues/16201

Fix compatibility with newer CMake.

---

CMakeLists.txt

Tested on debian jessie and Window 7.

Fix building documentation

---

packaging/debian/rules
packaging/redhat/zeromq.spec

Both a manual build and an OBS build solution are added.

Problem: cannot build packages with DRAFT APIs

---

src/mutex.hpp
src/socket_base.cpp

Solution: add a lock guard that takes optional a mutex and use it

Problem: socket_base uses macros for mutex lock and unlock

---

src/ctx.cpp
src/decoder.hpp
src/dgram.cpp
src/ip.cpp
src/norm_engine.cpp
src/norm_engine.hpp
src/pipe.cpp
src/select.cpp
src/signaler.cpp
src/socket_base.cpp
src/stream.cpp
src/tcp.cpp
src/tcp_listener.cpp
src/tweetnacl.c

Solution: replace tabs with spaces and remove trailing spaces

Problem: source conatins tabs and trailing spaces

---

CMakeLists.txt
acinclude.m4
src/poller.hpp

1. move the 'pollset' to the position between 'devpoll' and 'poll'
2. replace the tabs with spaces

Pollset-change the position of `pollset`

---

src/socket_poller.cpp

previous patch (#2128) updated only the branch for ZMQ_POLL_BASED_ON_POLL, causing failed builds on Windows.
closes #2137

update socket_poller when ZMQ_POLL_BASED_ON_SELECT

---

src/zmq.cpp

variable-size array allocation is not allowed by some compilers
This should fix the build failures due to #2140, but there are still some proxy tests failing.
One is due to zmq_poller not allowing sockets to be registered more than once, which zmq_poll allows and zmq_proxy currently requires.
I'm not sure what the other failure is caused by.

heap-allocate events in zmq_poller_poll

---

src/zmq.cpp

Problem: a request

---

doc/zmq_socket.txt

Problem: Invalid markup in zmq_socket.txt

---

src/tcp_address.cpp

See 
https://github.com/Microsoft/BashOnWindows/issues/185#issuecomment-250968454
for the idea and explanation.
I've verified that this works on the WSL system.

Patch for compatibility with Windows subsystem for linux

---

src/mtrie.cpp

Removes unnecessary null pointer check

Fixed issue #2155

---

src/socket_base.cpp
src/socket_base.hpp

- Fixed windows build errors
- Extended lock scope in monitor and process_stop to prevent race-condition

Fixed problems from previous PR for #2158

---

src/tcp_address.cpp

Solution: `#include <netioapi.h>` and change some `IP_ADAPTER_UNICAST_ADDRESS` data types

Problem: Does not build in Visual Studio 2013 / Win32

---

src/xpub.cpp

I have been experiencing segfaults related to XPUB sockets, and traced it down to this invalid memory access.  The metadata object incorrectly reaches refcount zero and is deleted before it is then used again in `set_metadata`.  This can be seen in the valgrind output below as stemming from lines 1320 and 1324 in socket_base.cpp
The solution presented is to increment the refcount on the metadata object while it's in `pending_metadata` but not actually referenced by any objects.
This might possibly fix #1833 but it's difficult to know for sure as the after-effects of invalid memory access are difficult to predict
<details><summary>Valgrind output</summary>
==20853== Invalid read of size 4
==20853==    at 0x4E70C58: zmq::atomic_counter_t::add(unsigned int) (atomic_counter.hpp:102)
==20853== …

Increment metadata refcount while it's in pending_metadata

---

CMakeLists.txt
tests/CMakeLists.txt

Solution: add optional lookup for openpgm via pkg-config

Problem: CMake build rejects to build with openpgm enabled

---

NEWS

Solution: add mention and point to doc/zmq_udp.txt

Problem: NEWS does not mention UDP multicast transport

---

NEWS

Problem: NEWS says scatter/gather support UDP but they don't

---

NEWS

Problem: NEWS says ZMQ_BLOCKY is a sock opt, but it's a ctx opt

---

src/tcp_address.cpp

Problem: inconsistent indentation and tabs in code

---

src/zmq.cpp

item.fd should be ignored if item.socket is defined.
Failing to check .socket could cause false-matches, raising EINVAL in zmq_poller_modify_fd.
It would be nice to get this in 4.2.1

only compare pollitem.fd if pollitem.socket is NULL

---

tests/test_stream_exceeds_buffer.cpp
tests/testutil.hpp

Solution: fix includes (see commits)
Partially fixes #2234

Problem: test_stream_exceeds_buffer fails to build on AIX

---

src/tcp_address.cpp

PVS Studio fix: http://www.viva64.com/en/w/V817/

"%" -> '%'

---

.gitignore
Makefile.am
tests/test_zmq_poll_fd.cpp

Problem: no mixed FD and zmq socket zmq_poll test

---

src/options.cpp
src/options.hpp

Solution: set_curve_key method in options_t struct with little
improvement in switch-case block

Problem: Duplicated code

---

src/options.cpp
src/options.hpp

Solution: Revert "Problem: Duplicated code"
This reverts commit 022eeaf33d50f8a1515a28ffb8c8cafd843ca064.

Problem: #2262 broke curve

---

.github/PULL_REQUEST_TEMPLATE.md

Solution: port Github PR template from CZMQ

Problem: contributing guidelines unclear for new devs

---

doc/Makefile.am
doc/zmq.txt
doc/zmq_curve_public.txt
doc/zmq_getsockopt.txt
doc/zmq_setsockopt.txt
doc/zmq_z85_decode.txt
doc/zmq_z85_encode.txt

Problems: no docs for ZMQ_SOCKS_PROXY and zmq_curve_public

---

src/radio.cpp

Solution: add a comment as it's easy to miss and very tempting to
"optimize"

Problem: fix for read-after-free not documented

---

.travis.yml
builds/cmake/ci_build.sh
builds/coverage/ci_build.sh
builds/valgrind/ci_build.sh
ci_build.sh

Problems: docs build not tested, old Travis OSX workaround not removed, libsodium rebuilt everytime

---

builds/cmake/ci_build.sh
builds/coverage/ci_build.sh
builds/valgrind/ci_build.sh
ci_build.sh

Solution: rework the bash test to avoid build failures as intended
and make it an easier one-liner

Problem: dpkg-query might fail in CI build and fail the build

---

NEWS
doc/zmq_ctx_get.txt
include/zmq.h
src/zmq_draft.h
tests/test_ctx_options.cpp

Problems: ZMQ_MSG_T_SIZE draft but not DRAFT, NEWS for 4.2.1 almost empty

---

doc/zmq_proxy.txt
doc/zmq_proxy_steerable.txt

Solution: mention this in the documentation
Fixes https://github.com/zeromq/libzmq/issues/1311

Problem: zmq_proxy* may return EINTR other than ETERM

---

packaging/debian/control
packaging/debian/zeromq.dsc.obs

Solution: build-depend on asciidoc and xmlto

Problem: debian packages do not build manpages

---

packaging/redhat/zeromq.spec

Solution: remove the dependency as it's not been needed for a while

Problem: spec file still depends on libuuid

---

src/pipe.cpp
src/pipe.hpp
src/socket_base.cpp

Problems: modifying pipe from different thread is not safe and HWM always boosted by 1

---

CMakeLists.txt

This PR fixes the cmake installation on Linux and UNIX like systems.

cmake install on linux fixed

---

builds/msvc/build/buildall.bat
builds/msvc/build/buildbase.bat

This PR would add support for Visual Studio RC 2017 when building with buildall.bat and buildbase.bat

Updated buildbase and buildall to work with visual studio 2017

---

doc/zmq_has.txt
tests/test_capabilities.cpp

add test and documentation for "draft" capability

---

doc/zmq_has.txt

Problem: typo in the zmq_has doc

---

CMakeLists.txt

Configuration used in ZeroMQConfig.cmake.in does not match to
explicic "libzmq" output of static build.
```
```
git push -f
If you are a …

CMake static library output does not match ZeroMQ Config.

---

src/lb.cpp

This is based on https://github.com/zeromq/zeromq3-x/pull/116/files

fix divide by zero in zmq::lb_t::sendpipe

---

NEWS
packaging/debian/changelog
packaging/debian/zeromq.dsc.obs
packaging/redhat/zeromq.spec

Solution: mention main changes and bug fixes since 4.2.1 and bump packaging versions to 4.2.2

Problem: NEWS not up to date, packaging versions not up to date

---

doc/zmq_socket.txt

Problem: typo in the zmq_socket doc

---

src/router.cpp
src/socket_base.cpp
tests/test_router_mandatory_hwm.cpp

Commit for Issue #2348
Problem: In zmq::socket_base_t::send method with or without ZMQ_ROUTER_MANDATORY option set

Commit: Issue #2348

---

include/zmq.h

solution: deprecate zmq_poll in favor of zmq_poller

problem:zmq_poll is slow and the API is complicated

---

RELICENSE/rlenferink.md

Added my license grant to the RELICENSE directory

RELICENSE: License grant by Roy Lenferink

---

RELICENSE/templates/relicense-template-mplv2-any-osi.txt
RELICENSE/templates/relicense-template-mplv2-share-alike-osi.txt
RELICENSE/templates/relicense-template-mplv2.txt

Added templates for re-licensing

RELICENSE: Added templates for relicensing

---

RELICENSE/sabae.md

Relicensing is a huge pain.  I wish you guys the best of luck.

Add relicensing agreement for Elliot Saba

---

RELICENSE/yuvallanger.md

RELICENSE: Yuval Langer grant

---

RELICENSE/cdolan.md

Added my license grant to the RELICENSE directory

RELICENSE: Christopher Dolan grant

---

RELICENSE/thompsa.md

RELICENSE: Andrew Thompson grant

---

RELICENSE/agronholm.md

Relicense: Alex Grönholm grant

---

RELICENSE/TimotheeBesset.md

relicensing

---

RELICENSE/RobGagnon.md

RELICENSE: Robert Gagnon

---

RELICENSE/danielhtshih.md

RELICENSE: Daniel Shih grant

---

RELICENSE/ckamm.md

RELICENSE: Christian Kamm grant

---

RELICENSE/johntconklin.md

RELICENSE: John T. Conklin grant

---

RELICENSE/relicense-template-mplv2.txt

Solution: add myself to the RELICENSING document.

Problem: want to relicense under mplv2

---

RELICENSE/LeonardoConsoni.md

RELICENSE: Leonardo J. Consoni grant

---

RELICENSE/torehalvorsen.md

Relicense for tore.halvorsen@gmail.com

RELICENSE: Tore Halvorsen

---

RELICENSE/shripchenko.md

RELICENSE: shripchenko

---

RELICENSE/loachfish.md

RELICENSE: Justin.Hung grant

---

RELICENSE/danriegsecker.md

Relicense statement for Dan Riegsecker (@danriegsecker)

---

RELICENSE/soulik.md

RELICENSE: soulik

---

RELICENSE/camachat.md

RELICENSE: Eric Camachat

---

RELICENSE/GavinMcNiff.md

Relicense approval

---

RELICENSE/febeling.md

RELICENSE febeling

---

RELICENSE/roalz.md

Ref: https://github.com/zeromq/libzmq/issues/2376

RELICENSE: Roal Zanazzi (roalz)

---

RELICENSE/mipaaa.md

Michael Hand grant

---

RELICENSE/GiuseppeCorbelli.md

Added RELICENSE/GiuseppeCorbelli.md to allow libzmq relicensing

Giuseppe Corbelli relicense grant

---

RELICENSE/egomotion.md

Added egomotion.md relicense file

Relicense - Robert Castle / Egomotion Ltd

---

RELICENSE/Bklyn.md

Relicense: Caleb Epstein (Bklyn)

---

RELICENSE/HaraldAchitz.md

add relicense file

---

AUTHORS

Soloution: add me on the authors list

Problem: not on the authors list

---

RELICENSE/fidlej.txt

RELICENSE: Ivo Danihelka grant

---

RELICENSE/ChuckRemes.md

Pull request for relicensing effort.

Relicense - Chuck Remes

---

RELICENSE/BerndPrager.md

license grant

---

RELICENSE/tabe.md

RELICENSE: Takeshi Abe

---

RELICENSE/reza-ebrahimi.md

Relicense: Reza Ebrahimi <reza-ebrahimi>

---

RELICENSE/Hugne.md

Relicensing permission statement

Relicense: Erik Hugne

---

RELICENSE/michael-fox.txt

@gitfoxi pull request #2422 contained un-relevant commit 5 years ago.
Cherry picked the correct commit and sending a pull request.
@bluca as the commit is by gitfoxi I think it is ok

relicense michael fox

---

RELICENSE/LionelOrry.md

Added my license grant to the RELICENSE directory

RELICENSE: License grant by Lionel Orry

---

RELICENSE/StoianIvanov

Relicense Grant

---

RELICENSE/willstrang.md

RELICENSE: William P Strang grant

---

RELICENSE/jimklimov.md

Solution: add jimklimov.md for my part

Problem: need to relicense libzmq

---

RELICENSE/mditzel.md

RELICENSE: Maarten Ditzel

---

src/msg.hpp

Problem: typo in comment.

---

RELICENSE/bjorntopel.md

RELICENSE: Björn Töpel / bjoto

---

RELICENSE/goodfella_ltd.md

This is the relicensing grant that was requested.  Thanks again for the great library.

RELICENSE: Nick Guiffrida grant

---

RELICENSE/ianbarber.md

Problem: Zero MQ needs relicensing.
As requested, thanks!

RELICENSE: Ian Barber grant

---

RELICENSE/linville.md

RELICENSE: Aaron Linville grant

---

RELICENSE/jemc.md

Problem: No relicense file for jemc contributions.

---

src/curve_server.cpp
src/gssapi_server.cpp
src/msg.hpp
src/null_mechanism.cpp
src/plain_server.cpp
src/session_base.cpp
tests/test_heartbeats.cpp

See also https://github.com/zeromq/libzmq/issues/2481

Problem: insufficient error handling relative to zap_connect.

---

src/curve_server.cpp
src/gssapi_server.cpp
src/msg.cpp
src/msg.hpp
src/null_mechanism.cpp
src/plain_server.cpp
src/proxy.cpp
src/sub.cpp
src/xpub.cpp
tests/test_xpub_welcome_msg.cpp

See https://github.com/zeromq/libzmq/issues/2481

Problem: msg_t leaks/unhandled failures (and bad style).

---

RELICENSE/ptroja.md

RELICENSE: Piotr Trojanek grant

---

RELICENSE/brunobodin.md

RELICENSE : Bruno Bodin grant

---

RELICENSE/jakecobb.md

Relicensing permission from Jake Cobb

RELICENSE: Jake Cobb grant

---

RELICENSE/bjovke.md

Relicense bjovke

---

RELICENSE/eburkitt.txt

Add relicense grant for eburkitt

---

src/tcp_address.cpp

fix a typo - assigment was used instead of comparison

---

RELICENSE/meox.md

adding licence

---

src/proxy.cpp
src/socket_poller.cpp

Code reformatting of proxy.cpp.

Reworked zmq::proxy() for improved performance.

---

RELICENSE/kurdybacha.md

RELICENSE: Pawel Kurdybacha grant

---

RELICENSE/Asmod4n.md

Problem: no relicense grant for Hendrik Beskow
Solution: add relicense grant

RELICENSE: Hendrik Beskow grant 

---

RELICENSE/rikvdh.md

RELICENSE: Grant from rikvdh

---

RELICENSE/michicc.md

RELICENSE: Grant from michicc

---

RELICENSE/flub.md

Grant permission to relicense to MPL

---

RELICENSE/rotty.md

Relicensing grant from rotty

---

RELICENSE/LeonardMichelet

Giving authorization for re-licensing for my previous commit

license right grant from Leonard Michelet

---

RELICENSE/jruffin.md

As requested in @rlenferink's mail from a while ago.

Added the license grant for jruffin

---

src/router.cpp
tests/test_reqrep_ipc.cpp

Revert "Problem: REP leaves label msgs for dead REQ in pipe"

---

RELICENSE/kentzo.md

RELICENSE: Ilya Kulakov

---

src/pipe.cpp

Problem: intermittent memory leak for req/rep send/recv. #2602 Solution: memory leak fixed.

---

RELICENSE/mattconnolly.md

RELICENSE: Matt Connolly

---

tests/test_security_curve.cpp

Solution: removed code duplication
improved global variable naming
added assertions on number of ZAP requests handled
added assertion on monitor event to test_curve_security_with_plain_client_credentials
add EPIPE workaround at another place, unify two code fragments to remove duplication

Problem: open TODOs in test code, CI failures

---

perf/local_thr.cpp
perf/remote_thr.cpp

Adds CURVE option to throughput performance testing tools.
Adjusts throughput calculation to have more accurate Mb/s 
on large/slow messages.

CURVE throughput performance testing

---

perf/local_thr.cpp

https://github.com/zeromq/libzmq/issues/2676#issuecomment-321909893

Problem: unused variables causing warnings or breaks.

---

perf/remote_thr.cpp

missed one here https://github.com/zeromq/libzmq/issues/2676

Problem: unused variable causing warnings or breaks.

---

Makefile.am
configure.ac
src/curve_client.cpp
src/curve_client.hpp
src/curve_client_tools.hpp
src/curve_server.cpp
src/mechanism.cpp
src/mechanism.hpp
tests/CMakeLists.txt
tests/test_security_curve.cpp

Solution: add tests with misbehaving ZMTP-CURVE client

[WIP, do not merge] Problem: insufficient tests for ZMTP-CURVE protocol errors

---

RELICENSE/sigiesec.md

Solution: added relicense agreement

Problem: no relicense agreement by sigiesec

---

src/gssapi_mechanism_base.cpp

Solution: emit an ZMQ_EVENT_HANDSHAKE_FAILED_PROTOCOL event instead of using zmq_assert

Problem: gssapi_mechanism_base_t aborts the application when it receives a message it cannot decode

---

.travis.yml
ci_build.sh
include/zmq.h
packaging/debian/control
packaging/debian/rules
packaging/debian/zeromq.dsc.obs
packaging/redhat/zeromq.spec
src/gssapi_client.cpp
src/gssapi_mechanism_base.cpp
src/gssapi_mechanism_base.hpp
src/gssapi_server.cpp
src/gssapi_server.hpp
src/zmq_draft.h

Problems: GSSAPI builds broken with picky compilers, Debian/RPM packages do not use GSSAPI, no CI jobs that test GSSAPI

---

packaging/redhat/zeromq.spec

Problem: RPM -devel still ships libzmq.la

---

doc/zmq_setsockopt.txt
tests/test_sockopt_hwm.cpp

Solution: Relax assertion and update documentation accordingly
Fixes #2686

Problem: test_sockopt_hwm fails occasionally

---

README.md

Solution: add brief description and links

Problem: packages builds not mentioned in README.md

---

Makefile.am
tests/CMakeLists.txt
tests/test_socket_null.cpp

Problem: no tests for socket-related functions passing NULL as socket

---

src/proxy.cpp
src/socket_poller.cpp
src/socket_poller.hpp
src/zmq.cpp
tests/test_poller.cpp
tests/test_system.cpp
tests/testutil.hpp

Solution: added test cases, aligned behaviour for some corner cases, removed unreachable code

Problem: insufficient tests for zmq_poller_*

---

src/timers.cpp
src/timers.hpp
tests/test_timers.cpp

Solution: added tests, fixed handling of corner cases

Problem: insufficient tests for zmq_timers_* and inadequate behaviour in corner cases

---

builds/coverage/ci_build.sh

Solution: exclude tweetnacl from coverage

Problem: coverage includes tweetnacl, which is not our code

---

.github/issue_template.md

Solution: provide template for bug reports

Problem: bug reports are often missing relevant information

---

builds/cmake/platform.hpp.in
tests/CMakeLists.txt

Solutions: see commits
Fixed #2728

Problems: ZMQ_HAVE_O_CLOEXEC not defined by CMake, support for CMake << 3.1 broken

---

src/select.cpp
src/select.hpp
src/session_base.cpp

Solution: Fix zmq::select_t::rm_fd and zmq::session_base_t::engine_error
Fixes #2723

Problem: assertion in src\select.cpp:111 on Windows or hang on zmq_ctx_destroy

---

src/session_base.cpp
src/socket_base.cpp
tests/test_poller.cpp

Problems: compiler warnings

---

src/mechanism.cpp
src/plain_client.cpp

Fix https://www.viva64.com/en/w/V1001/print/

Variable is assigned but is not used until the end of the function

---

src/proxy.cpp
tests/test_proxy.cpp

Solution: split each stat into its own frame, to make it simpler and
easier to use it, especially from high level bindings

Problem: proxy_steerable STATISTICS returns conflated buffers

---

src/proxy.cpp

Problems: typos in proxy_steerable stats

---

AUTHORS
RELICENSE/google.md

Relevant commits: ddb82a546b8786b23b977087000e296589529cb2, 68f5926ec65d33043ba3f1687e49d1e6abe47fa2
Also adds AUTHORS entry that should have been part of the previous commits.

RELICENSE: Google, Inc.

---

tests/test_security_curve.cpp
tests/test_security_zap.cpp
tests/testutil_security.hpp

receive an ERROR (probably because the connection is closed before)
Solution: wait for client-side monitor events before closing the client
socket
Fixes #2705

Problem: tests where client should receive an ERROR sometimes do not

---

m4/ax_code_coverage.m4

Solution: update it
Fixes #2770

Problem: lcov autoconf macro out of date

---

src/ipc_listener.cpp
tests/test_rebind_ipc.cpp

Problems: IPC event_closed logs -1 as the FD, couple small fixes for test_rebind_ipc

---

RELICENSE/arsenm.md

Add my RELICENSE

---

doc/zmq_ctx_set.txt
tests/test_ctx_options.cpp

Solutions: document them and fix the test ifdefs

Problems: no documentation for new thread affinity and priority options, test_ctx_options only checks global DRAFT flag

---

Makefile.am
configure.ac
packaging/debian/control
packaging/debian/rules
packaging/debian/zeromq.dsc.obs

Solutions: use pkg-config and enable debian builds

Problems: autoconf does not use pkgconfig for NORM, deb packages do not build with libnorm

---

doc/zmq_proxy_steerable.txt

Add docs for new proxy command over control socket added in DRAFTS

Add documentation for new steerable proxy command

---

.travis.yml
ci_build.sh

Solution: install package and enable the build on some Linux jobs

Problem: Travis does not build with NORM

---

doc/zmq_ctx_set.txt

More docs for ZMQ_THREAD_PRIORITY and ZMQ_THREAD_AFFINITY

Increase details in docs

---

src/ctx.cpp
src/mechanism.cpp
src/pgm_receiver.cpp
src/radio.cpp
src/server.cpp
src/socket_base.cpp
src/stream_engine.cpp

Solution: use std::map::emplace instead, where available

Problem: use of std::map::insert is inefficient

---

src/router.cpp

Solution: create referencing blob_t

Problem: one missed optimization opportunity for blob_t map lookup

---

include/zmq.h
src/condition_variable.hpp
src/windows.hpp

Partial Windows XP support

---

doc/zmq_msg_init.txt

… zmg_msg_recv style functions.
```
```
git push -f …

Change zmq_recv to zmg_msg_recv since zmq_msg_t used there.

---

tests/test_stream_exceeds_buffer.cpp

Solution: bind to wildcard and let the OS pick a free port instead
of using an hard-coded 12345 TCP port

Problem: test_stream_exceeds_buffer cannot be ran in parallel

---

NEWS
doc/zmq_socket_monitor.txt
include/zmq.h

Problems: no NEWS for 4.2.3, missing some events docs, whitespace in header

---

CMakeLists.txt
NEWS
builds/cmake/platform.hpp.in
builds/gyp/platform.hpp
configure.ac
src/ipc_listener.cpp
src/tcp_listener.cpp

Solution: check for availability in CMake and autoconf before using it

Problem: accept4 not available on all platforms

---

NEWS

Problem: ZMQ_LINGER doc change not in NEWS

---

NEWS

Problem: DRAFT API change not in NEWS

---

Jenkinsfile

Solution: Introduce Jenkinsfile

Problem: No Jenkinsfile

---

Makefile.am

fix missing file ZeroMQConfig.cmake.in in the release process by adding in Makefile.am

add ZeroMQConfig.cmake.in in EXTRA_DIST

---

src/timers.cpp

Solution: use comparison operator.

Problem: fn pointers are not bool (vc++ warning C4550).

---

Jenkinsfile

Mostly transplanted from czmq Jenkinsfile, as before, since libzmq is still not handled by zproject directly.

Update Jenkinsfile according to current zproject template

---

src/address.hpp
src/decoder_allocators.hpp
src/encoder.hpp
src/mailbox_safe.hpp
src/mechanism.hpp
src/metadata.hpp
src/object.hpp
src/signaler.cpp
src/socket_base.hpp
src/stream_engine.hpp
src/tcp_connecter.cpp
src/tcp_connecter.hpp
src/v1_decoder.hpp

Solution: add const where easily possible
Note: this requires #2908 to be merged first.

Problem: several fields are non-const without need

---

src/mechanism.cpp
src/mechanism.hpp
src/socket_base.cpp

Solution: see individual commits
This PR requires #2908 to be merged first.

Problem: code style issues in mechanism_t and socket_base_t

---

src/atomic_ptr.hpp
src/dish.cpp
src/options.cpp
src/options.hpp
src/own.cpp
src/socket_base.cpp
src/xsub.cpp

Solution: make options.linger atomic
Note: this requires #2908 to be merged first.

Problem: race conditions for options.linger

---

include/zmq.h
src/options.cpp
src/options.hpp
src/signaler.cpp
src/tcp.cpp
src/tcp.hpp
src/tcp_connecter.cpp
src/tcp_listener.cpp
src/zmq_draft.h
tests/test_pair_tcp.cpp

Fixes #2899 
This PR requires #2908 to be merged first.

Add support for SIO_LOOPBACK_FAST_PATH on Windows

---

src/radio.cpp
src/radio.hpp

Add support for ZMQ_XPUB_NODROP on ZMQ_RADIO sockets

---

Makefile.am
configure.ac

Solution: port implementation from zproject
@sigiesec FYI, it seems to work

Problem: make format-check not implemented with autotools

---

src/poll.cpp
src/poll.hpp

Fixed a deadlock and an assertion failure in poll_t

---

src/poll.cpp
src/poll.hpp
src/poller_base.cpp
src/poller_base.hpp
src/select.cpp
src/select.hpp
src/thread.cpp
src/thread.hpp

Solution: see individual commits

Problem: data races in select/poll poller implementations

---

unittests/unittest_poller.cpp

Solution: fix order of statements in test_events_t

Problem: race condition in unittest_poller

---

.github/PULL_REQUEST_TEMPLATE.md
src/generic_mtrie_impl.hpp
src/ip.cpp
src/socket_base.cpp
src/tcp_connecter.cpp
src/zmq.cpp

Solution: apply fixes and add info to PR template

Problem: CI check for format fails

---

src/options.cpp
src/options.hpp
src/router.cpp
src/socket_base.cpp
src/stream.cpp
src/sub.cpp

Solution: extracted common code into do_getsockopt/do_setsockopt functions

Problem: code duplication in getsockopt/setsockopt

---

src/ip.cpp
src/options.cpp
src/socket_base.cpp
src/socks_connecter.cpp
src/tcp_connecter.cpp
src/tweetnacl.c
src/ypipe.hpp
src/ypipe_conflate.hpp
src/zmq.cpp

Solution: ignore tweetnacl.c and reformat the rest

Problem: formatting issues in CI

---

tests/README.md
tests/test_hwm.cpp
tests/test_router_mandatory.cpp
tests/test_sockopt_hwm.cpp
tests/testutil_unity.hpp

@eponsko Please have a look if this is what you expected.

Problem: test assertion failures do not clean up properly

---

Makefile.am
tests/test_bind_after_connect_tcp.cpp
tests/test_bind_src_address.cpp
tests/test_client_server.cpp
tests/test_conflate.cpp
tests/test_connect_resolve.cpp
tests/test_router_handover.cpp

Migrate more tests to unity

---

Makefile.am
tests/CMakeLists.txt
tests/test_ctx_destroy.cpp
tests/test_poller.cpp
tests/test_reconnect_ivl.cpp
tests/test_thread_safe.cpp
tests/testutil_unity.hpp

Migrate further tests to unity, and split up into individual test cases

---

src/udp_engine.cpp

Sigiesec noticed a superfluous errno_assert() in my previous commit

Problem: Unnecessary errno_assert

---

builds/cmake/ci_build.sh
ci_build.sh

Problem: clang-format Travis job broken

---

src/tweetnacl.c

Solution: change comments
Fixes: #3036

Problem: C++ style comments in C file breaks pedantic build

---

doc/zmq_socket.txt

Solution: add note like for radio-dish
Fixes: #3050

Problem: Server-client not marked as DRAFT in manpage

---

AUTHORS
RELICENSE/simias.md

Add me to AUTHORS + RELICENSE file

---

Makefile.am
src/ip_resolver.cpp
src/ip_resolver.hpp
src/socket_base.cpp
src/udp_address.cpp
src/udp_address.hpp
src/udp_engine.cpp
tests/test_radio_dish.cpp
unittests/CMakeLists.txt
unittests/unittest_ip_resolver.cpp
unittests/unittest_resolver_common.hpp
unittests/unittest_udp_address.cpp

Far from complete but I could use some feedback

UDP Ipv6 support

---

src/blob.hpp
src/ctx.cpp
src/mechanism.cpp
src/options.hpp
src/socket_base.cpp
src/stream_engine.cpp
src/tcp.hpp
tests/test_system.cpp

Solutions: see commits
Fixes #3090

Problem: build broken on Solaris with Sun Studio compilers

---

tests/test_radio_dish.cpp

Since I can't reproduce the error locally I don't know if this actually fixes the problem but I though it was worth a try.

Problem: test_radio_dish triggers aliasing errors with some compilers

---

doc/zmq.txt
doc/zmq_poller.txt
doc/zmq_poller_add.txt
doc/zmq_poller_add_fd.txt
doc/zmq_poller_destroy.txt
doc/zmq_poller_modify.txt
doc/zmq_poller_modify_fd.txt
doc/zmq_poller_new.txt
doc/zmq_poller_remove.txt
doc/zmq_poller_remove_fd.txt
doc/zmq_poller_wait_all.txt
doc/zmq_setsockopt.txt
src/socket_poller.cpp
src/zmq.cpp
tests/test_poller.cpp

Added initial documentation for zmq_poller_* functions.
Fixes #2188 
@bluca, @somdoron, @kurdybacha Maybe you can have a look?

Add poller docs

---

tests/test_heartbeats.cpp

Problem: heartbeat tests are disabled

---

Makefile.am
tests/test_spec_dealer.cpp
tests/testutil_unity.hpp

Problem: test_spec_dealer not using test framework

---

Makefile.am
tests/test_inproc_connect.cpp

Problem: test_inproc_connect not using test framework

---

Makefile.am
configure.ac

Solution: fix directory reference

Problem: autotools build broken

---

.travis.yml

Problem: missing sonarqube token

---

appveyor.yml

Solution: disabled parallel testing for these VS versions
Related to #3123 but it does not fix it, it must be investigated why the tests fail when run in parallel.

Problem: VS2008/2010/2017 tests fail if run in parallel

---

CMakeLists.txt
configure.ac
src/tipc_connecter.cpp

Solution: see commit
Fixes #3131

Problem: build broken with clang 6 on Android NDK 17

---

src/mechanism.cpp
src/mechanism.hpp
src/router.cpp
src/router.hpp
src/socket_base.cpp
src/socket_base.hpp
src/stream.cpp
src/stream.hpp

Remove duplication between stream_t and router_t

---

.travis.yml
builds/cmake/ci_build.sh
src/plain_server.cpp
src/udp_engine.cpp

Few more code style fixes

---

Makefile.am
acinclude.m4
configure.ac

Solution: add wepoll as a polling system

Problem: not able to use wepoll in configure script

---

CMakeLists.txt
appveyor.yml

Note: some tests are currently failing, which need to be fixed in a separate effort. these are ignored for the overall result of the appveyor
Fixes #3030

Add cygwin64 CI on Appveyor

---

doc/zmq_setsockopt.txt

Updated `zmq_setsockopt` docs for `ZMQ_CONFLATE`  
Details of issue: https://github.com/zeromq/libzmq/issues/3171

Update conflate docs to cover issue #3171

---

src/ctx.cpp
src/dish.cpp
src/dish.hpp
src/ip_resolver.cpp
src/mailbox_safe.cpp
src/own.cpp
src/poller_base.cpp
src/radio.cpp
src/router.cpp
src/signaler.cpp
src/socket_base.cpp
src/timers.cpp

Simplified and optimized several code fragments

---

external/wepoll/version.txt
external/wepoll/wepoll.c

Solution: update to wepoll 1.5.2

Problem: wepoll outdated

---

src/ctx.cpp
src/dish.cpp
src/epoll.cpp
src/generic_mtrie.hpp
src/generic_mtrie_impl.hpp
src/mailbox_safe.cpp
src/mechanism.cpp
src/own.cpp
src/pgm_receiver.cpp
src/pipe.cpp
src/poller_base.cpp
src/radio.cpp
src/router.cpp
src/server.cpp
src/socket_base.cpp
src/socket_poller.cpp
src/stream_engine.cpp
src/stream_engine.hpp
src/timers.cpp

Code style improvements

---

RELICENSE/hoditohod.md

Relicense grant from Szekely Gyorgy.

RELICENSE: Szekely Gyorgy

---

RELICENSE/ByronMallett.md

Added relicensing permissions for Byron Mallett

RELICENSE: Byron Mallett

---

RELICENSE/ChristophSchulz.md

RELICENSE: Christoph Schulz

---

RELICENSE/FabriceFontaine.md
acinclude.m4

Commit 2ec5a33f6e986661dc92f3585ea400f919a39cae added support to link
with -latomic if needed however using LDFLAGS doesn't work when
statically linking because LDFLAGS is added before LIBS
Detection of atomic fails with:
configure:23230: /accts/mlweber1/instance-2/output/host/bin/sparc-linux-g++ -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -static -static -pedantic -Werror -Wall -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -Wno-long-long -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -static -latomic conftest.cpp -lrt -lpthread -lstdc++ >&5
/tmp/ccgrvVTg.o: In function `main':
conftest.cpp:(.text.startup+0x10): undefined reference to `__atomic_fetch_add_4'
collect2: error: ld returned 1 exit status
So use LIBS instead of LDFLAGS …

fix static build with libatomic

---

RELICENSE/FrancescoMontorsi.md

Relicensing for previous contributions

add relicensing grant

---

tests/test_hwm_pubsub.cpp

This PR changes test_hwm_pubsub to use XPUB and wait for subscription before start to sending messages out

Fix for test_hwm_pubsub

---

tests/test_hwm_pubsub.cpp

Title says pretty much all. This PR removes the need for msleep() from test_blocking().
Question is whether we should change also test_defaults() and test_reset_hwm() functions, which still employ msleep() calls for synching pub/sub.

Remove race condition from XPUB/SUB test in test_blocking()

---

.github/PULL_REQUEST_TEMPLATE.md

Solution: add note in PR template
This is how it looks like:
https://github.com/bluca/libzmq/blob/issue_pr_text/.github/PULL_REQUEST_TEMPLATE.md

Problem: have to ask manually for relicensing grant

---

RELICENSE/gabm.md

Problem: gabm didn't signalise his consent to relicense libzmq

---

src/xsub.hpp

Solution: use it only for DRAFT builds for now, to leave it time to be
tested and stabilised.

Problem: new radix tree implementation is experimental

---

NEWS

Solution: mention all relevant bug fixes, features and changes

Problem: NEWS still out of date

---

.github/stale.yml

Solution: try again without escaping the space

Problem: stale bot didn't parse labels correctly

---

Makefile.am
configure.ac
src/session_base.cpp
src/session_base.hpp
src/zmq.cpp
tests/test_filter_ipc.cpp
tests/test_hwm_pubsub.cpp
tests/test_reconnect_ivl.cpp

Problem: build broken with Sun Studio, tests fail on debian/kfreebsd and debian/hurd, DRAFT zmq_poll is slow

---

src/session_base.cpp
src/session_base.hpp

Re-apply the changes from  6d7aeb0 and fix Sun Studio compilation issues.

Reapply session_base_t refactoring

---

NEWS

Problem: #3263 not mentioned in NEWS

---

configure.ac

Solution: add a switch and a default to autoconf

Problem: radix tree never used in autotools builds

---

external/wepoll/version.txt
external/wepoll/wepoll.c

Solution: Update to upstream version 1.5.4

Problem: wepoll 1.5.2 is outdated

---

RELICENSE/jcourreges.txt

Relicensing grant for my contributions (jcourreges)

---

Makefile.am
configure.ac

Now that #3322 has been pushed, the autotools code can be further simplified.

Platforms conditionals cleanup

---

Makefile.am
tests/test_pair_inproc.cpp
tests/test_pair_ipc.cpp
tests/test_pair_tipc.cpp
tests/test_rebind_ipc.cpp
tests/test_req_relaxed.cpp
tests/test_spec_req.cpp

Problem: tests without test framework

---

src/radix_tree.cpp
src/radix_tree.hpp

Solution: remove unused import and fix const placement

Problem: unused import and inconsistent use of const

---

NEWS

Problem: NEWS out of date with recent changes

---

tests/test_rebind_ipc.cpp

Solution: create manually the random IPC file to reuse

Problem: test_rebind_ipc still fails

---

.gitignore
include/zmq.h
tests/test_monitor.cpp
tests/testutil_monitoring.hpp

Problems: ipv6 test_monitor hangs, old Windows build fails

---

src/stream_listener_base.cpp

Solution: add missing includes to stream_listener_base
@sigiesec listener had same issue

Problem: build broken with newer gcc

---

src/mailbox_safe.cpp
src/socks_connecter.cpp
src/tcp.cpp
src/tcp.hpp
src/tcp_connecter.cpp
src/tcp_listener.cpp
tests/test_pair_tcp.cpp
tests/testutil_unity.hpp

Fix regression introduced by 68d520e

---

Makefile.am
src/ip.cpp
src/ip.hpp
src/tcp.cpp
tests/CMakeLists.txt
tests/test_pair_tcp_cap_net_admin.cpp

Add test for ZMQ_BINDTODEVICE

---

src/ctx.cpp
src/io_thread.cpp
src/thread.cpp
src/thread.hpp
src/zmq_utils.cpp

Problem: non-linux build broken by last PR

---

RELICENSE/calid.md

Ref: #2376
Thank you to the libzmq maintainers for your efforts post Pieter's death, it is much appreciated

Relicense: Dylan Cali

---

RELICENSE/somdoron.md

Problem: missing relicensing statement from somdoron

---

RELICENSE/pnnl

Solution: add the one received by email
B671D81EAD34104986FFE7881B8036371ABEF4AF@EX10MBOX02.pnnl.gov

Problem: no relicense grant from PNNL

---

RELICENSE/pmienk.md

RELICENCE: Phillip Mienk grant

---

RELICENSE/micromass-ricnewton.md

RELICENSE: Received grant from Micromass UK Limited

---

RELICENSE/pnnl.md

RELICENSE: Converted pnnl to markdown

---

RELICENSE/mgatny.md

Problem: missing relicensing statement from mgatny

---

README.md
SupportedPlatforms.md

Solution: add an initial version

Problem: no documentation of supported platforms

---

RELICENSE/vortechs2000.md

Add Quantum's relicense grant for my work on libzmq

Add relicense grant

---

RELICENSE/steve-o.md

Relicense: steve-o

---

RELICENSE/shancat.md

Adding grant from shancat

---

RELICENSE/leonarf.md

Corrected info listed in license grant

RELICENSE: Corrected info for leonarf

---

RELICENSE/brett-cameron.md

```
```
Please try to have the code changes conform to our coding style. For your
convenience, you can install clang-format (at least version 5.0) and then
run ```make clang-format-check```. Don't fix existing issues, if any - just
make sure your changes are compliant. ```make clang-format-diff``` will
automatically apply the required changes.
To set a specific clang-format binary with autotools, you can for example
run: ```./configure CLANG_FORMAT=clang-format-5.0```
are impossible to fix once merged. Please rebase …

RELICENSE: Brett Cameron

---

RELICENSE/hewlett_packard_enterprise.md

Received via email on 2019/03/12, message-id:
TU4PR8401MB1277B86B48464DC63AEDCA2D96490@TU4PR8401MB1277.NAMPRD84.PROD.OUTLOOK.COM

Relicensing grant from HPE

---

tests/test_hwm_pubsub.cpp

Some improvements to test_hwm_pubsub to investigate #3465

Improve hwm pubsub test

---

doc/zmq_getsockopt.txt
doc/zmq_setsockopt.txt
doc/zmq_socket.txt

Problems: formatting errors in docs reported by linters

---

src/plain_common.hpp

Solution: change to HELLO
Fixes #3500

Problem: PLAIN HELLO message incorrectly uses WELCOME literal

---

tests/test_monitor.cpp

Problem: Potentially unitialized variable in #3508

---

Makefile.am
doc/zmq_setsockopt.txt
doc/zmq_socket_monitor_versioned.txt
include/zmq.h
src/xpub.cpp
src/xpub.hpp
src/zmq.cpp
src/zmq_draft.h
tests/test_monitor.cpp

Problems: typos in docs, unnecessary ifdefs, duplicated APIs

---

.travis.yml
src/options.cpp
src/socket_base.cpp
src/socks_connecter.cpp
src/tcp_connecter.cpp
src/udp_engine.cpp
src/ypipe.hpp
src/ypipe_conflate.hpp
src/zmq.cpp

Problem: clang-format 5 has issues with comments

---

src/thread.cpp

Problem: build is broken on Fedora 30 after merging last PR
Solution: fix build :)

Fix Fedora 30 build

---

RELICENSE/philippeleite.md
src/options.cpp
src/session_base.cpp
src/socks.cpp
src/socks_connecter.cpp
src/thread.cpp

Solution: apply clang-format-diff

Problem: formatting errors

---

appveyor.yml

Solution: deploy artifcats to bintray
You can find the repository here:
https://dl.bintray.com/zeromq/generic/
I manually built 4.3.1, next versions should release a version automatically.

problem: no artifact repository for windows

---

appveyor.yml

solution: add x64 builds to appveyor

problem: no artifacts for x64 on windows

---

src/radix_tree.cpp

Solution: rewrite the function using a vector
The buffer is extended once by 256 bytes, which will not be enough if
the node holds data larger than this number.

Problem: radix tree's apply function uses incorrect resizing logic

---

perf/benchmark_radix_tree.cpp
src/radix_tree.cpp
src/radix_tree.hpp
src/xsub.hpp
unittests/unittest_radix_tree.cpp

Solution: rename types/variables that are inconsistent

Problem: code doesn't follow libzmq naming conventions

---

RELICENSE/lourens.md

```
```
Please try to have the code changes conform to our coding style. For your
convenience, you can install clang-format (at least version 5.0) and then
run ```make clang-format-check```. Don't fix existing issues, if any - just
make sure your changes are compliant. ```make clang-format-diff``` will
automatically apply the required changes.
To set a specific clang-format binary with autotools, you can for example
run: ```./configure CLANG_FORMAT=clang-format-5.0```
are impossible to fix once merged. Please rebase …

Add relicense agreement from Lourens Naudé

---

appveyor.yml

problem: wrong api_key for bintray

---

perf/benchmark_radix_tree.cpp

Problem: unused parameter in benchmark function

---

NEWS
external/sha1/license.txt
src/stdint.hpp
src/ws_connecter.cpp
src/ws_connecter.hpp
src/ws_decoder.cpp
src/ws_decoder.hpp
src/ws_encoder.cpp
src/ws_encoder.hpp
src/ws_engine.cpp
src/ws_engine.hpp
src/ws_listener.cpp
src/ws_listener.hpp
src/ws_protocol.hpp

Problems: build broken on centos6/ubuntu12, missing licenses and wrong copyright dates

---

src/radix_tree.cpp

Problem: redundant check in condition

---

src/thread.cpp

Solution: fix them with make clang-format-diff

Problem: formatting errors introduced by #3601

---

README.md
RELICENSE/hsw.md

Information missing from my previous PR

Re-license grant + suggested readme update

---

RELICENSE/drbobbeaty.md

Just following the instructions in the email to add my agreement.

Added my relicense doc

---

RELICENSE/malexzx.md

Grant received via Github PR comment:
https://github.com/zeromq/libzmq/pull/1413#issuecomment-520233278

RELICENSE: Aleksander Melnikov

---

RELICENSE/jens.auer.md

Hi,
here is my relicense statement.
Cheers,
Jens

Add relicense statement

---

perf/generate_csv.sh
perf/generate_graphs.py

This PR updates the 2 scripts I used to produce the graphs at
http://zeromq.org/results:10gbe-tests-v432
http://zeromq.org/results:100gbe-tests-v432
(previous PR was mostly a work-in-progress... this one updates the script to include better defaults and a little bit more documentation)

Scripts for graphing benchmark results

---

RELICENSE/hnwyllmm.md

Adds relicensing grant

---

RELICENSE/chymanfx.md

Grant received by PR comment:
https://github.com/zeromq/libzmq/pull/3195#issuecomment-520338586

RELICENSE: chymanfx

---

RELICENSE/dkrikun.md

CAMohcw2mZMPku8OV0Ge0-8+D3a6ayLR=6ivWjVmT0UU_ejZxiA@mail.gmail.com

RELICENSE: add grant by Daniel Krikun

---

RELICENSE/spotify.md

Granted by myself on behalf of Spotify for @gimaker, and @danielnorberg, who were contacted internally.

Add relicense agreement from Spotify AB

---

RELICENSE/dmeehan1968.md

Received via Github comment:
https://github.com/zeromq/libzmq/pull/1082#issuecomment-526840485

Grant by dmeehan1968

---

RELICENSE/mvilim.md

Relicensing permission as requested in #3193.

Relicense permission

---

RELICENSE/rcxdude.md

Add my permission to relicense under MPL-2

Add relicense permission

---

RELICENSE/skaller.md

B7B30120-05AF-4A53-8023-D9C092DE0873@internode.on.net

Grant by skaller

---

RELICENSE/kreuzberger.md

Received via Github comment:
https://github.com/zeromq/libzmq/pull/1374#issuecomment-527100078

Grant by kreuzberger

---

RELICENSE/psl-felipefarinon.md

Received via Github message:
https://github.com/zeromq/libzmq/pull/751#issuecomment-527205167

Grant by psl-felipefarinon

---

CMakeLists.txt
Makefile.am
src/address.cpp
src/address.hpp
src/ip_resolver.cpp
src/ip_resolver.hpp
src/socket_base.cpp
src/ws_address.cpp
src/ws_address.hpp
src/ws_connecter.cpp
src/ws_engine.cpp
src/ws_engine.hpp
src/ws_listener.cpp
tests/test_ws_transport.cpp

Solution: extract path and host from the address

problem: ws_engine doesn't send correct host and path

---

src/ws_engine.cpp
src/ws_engine.hpp

Solution: Validate Sec-WebSocket-Protocol and make sure ZWS2.0 is one of the protocols

problem: ws_engine doesn't check Sec-WebSocket-Protocol

---

RELICENSE/RPGillespie6.md

Received by Github comment:
https://github.com/zeromq/libzmq/pull/2536#issuecomment-528961084

Relicense granby by RPGillespie6

---

RELICENSE/jcfr.md

See https://github.com/zeromq/libzmq/pull/3181#issuecomment-526829225
Cc: @bluca

Relicense: Jean-Christophe Fillion-Robin

---

RELICENSE/mongodb.md

Received by Github comment:
https://github.com/zeromq/libzmq/pull/1451#issuecomment-537169373

Add grant by MongoDB, Inc.

---

RELICENSE/nixman.md

Submitted as Github comment:
https://github.com/zeromq/libzmq/pull/242#issuecomment-537903446

Add grant by nixman

---

src/ws_decoder.cpp
src/ws_engine.cpp
src/ws_engine.hpp
src/zmq.cpp
tests/test_ws_transport.cpp

Solution: add support to mechanism

problem: WS transport doesn't support mechanism

---

src/stream_engine_base.cpp
src/stream_engine_base.hpp
src/wss_engine.cpp
src/wss_engine.hpp

Solution: return -1 for errors

problem: wss transport return incorrect return code for error

---

.gitignore
appveyor.yml
tests/test_xpub_nodrop.cpp

WIP: problem: appveyor is failing

---

src/ip_resolver.cpp
src/thread.cpp
src/thread.hpp
src/udp_address.cpp
tests/test_radio_dish.cpp
tests/testutil.cpp

Solution: fix build issues
Fixes #3694

Problem: build targeting Windows XP is broken

---

builds/deprecated-msvc/vs2010/libzmq/libzmq.props
builds/deprecated-msvc/vs2010/libzmq/libzmq.vcxproj
builds/deprecated-msvc/vs2010/libzmq/libzmq.vcxproj.filters
builds/deprecated-msvc/vs2010/libzmq/libzmq.xml
builds/deprecated-msvc/vs2012/libzmq/libzmq.props
builds/deprecated-msvc/vs2012/libzmq/libzmq.vcxproj
builds/deprecated-msvc/vs2012/libzmq/libzmq.vcxproj.filters
builds/deprecated-msvc/vs2012/libzmq/libzmq.xml
builds/deprecated-msvc/vs2013/libzmq/libzmq.props
builds/deprecated-msvc/vs2013/libzmq/libzmq.vcxproj
builds/deprecated-msvc/vs2013/libzmq/libzmq.vcxproj.filters
builds/deprecated-msvc/vs2013/libzmq/libzmq.xml
builds/deprecated-msvc/vs2015/libzmq/libzmq.props
builds/deprecated-msvc/vs2015/libzmq/libzmq.vcxproj
builds/deprecated-msvc/vs2015/libzmq/libzmq.vcxproj.filters
builds/deprecated-msvc/vs2015/libzmq/libzmq.xml
builds/deprecated-msvc/vs2017/libzmq/libzmq.props
builds/deprecated-msvc/vs2017/libzmq/libzmq.vcxproj
builds/deprecated-msvc/vs2017/libzmq/libzmq.vcxproj.filters
builds/deprecated-msvc/vs2017/libzmq/libzmq.xml
packaging/nuget/package.config
packaging/nuget/package.gsl
packaging/nuget/package.nuspec
packaging/nuget/package.targets

This updates the (deprecated) MSVC project files for the v4.3.2 release. Corresponding packages have been uploaded to the NuGet Gallery.

Problem: MSVC projects not current.

---

RELICENSE/benjdero.md
builds/android/android_build_helper.sh
builds/android/ci_build.sh

Linked to the changes made on zeromq/zproject#1211

Add a few quality of life improvements to the Android build scripts

---

CMakeLists.txt
builds/cmake/platform.hpp.in
configure.ac
src/address.cpp
src/address.hpp
src/ip.cpp
src/ipc_address.cpp
src/ipc_address.hpp
src/ipc_connecter.cpp
src/ipc_connecter.hpp
src/ipc_listener.cpp
src/ipc_listener.hpp
src/session_base.cpp
src/socket_base.cpp
src/zmq.cpp
tests/CMakeLists.txt
tests/test_rebind_ipc.cpp
tests/test_reconnect_ivl.cpp
tests/testutil_unity.cpp
tests/testutil_unity.hpp

Solution: implement support
Fixes #3691 
Open points:

Problem: ipc transport not supported under Windows

---

RELICENSE/Botje.md
doc/zmq_poller.txt

Solution: Flip argument order.
Spotted while investigating https://stackoverflow.com/a/58643328/1548468

Problem: Poller example has wrong argument order

---

appveyor.yml
src/ip.cpp
src/ip.hpp
src/ipc_listener.cpp
src/ipc_listener.hpp
tests/test_capabilities.cpp

Use Unix domain sockets for listener when available on Windows

---

.travis.yml

Solution: Update to version 4.2.0.1873

Problem: sonar-scanner binary is outdated and no longer available

---

src/signaler.cpp

Fix windows signaler regression

---

src/msg.cpp
src/msg.hpp
src/stream_engine_base.hpp
src/ws_decoder.cpp
src/ws_encoder.cpp
src/ws_engine.cpp
src/ws_engine.hpp
tests/test_ws_transport.cpp

Solution: implement both PONG response and producing pings

problem: ws_engine don't support WS RFC ping-pong and close

---

RELICENSE/mloy.md
src/ws_address.cpp
src/ws_listener.cpp
tests/test_ws_transport.cpp

websocket urls without a path caused crash!
Same as #3781 with test and relicense file

Fix websocket without path with test

---

NEWS

Problem: NEWS out of date with latest changes

---

doc/zmq_getsockopt.txt
doc/zmq_setsockopt.txt

Just some minor stuff fixed in the documentation for get.../set_sockopt I just noticed.

Some minor documentation fixes

---

tests/CMakeLists.txt

Solution: increase timeout to 15 seconds

Problem: intermittent timeouts of test_reconnect_ivl

---

src/curve_mechanism_base.cpp

Solution: add version check and fall back to old implementation for old versions

Problem: curve_encoding_t build fails with old libsodium versions

---

RELICENSE/gummif.md
doc/zmq_ctx_get.txt
doc/zmq_ctx_set.txt

Problem: Documentation for option name mismatch 

---

RELICENSE/asafkahlon.md

CALFsTFVZLgujRE3V_30G9V9b35kE566K5cWi0vKbNkZGSHrszA@mail.gmail.com

Grant by asafkahlon

---

RELICENSE/KLNikita.md

81ce91c8-df40-13c2-7abf-6f648d0b123f@elyzion.net

Grant from KLNikita

---

src/ws_address.cpp
src/ws_encoder.cpp
src/ws_encoder.hpp
src/ws_listener.cpp
src/wss_address.cpp
tests/test_ws_transport.cpp

solution: if msg is not shared or constant, mask the message in place

websocket problems

---

RELICENSE/ninoles.md

ed4de883-640b-bf7e-ac56-911e117b649e@tzone.org

Add grant by ninoles

---

README.md
builds/android/README.md
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

As a user I simple have to type ./build.sh [arm|arm64|x86|x86_64] now.

Improve android build handling

---

RELICENSE/gcsideal.md

Add relicense grant by Laszlo Boszormenyi (GCS)

---

src/msg.cpp

Problem: msg_t functions do not respect coding style

---

.gitignore

Some files were not ignored by gitignore.  
Most of not-ignored files were similar to other ignored files, so I've optimized it by using patterns/
*  Categorize ignoring lists
*  Use pattern to remove similar lists
*  Marked source files to be tracked

Optimizing gitignore files

---

doc/zmq_send.txt
doc/zmq_send_const.txt

Solution: add const to pointer type

Problem: zmq_send doc does not match declaration

---

doc/zmq_poller.txt

Solution: Add newlines and extra asterisks
See http://api.zeromq.org/4-3:zmq-poller

Problem: Strange zmq_poller doc formatting

---

src/socket_poller.cpp

Solution: Set to zero for socket events

Problem: poller item fd uninitialized

---

src/socket_poller.cpp
src/socket_poller.hpp

Solution: Extract find functinos

Problem: poller item lookup can be simplified

---

doc/zmq_poller.txt
src/socket_poller.cpp
src/zmq.cpp
tests/test_poller.cpp

Solution: Specify an invalid file descriptor for socket events

Problem: Poller event fd unspecified

---

src/fd.hpp
tests/test_poller.cpp
tests/test_system.cpp
tests/testutil.hpp

Problem: Multiple fd_t definitions

---

tests/testutil.cpp

Problem: testutil build broken with gcc 4.4 on CentOS 6

---

src/ipc_connecter.cpp
src/tipc_connecter.cpp
src/tipc_listener.cpp

Solution: use retired_fd instead

Problem: -1 used for invalid socket

---

src/router.cpp

Problem: extra blob copy

---

CMakeLists.txt
Makefile.am
doc/zmq_bind.txt
doc/zmq_connect.txt
doc/zmq_socket.txt
include/zmq.h
src/channel.cpp
src/channel.hpp
src/mechanism.cpp
src/session_base.cpp
src/socket_base.cpp
src/zmq_draft.h
tests/CMakeLists.txt
tests/test_channel.cpp

Solution: create ZMQ_CHANNEL, the thread safe alternative

problem: no thread-safe alternative for ZMQ_PAIR

---

src/i_engine.hpp
src/norm_engine.hpp
src/pgm_receiver.hpp
src/pgm_sender.hpp
src/raw_engine.cpp
src/session_base.cpp
src/session_base.hpp
src/stream_engine_base.cpp
src/stream_engine_base.hpp
src/udp_engine.hpp
src/ws_engine.cpp
src/zmtp_engine.cpp
tests/test_mock_pub_sub.cpp
tests/test_xpub_manual.cpp
tests/test_xpub_manual_last_value.cpp

Solution: delay connecting the peer pipe until the handshake is complete

problem: zeromq connects peer before handshake is complete

---

src/xpub.cpp

Problem: small memory leaks in PUB/XPUB

---

builds/fuzz/ci_build.sh

Solution: move the script to our repo, and simply call it from oss-fuzz's script

Problem: we have to send a PR to oss-fuzz on every build change on the fuzzers

---

Makefile.am
tests/test_bind_ws_fuzzer.cpp
tests/test_connect_ws_fuzzer.cpp
tests/testutil.cpp
tests/testutil.hpp

Solution: add tests for plain WS

Problem: no fuzz testing for websockets

---

RELICENSE/mileschet.md
builds/ios/build_ios.sh

Hi, 
I closed the other pull request and make the modifications pointed out, please let me know if there is anything missing.
Thank you,

added script to compile the lib to iphone sdk >= 13.5

---

builds/android/README.md
builds/android/build.sh
builds/android/ci_build.sh

Solution: Update Android NDK version

Problem: libzmq use outdated Android NDK version

---

src/stream_engine_base.cpp

Solution: bail out of the stream engine out_event if ws_engine raises
an error

Problem: use-after-free in WS

---

src/wss_engine.cpp
src/wss_engine.hpp

Solution: extract do_handshake member function

Problem: code duplicated between handshake and out_event

---

Makefile.am
tests/test_bind_stream_fuzzer.cpp
tests/test_connect_stream_fuzzer.cpp

Problem: no fuzzing coverage for ZMQ_STREAM

---

doc/zmq_ctx_get.txt
doc/zmq_ctx_get_ext.txt
doc/zmq_ctx_new.txt
doc/zmq_ctx_set_ext.txt
doc/zmq_proxy.txt
doc/zmq_proxy_steerable.txt

Solution: document more possible errno values

Problem: not all possible errno values were documented (#4078)

---

RELICENSE/boxkey.md

add relicense.md file boxkey.md

add relicense.md file

---

src/ip.cpp

Solution: Move initialization of variables before gotos.
```
error C2362: initialization of 'lcladdr_len' is skipped by 'goto error_closelistener'
error C2362: initialization of 'saved_errno' is skipped by 'goto try_tcpip'
error C2362: initialization of 'rc' is skipped by 'goto try_tcpip'
```

Problem: Build error on MSVC with C++20 in ip.cpp

---

RELICENSE/mrvn.md
RELICENSE/sradomski.md

As indicated by author's comment on Github:
https://github.com/zeromq/libzmq/pull/810#issuecomment-748587654

Add relicense statement from sradomski and mrvn

---

CMakeLists.txt
RELICENSE/stanpl.md
builds/cmake/platform.hpp.in
configure.ac
src/ip_resolver.cpp
src/udp_address.cpp

Solution: if_nametoindex function is now used when available

---

RELICENSE/mrvn.md

Problem: typo in RELICENSE/mrvn.md

---

.git-blame-ignore-revs
src/ws_encoder.cpp
tests/test_ws_transport.cpp

Problem: PUB+WS broken, git blame hard to use

---

RELICENSE/skaes.md

SOLUTION: add file containing permission statement

PROBLEM: missing permission to relicense commits by GH handle skaes

---

RELICENSE/sab24.md
src/ws_engine.cpp

This fixes issue [#2158 in czmq](https://github.com/zeromq/czmq/issues/2158) and [#18 in jszmq](https://github.com/zeromq/jszmq/issues/18) project

Fixes Firefox WebSocket upgrade request in WebSocket engine

---

src/dgram.cpp
src/dgram.hpp
src/fq.cpp
src/fq.hpp
src/pair.cpp
src/pair.hpp

Problem: Unused member variables _last_in

---

src/polling_util.hpp

Problem: C style malloc and free

---

src/ws_engine.cpp

Problem: strtok is not thread safe

---

.travis.yml
Makefile.am
config.sh
src/vmci.cpp
src/vmci.hpp
src/vmci_address.cpp
src/vmci_address.hpp
src/vmci_connecter.cpp
src/vmci_connecter.hpp
src/vmci_listener.cpp
src/vmci_listener.hpp
tests/test_pair_vmci.cpp
tests/test_reqrep_vmci.cpp

Fixes #4133 - build tested only

Problem: VMCI build broken

---

tests/testutil.hpp

This fixes build under BSD. Tested with OpenBSD-6.4 and FreeBSD-11.3.

Fix Build BSD

---

builds/ios/build_ios.sh

Added the fix suggested by @cyrilchandelier and @bluca in #4100 in order to fix iOS builds

Fix iOS build failure for x86_64

---

builds/android/README.md
builds/android/build.sh
builds/android/ci_build.sh

Solution: Update Android NDK version

Problem: Outdated Android build tools

---

.obs/workflows.yml

Solution: try the new Open Build Service PR integration workflow

Problem: build/test breakages on various distros are discovered only after merge

---

external/wepoll/license.txt
external/wepoll/version.txt
external/wepoll/wepoll.c
external/wepoll/wepoll.h

Solution: update to latest version, v1.5.8
Fixes #4221

Problem: wepoll is out of date, known issues on Windows

---

RELICENSE/yunye-pu.md
src/wss_engine.cpp

Problem: WSS broken under high load

---

src/polling_util.hpp

Solution: init correct vector size and copy previous data into it

Problem: fast vector resize bug

---

RELICENSE/timblechmann.md
src/session_base.hpp
src/stream_engine_base.hpp

silences inconsistent-missing-override warnings for me

add missing override statements

---

README.md

Libzmq on windows on arm64 seems to be working as expected. Mark the platform as supported.
```
Test project C:/Users/niysai01/Workspace/libzmq/build
Start   1: test_ancillaries
1/101 Test   #1: test_ancillaries .................   Passed    2.09 sec
Start   2: test_system
2/101 Test   #2: test_system ......................   Passed    0.66 sec
Start   3: test_pair_inproc
3/101 Test   #3: test_pair_inproc .................   Passed    0.75 sec
Start   4: test_pair_tcp
4/101 Test   #4: test_pair_tcp ....................   Passed    0.67 sec
Start   5: test_reqrep_inproc
5/101 Test   #5: test_reqrep_inproc ...............   Passed    0.56 sec
Start   6: test_reqrep_tcp
6/101 Test   #6: test_reqrep_tcp ..................   Passed    0.75 sec
Start   7: test_pubsub
7/101 Test   #7: …
```

add win/arm64 to supported platform list

---

configure.ac

problem: typo in configure.ac output

---

RELICENSE/tranthamp.md

Adding statement for relicensing effort.

Add license file for tranthamp

---

doc/zmq_socket_monitor_versioned.txt
tests/test_monitor.cpp
tests/testutil_monitoring.cpp
tests/testutil_monitoring.hpp

Solution: change test_monitor and example

Problem: build fails with gcc 12

---

doc/zmq_tcp.txt

Solution: Update with URL to current stable spec

Problem: Docs reference outdated spec

---

builds/android/android_build_helper.sh
builds/android/build.sh

Solution: Fix the recently updated scripts

Problem: Libs crash at runtime on Android when built with NDK 23+

---

RELICENSE/stephan57160.md

Added RELICENSE statement

---

builds/android/build.sh

Solution: Implement the current same kind of mechanism as CZMQ & ZYRE, with enhancement.
Enhancement: When required and if LIBSODIUM is not set, the build tool checks for an already existing clone, close to LIBZMQ. This mechanism is close to what is done by LIBZMQ/CZMQ/ZYRE for their dependencies.
Additionnaly: Do not copy current source tree to any 'cache' folder. Use current folder, but make sure all is cleaned before compilation is launched. This is a lot safer, when building different clones in parrallel...
Enhancement to be reported to CZMQ/ZYRE via ZProject.

Problem: Android CI build tools does not support LIBSODIUM_ROOT

---

builds/android/android_build_helper.sh

Among them, CC, LD, CFLAGS, ... could be useful for other tools.
Reason: Many are calculated as "local" to a particular function, which makes them unavailable outside this helper function.
Solution: Export more variables (CC, LD, CFLAGS, ...).
New exported variables are prefixed with ANDROID_BUILD_xxx. This naming is expected to avoid any conflicts/problem with other tools:
- ANDROID_BUILD_CC
- ANDROID_BUILD_LD
- ANDROID_BUILD_CFLAGS
- ...

Problem: Android helpers should export more compilation chain related variables

---

builds/android/README.md

Solution: Update Android build documentation.

Problem: Android build documentation is outdated.

---

RELICENSE/djolemanojlovic.md
src/stream_engine_base.cpp

Solution: Cancel handshake timer after handhake has been done.

Problem: Handshake timeout error with ZMTP_2_0

---

CMakeLists.txt
RELICENSE/Teebonne.md

sodium, not Sodium

---

.github/workflows/CI.yaml
appveyor.yml
configure.ac
src/atomic_counter.hpp
src/blob.hpp
src/mailbox.hpp
src/proxy.cpp
src/socket_base.cpp
src/ypipe_conflate.hpp
tests/test_hwm_pubsub.cpp
tests/test_pair_vmci.cpp
tests/test_poller.cpp
tests/test_radio_dish.cpp
tests/test_reqrep_vmci.cpp
tests/test_spec_dealer.cpp
tests/test_spec_router.cpp
tests/test_tcp_accept_filter.cpp
tests/testutil_unity.hpp

Problem: various CI issues

---

README.md
RELICENSE/martindelille.md

Since your project is available on the [conan center](https://conan.io/center/zeromq), what about advertizing it on the README.md ?

Add conan badge

---

RELICENSE/casaroli.md
src/blob.hpp
src/err.hpp

Hello,
I am building ZeroMQ with NuttX and this is part of a probably series of minor PRs.
I see a scenario where size is `0`, so we are getting a spurious out of memory error.
BR

Fixes for memory allocation and zero size

---

.readthedocs.yaml

* Link the new CSS stylesheet also when building docs at RTD

Documentation: improve the look of landing page

---

doc/zmq_socket.adoc

Solution: Fix format issue of zmq_socket.adoc
Fixes #4738

Problem: zmq_socket document format error

---

src/vmci_listener.cpp

make vmci_listener compile on windows again

fix(windows) VMCI Listener not compiling
