zeromq/libzmq

doc/zmq_socket.txt
group being defined as a null-terminated `char *` is logically a text type, which needs an encoding.
Declare in the API that groups shall be UTF8-encoded, matching the `zmq_msg_gets` API, which is the other user-facing null-terminated `char *` API, and has the same encoding specification.
This allows bindings in languages that distinguish bytes from text strings to provide text-type APIs to groups, which they cannot do if arbitrary (non-null) bytes are allowed.
=> specify that groups shall be UTF8

builds/coverage/ci_build.sh
Solution: run make check with VERBOSE=1
=> Problem: coverage CI job does not print test errors

tests/test_security_gssapi.cpp
Solution: fix it, and also close messages after copying data
=> Problem: test_security_gssapi expects wrong event

src/curve_client.cpp, src/mechanism_base.cpp, src/mechanism_base.hpp, src/null_mechanism.cpp, src/plain_client.cpp, src/zap_client.cpp, tests/test_security_curve.cpp, tests/test_security_zap.cpp, tests/testutil_security.hpp
Solution: added tests for CURVE, add emitting of client-side event in curve_client_t; add ZAP code 300/500 tests for all mechanisms; suppress sending an error message for ZAP code 300
=> Problem: no tests for client-side events for successful handshake and authentication failure in handshake

tests/CMakeLists.txt, tests/test_monitor.cpp, tests/testutil_security.hpp
Solution: add diagnostic output
This also re-enables test_monitor on Windows builds.
=> Problem: test_monitor fails sometimes due to a wrong event received but unclear which one

src/select.cpp, src/select.hpp
Solution: extract find_fd_entry_by_handle from rm_fd
=> Problem: code duplication within zmq::select_t::rm_fd

src/thread.cpp
Solution: do not assert() the values returned; if we failed to set the thread name - we just have harder debugging, not flawed production conditions.
Closes github issue #2679
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
=> Problem: cosmetic setThreadName() can be fatal

src/mechanism_base.cpp, src/mechanism_base.hpp, src/plain_server.cpp
=> Problem: Inconsistent size_t/int usage. size_t and int don't match in 64 bit build and produce warnings. Solution: types corrected.

builds/cmake/Modules/ZMQSourceRunChecks.cmake
Solution: Escape quotes in cmake test.
=> Problem: ZMQ_HAVE_O_CLOEXEC always disabled

include/zmq.h, src/router.cpp, src/router.hpp, src/socket_base.cpp, src/socket_base.hpp, src/zmq.cpp, src/zmq_draft.h, tests/test_router_mandatory.cpp
Solution: add zmq_socket_get_peer_state function
This addresses #2623 at least partially.
=> Problem: unable to query state of a router for a particular peer

src/session_base.cpp
V728 An excessive check 'options.mechanism == 0' can be simplified.
The '||' operator is surrounded by opposite expressions. session_base.cpp 377
=> Excessive check options.mechanism == ZMQ_NULL

src/proxy.cpp, tests/test_proxy.cpp
```
Problem:
Currently there is no visibility on how many packets / bytes a ZMQ proxy has processed on its frontend/backend socket. The only possible way is using the "capture" socket but that seems overkill to just keep track of packets/bytes passed through the proxy.
A way to retrieve such information would be important, at the very least, for debugging purpose.
Solution:
Attached is the proposed patch to ZMQ master branch to add such feature.
The solution is just to increment counters in the proxy.cpp forward() function and add a new command on the proxy control socket to retrieve them.
```
Fixes https://github.com/zeromq/libzmq/issues/2736
=> Add "STATISTICS" command to zmq_proxy_steerable() 

src/proxy.cpp, tests/test_proxy.cpp
Solution: cast the uint64_t to uint32_t to avoid portability nightmare in the test, and wrap response to STATISTICS zmq_proxy_steerable message in \#ifdef draft
=> Problems: proxy stats test break 32bit build, not declared as draft

src/socket_poller.cpp, src/socket_poller.hpp
Incorporated feedback from discussing in #2742. Refactor even more code to save some lines here and there.
zmq::socket_poller_t::wait() had an important set of common lines
between POLL and SELECT variant.
Solution: refactor zmq::socket_poller_t::wait() and add the
following methods:
zmq::socket_poller_t::zero_trail_events()
zmq::socket_poller_t::check_events()
zmq::socket_poller_t::adjust_timeout()
=> Problem: duplicated socket_poller::wait() code

packaging/redhat/zeromq.spec
Solution: use same autoconf workaround as for Debian 7, and manually
create the config directory
=> Problem: CentOS 6 build fails

src/curve_server.cpp, src/curve_server.hpp, src/mechanism_base.cpp, src/mechanism_base.hpp, src/null_mechanism.cpp, src/null_mechanism.hpp, src/plain_server.cpp, src/session_base.cpp, src/zap_client.cpp, tests/test_security_plain.cpp, tests/test_security_zap.cpp, tests/testutil_security.hpp
Solution: added tests & aligned behaviour
Fixes #2711
=> Problem: missing tests and inconsistent behaviour for ZAP corner cases

doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt
Solution: fix documentation
Follow-up to #2752
=> Problem: documentation of ZMQ_ZAP_DOMAIN is wrong

.gitignore, Makefile.am, src/command.hpp, src/object.cpp, src/object.hpp, src/session_base.cpp, src/socket_base.cpp, src/socket_base.hpp, tests/CMakeLists.txt, tests/test_reconnect_ivl.cpp
Solution: when a connection breaks and ZMQ_RECONNECT_IVL is set to -1,
which means a reconnection will not be attempted, send a message from
the I/O thread to the application thread to make the socket call
term_endpoint, which is the equivalent of manually calling
zmq_disconnect.
This way subsequent zmq_connect call to the same endpoint will attempt
again to do a connection.
Otherwise, for some socket types like SUBs, those new connects will
fail as the endpoint is recorded, despite the connection having been
permanently closed.
Add test cases to exercise this corner case with TCP and IPC.
=> Problem: zmq_connect fails after disconnect due to RECONNECT_IVL == -1

src/stream_engine.cpp, src/thread.cpp
On FreeBSD the sysmbol __FreeBSD_kernel__ is only defines if a
specific param.h file is included, unlike Debian/kFreeBSD where this
symbol is always defined.  So also compile the FreeBSD specific code
if __FreeBSD__ is defined for FreeBSD 11 & 12 compatibility.
Signed-off-by: Christopher Hall <hsw@ms2.hinet.net>
```
```
git rebase …
=> add __FreeBSD__ to ifdefs

builds/msvc/build/buildbase.bat, builds/msvc/vs2017/libzmq.sln
The build configuration for MSVC 2017 is corrected:
1. Visual Studio version fixed in .sln file
2. Workaround of changing directory / drive letter by vcvarsall.bat added to buildbase.bat
=> fix build for msvc2017

.gitignore, Makefile.am, builds/gyp/project-tests.gypi, builds/gyp/project-tests.xml, src/ipc_listener.cpp, tests/CMakeLists.txt, tests/test_rebind_ipc.cpp
Solution: Don't unlink file on close
File may not belong to the socket at that point.
Refs #2764
=> Problem: Race condition in IPC sockets

doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, src/curve_server.cpp, src/options.cpp, src/options.hpp, src/plain_server.cpp, src/socket_base.cpp, src/zmq_draft.h, tests/test_security_zap.cpp, tests/testutil_security.hpp
Solutions: fix the warnings, and add ZMQ_ZAP_ENFORCE_DOMAIN to hide backward incompatible
change and make it disabled by default.
In a future release that breaks API compatibility we can then switch the default to enabled in order to achieve full RFC compatibility.
Fixes #2762
=> Problems: strict ZAP protocol adherence is backward incompatible, minor static analysis warnings

CMakeLists.txt, builds/cmake/Modules/ZMQSourceRunChecks.cmake, configure.ac, include/zmq.h, src/ctx.cpp, src/ctx.hpp, src/thread.cpp, src/thread.hpp, src/zmq_draft.h, tests/test_ctx_options.cpp
Problem: 
- right now there's no way to set background thread CPU affinity
- right now it's impossible to set the NICE value of background threads when using SCHED_OTHER Linux default scheduling
Solution: 
- add option ZMQ_THREAD_AFFINITY to allow setting CPU affinity
- add special casing for SCHED_OTHER that triggers a call to the nice() syscall, to allow setting the NICE of background threads.
=> Background threads enhancements

doc/zmq_proxy_steerable.txt, include/zmq.h, src/ctx.cpp, src/ctx.hpp, src/zmq_draft.h, tests/test_ctx_options.cpp
Problem: zeromq background thread names cannot be customized. It is difficult to understand which background thread is associated to which process.
Solution: allow the user to set a custom thread name prefix. Currently because of zmq_ctx_set() limitation it is just a number
=> Background thread names

configure.ac
As discussed on IRC, added iphlpapi to PKGCFG_LIBS_PRIVATE for static mingw builds, which implements `if_indextoname` and `GetAdapterAddresses`.
=> added libiphlpapi to PKGCFG_LIBS_PRIVATE for static mingw builds

INSTALL
added note urging users to add `-DZMQ_STATIC` to their compiler flags when building using a static libzmq in windows / mingw.
This is a temporary workaround until pkg-config supports cflags.private, see issue:
https://github.com/zeromq/libzmq/issues/2788
=> added note concerning issue 2788 to INSTALL

doc/zmq_ctx_set.txt, doc/zmq_proxy_steerable.txt, tests/test_router_mandatory.cpp, tests/test_timers.cpp
=> Problems: DRAFT build broken in CentOS 6, missing bits in documentation

src/options.hpp
=> Problem: comment before sndtimeo/rcvtimeo does not specify dimension

doc/zmq_atomic_counter_value.txt
Solution: provide correct description
Fixes #2789
=> Problem: description of return value is cloned from zmq_atomic_counter_new

doc/zmq_ctx_set.txt, include/zmq.h, src/ctx.cpp, src/ctx.hpp, src/thread.cpp, src/thread.hpp, src/zmq_draft.h, tests/test_ctx_options.cpp
Change ZMQ_THREAD_AFFINITY to ZMQ_THREAD_AFFINITY_CPU_ADD/ZMQ_THREAD_AFFINITY_CPU_REMOVE. 
Avoid prefix thread names when no prefix was set.
=> Change ZMQ_THREAD_AFFINITY to ZMQ_THREAD_AFFINITY_CPU_ADD/REMOVE

src/select.cpp
iteration even if not used
Solution: Move wsa_events closer to usage
=> Problem: wsa_events are initialized/destroyed within every loop

src/socket_poller.cpp
Cannot reproduce/test this in libzmq. But i ran czmq/zloop self-test: https://github.com/zeromq/czmq/blob/ed902413453c0e50c65f887c40a5e9052619a224/src/zloop.c#L1  
If i print the "Value of zmq_error(): " here: 
https://github.com/zeromq/libzmq/blob/812e756264cc92d735dc56d91eaf8db2843f77ce/src/zmq.cpp#L783 i get:
```
Running czmq test 'zloop'...
* zloop: D: 17-11-01 15:24:18 zloop: register timer id=1 delay=1000 times=1
D: 17-11-01 15:24:18 zloop: register timer id=2 delay=5 times=1
D: 17-11-01 15:24:18 zloop: register timer id=3 delay=20 times=1
D: 17-11-01 15:24:18 zloop: register PAIR reader
D: 17-11-01 15:24:18 zloop polling for 5 msec
Value of zmq_errno(): 35
D: 17-11-01 15:24:18 zloop: call timer handler id=2
D: 17-11-01 15:24:18 zloop: cancel timer id=1
D: 17-11-01 15:24:18 zloop …
```
=> Problem: Sometimes on OSX we get ETIMEDOUT instead of EAGAIN

src/req.cpp, tests/test_req_relaxed.cpp
Solution: Check for strictness before returning false if no reply has been received.
Fixes #2824.
=> Problem: REQ socket with ZMQ_REQ_RELAXED does not report ZMQ_POLLOUT when queried for events after first message.

configure.ac
* link against libnetwork.so for network functions.
This is similar with what is done for the Solaris case.
=> add Haiku support

packaging/debian/rules, tests/testutil_security.hpp
Solutions: let test failures fail Debian build, and set linger at the beginning of the test rather than the end.
As the commit message says this is a bandaid rather than a fix. There's an obvious race condition that needs a deeper fix, but at least stop the constant test failures for now.
Fixes #2733
=> Problems: test_security_{zap|curve} often hangs, debian builds ignore test failures hiding issues

src/precompiled.hpp, src/stdint.hpp, src/vmci.hpp, src/zmq_utils.cpp
```
Problem: Build fails on Visual Studio 2008 without `stdint.h`
Solution: Cleaning include files which include `stdint.h` except `stdint.hpp`.
Define UINT32_MAX in `stdint.hpp`.
```
git push -f
[CONTRIBUTING](http://zeromq.org/docs:contributing)
=> Problem: Build fails in Visual Studio 2008 without `stdint.h`

doc/zmq_setsockopt.txt
Problem: Wrong linger default value
Solution: correct documentation
Fixes #2845
=> Wrong ZMQ_LINGER default value

appveyor.yml
Solution: add it to Appveyor
Covers what the retired cloudapp jenkins job was testing with VS2013
@ricnewton FYI seems to work
=> Problem: no coverage for VS2013 and VS2017

packaging/debian/rules, packaging/obs/_service
Solution: install it if available. Download it from its repo as part
of the OBS source run.
Debian and Ubuntu always ship zmq.hpp in libzmq-dev, so do the same.
In the RPM world it is in its own separate package, so don't do the
same for RPM.
=> Problem: Debian packages are missing zmq.hpp

CMakeLists.txt
Solution: set it to CMake instead of a subfolder of share.
See [cmake find_package documentation](https://cmake.org/cmake/help/v3.5/command/find_package.html) for further info.
View the commit diff without whitespace to see that the non-WIN32 settings haven't changed:
* https://github.com/zeromq/libzmq/commit/de5e7a39834500b924e156488aa63a5dbf874998?w=1
=> Problem: WIN32 CMAKECONFIG_INSTALL_DIR is broken

Jenkinsfile
Solution: tune the recipe so it passes... renamed test dir (unstash in another agent) complicates things for libtool...
=> Problem: Jenkinsfile does not pass distcheck etc.

CMakeLists.txt
Solution: revert the objects optimisation, and go back to building
everything twice on Windows, as the static builds needs different
preprocessor definitions from the shared one, so the objects have to be
rebuilt.
Keep the optimisation for all the other platforms.
Fixes #2858
=> Problem: static build broken on Win + CMake

CMakeLists.txt
Problem: If libzmq is used as static library on windows all using projects need to define "ZMQ_STATIC".
In case libzmq is part of a larger project, this patch automatically exports the needed flag using cmake functionality.
Solution: export flag using target_compile_definitions
```
=> export ZMQ_STATIC compile flag to depending projects (MSVC)

Jenkinsfile
Solution: avoid using random infrastructure and default agents by requiring a reasonable label (like in GSL and zproject)
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
=> Problem: Jenkinsfile uses "any" agent

packaging/nuget/package.gsl
Solution: re-point to the maintained zeromq fork
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
=> Problem: nuget packaging refers to imatix gsl

src/precompiled.hpp
Solution: re-instate block for OpenBSD erroneously removed in 9622a830
=> Problem: Build is broken on OpenBSD

packaging/nuget/package.config, packaging/nuget/package.nuspec, packaging/nuget/package.targets
Solution: Change the package name,  reset version sequence and regenerate.
This also makes the naming system consistent with boost packages. Old packages will be retained.
=> Problem: NuGet package versioning out of sync with releases.

src/socket_base.cpp
(see https://github.com/zeromq/libzmq/issues/788)
The original fix for the duplicate connect issue only covered SUB connecting to PUB, but the same problem exists in the other direction.  (Irrespective of any other issues related to PUB connecting to SUB).
Note to Luca -- let me know if you need/want a test pgm for this, or if this behavior should be documented somewhere (e.g.in zmq_connect.txt?)
=> prevent duplicate connections from PUB sockets also 

CMakeLists.txt, include/zmq.h
CMake tests for some symbols (WSAStartup, UuidCreateSequential, GetAdaptersAddresses) were checked in the wrong way.
Added automatic dependies pull-in for windows/msvc.
=> Fix CMake tests on Windows

CMakeLists.txt
The full path to librt.so is hard-coded in the generated file ZeroMQTargets.cmake. While this is not problematic when installing from source, this may prevent to link with ZeroMQ if the package has been built on another machine with a different folder / system structure.
This behavior is the result of linking with the result of the `find_library` instruction, which returns a full path.
=> removing hard-coded path of librt

src/poll.cpp
Solution: add assertion
This is related to #2895, but it does not fix it. Rather, it attempts to simplify identifying the cause of the problem.
=> Problem: add_fd might be called with fd_ == retired_fd

src/ctx.cpp, src/ctx.hpp, src/io_thread.cpp, src/mailbox.cpp, src/mailbox.hpp, src/reaper.cpp, src/select.cpp, src/select.hpp, src/signaler.cpp, src/signaler.hpp, src/socket_poller.cpp, src/zmq.cpp
Solution: signal error to caller, and apply appropriate cleanup
Fixes #2895 (I hope)
=> Problem: in case of exhausted resources on creation of a context, assertions are triggered

src/dish.cpp
Solves issue #2907 by checking whether the msg already has a group
=> Problem:  ZMQ_DISH triggers assert when hitting the watermark(?)

include/zmq.h
Problem: #2919 Windows Intel compiler build error by include zmq.h 
Solution: 
Modified ifdef condition order of typedef struct zmq_msg_t alignement.
Placed if defined(_MSC_VER) before the other compiler.
=> Problem: Windows Intel compiler build broken

include/zmq.h
Reverts zeromq/libzmq#2920
Temporarily revert so that #2908 can go in unchanged. Will be reapplied afterwards.
=> Revert "Problem: Windows Intel compiler build broken"

include/zmq.h
Reapply #2920 after formatting was updated.
=> fix Windows Intel compiler build failure

src/socket_base.cpp, src/socket_base.hpp, src/socket_poller.cpp
Solution: replaced by assertion
Note: this requires #2908 to be merged first.
=>  Problem: unreachable code around socket_base_t::add/remove_signaler

src/socket_poller.cpp
Solution: remove code duplication and rearrange conditions
Note: this requires #2908 to be merged first.
=> Problem: code duplication and unnecessary nesting around ZMQ_THREAD_SAFE querying

src/tcp_connecter.cpp, src/tcp_connecter.hpp, src/tcp_listener.cpp
Solution: remove duplication and redundant member, align handling of
handle in tcp_connecter and tcp_listener
This PR requires #2908 to be merged first.
=> Problem: duplicated code, redundant member handle_valid, asymmetry between tcp_connecter and tcp_listener

src/atomic_counter.hpp
Solution: change conditional compilation to recognize _MSC_VER
=> Problem: std::atomic not used on Visual C++ although it is available

include/zmq.h, src/poller_base.cpp, src/poller_base.hpp, src/select.cpp, src/select.hpp, src/zmq_draft.h, src/zmq_utils.cpp, tests/test_timeo.cpp, tests/test_timers.cpp
Solution: wait until all fds have been unregistered before exiting select_t::loop
Fixes #2925 
This PR requires #2908 to be merged first.
=> Problem: assertion failure in poller_base.cpp:42

tests/test_timers.cpp
Solution: change variable type in test_timers to match public API
=> Problem: DRAFT build broken with GCC 4.7

.travis.yml, ci_build.sh, src/io_thread.cpp, src/select.cpp, src/select.hpp
@sigiesec using select does not work anymore since recent changes, it works fine with 4.2.2 though.
There is still one weird linking problem left:
```
CXXLD    tools/curve_keygen
src/.libs/libzmq.so: undefined reference to `zmq::select_t::family_entry_t::family_entry_t()'
collect2: error: ld returned 1 exit status
```
I think it's cause by this line: https://github.com/zeromq/libzmq/blob/master/src/select.hpp#L118
Is that perhaps a Windows compiler specific thing?
EDIT: I think the constructor was missing the body and GCC is not happy about that - tests still fail though
=> Problem: regression with "select" on *nix

src/tcp.cpp
Problem: build is broken on Windows when SIO_LOOPBACK_FAST_PATH is not defined (i.e. in VS2010, even on Windows 10, even with Windows 10 SDK installed, as VS2010 won't detect/use it)
Solution: add one more condition to #if.
=> Fix build break when SIO_LOOPBACK_FAST_PATH is not defined (i.e. in VS2010)

src/tipc_address.cpp, src/tipc_address.hpp, src/tipc_connecter.cpp, src/tipc_listener.cpp
Solution: 
ZeroMQ currently supports location independent addressing using TIPC Port Names with tipc://{type,instance}. This commits adds support for connecting and binding using TIPC Port Identity addresses. To connect using Port Identities the expected format is tipc://<Z.C.N:Ref>, e.g. "tipc://<1.2.3:123123>". To bind using TIPC Port Identities the expected format is "tipc://<*>".
=> Problem: No support for addressing using TIPC Port Identity

src/msg.cpp
Hi,
I have a small build error/warning when building with gcc 8 and -O3 in CFLAGS/CXXFLAGS:
```
In member function ‘zmq::msg_t::set_group(char const*, unsigned long)’,
inlined from ‘zmq::msg_t::set_group(char const*)’ at src/msg.cpp:549:22:
src/msg.cpp:560:13: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
strncpy (u.base.group, group_, length_);
~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/msg.cpp: In member function ‘zmq::msg_t::set_group(char const*)’:
src/msg.cpp:549:22: note: length computed here
return set_group (group_, strlen (group_));
~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```
Here we don't actually need to call `strlen(group_)`, since `strncpy` will already stop at the end of the string, and …
=> Fix gcc 8 build warning/error with -O3.

unittests/unittest_mtrie.cpp
Solution: correctly dereference pointer in test.
@sigiesec - just a small error that was not visible on 64bit (I guess the pointer there evaluates as greater than 0, but on 32bit it's negative)
=> Problem: unittest_mtrie fails on 32bit *nix

doc/zmq_ctx_get.txt, doc/zmq_ctx_set.txt, include/zmq.h, src/ctx.cpp, src/ctx.hpp, src/norm_engine.cpp, src/norm_engine.hpp, src/options.cpp, src/options.hpp, src/socket_base.cpp, src/stream_engine.cpp, src/v2_decoder.cpp, src/v2_decoder.hpp, src/zmq_draft.h, tests/test_ctx_options.cpp, tests/testutil.hpp
The zero copy decoding strategy implemented for 4.2.0 can lead to a large
increase of main memory usage in some cases (I have seen one program go up to
40G from 10G after upgrading from 4.1.4). This commit adds a new option to
contexts, called ZMQ_ZERO_COPY_RECV, which allows one to switch to the old
decoding strategy.
=> Problem: enormous memory increase due to zero copy decoding

src/random.cpp
Solution: use local statics when available in a thread-safe implementation
Fixes #2915 (at least on platforms with gcc >=4.3.0 and MSVC>=2015)
=> Problem: static initialization order fiasco

src/options.cpp
Solution: initialise variable in options.cpp to dummy value to fix
compiler complaint:
src/options.cpp: In function
'int zmq::do_setsockopt_int_as_bool_strict(const void*, size_t, bool*)':
src/options.cpp:121:5: error: 'value' may be used uninitialized in
this function [-Werror=maybe-uninitialized]
src/options.cpp: In function
'int zmq::do_setsockopt_int_as_bool_relaxed(const void*, size_t, bool*)':
src/options.cpp:135:31: error: 'value' may be used uninitialized in
this function [-Werror=maybe-uninitialized]
=> Problem: build broken with gcc-4.7

src/random.cpp
Solution: do not rely __cplusplus >= 201103L to detect whether the
compiler supports thread safe static initialisation, but check only
the proper feature preprocessor macro.
GCC introduced it in version 8, and Clang in version 6.
=> Problem: mis-detection of threadsafe_static_init causes test failures

src/random.cpp
Reverts zeromq/libzmq#2974
#2974 was based on wrong assumptions. The problem in czmq/malamute was unrelated to thread-safety; and while gcc/clang support the feature *macro* __cpp_threadsafe_static_init only in recent versions, they support the actual feature for a long time (gcc since at least 4.3.0). Probably, the condition could be even more relaxed based on the gcc version number.
=> Revert "Problem: mis-detection of threadsafe_static_init causes test failures"

Makefile.am, src/socket_base.cpp, src/tipc_address.cpp, src/tipc_listener.cpp, tests/CMakeLists.txt, tests/test_address_tipc.cpp
Solution: 
Add tests for binding/connecting with different TIPC address types, and error checks misused addresses.
=> Problem: Tests for different TIPC address types missing

.travis.yml, builds/cmake/Modules/ZMQSourceRunChecks.cmake, ci_build.sh, configure.ac, tests/CMakeLists.txt, tests/test_address_tipc.cpp, tests/test_connect_delay_tipc.cpp, tests/test_pair_tipc.cpp, tests/test_reqrep_device_tipc.cpp, tests/test_reqrep_tipc.cpp, tests/test_router_mandatory_tipc.cpp, tests/test_shutdown_stress_tipc.cpp, tests/test_sub_forward_tipc.cpp, tests/test_term_endpoint_tipc.cpp, tests/testutil.hpp
Solution: at build time only check if the API is available. In the tests
do a first check and a skip if the functionality is not available.
TIPC needs an in-tree but not loaded by default kernel module, tipc.ko
to be loaded, which requires root, so it is unlikely to be available on
any build system by default.
This will allow most distributions to ship with TIPC support built in,
and to avoid tests failure if the module is not there.
Also add a CI job on Travis and have CMake mark tests as skipped if they return 77 (like autotools does).
@eponsko what do you think?
=> Problem: TIPC availability check is too strict

src/mtrie.hpp
```
Problem: VS2010 build is broken
Solution: Update macro guarding ZMQ_HAS_EXTERN_TEMPLATE to set it to 0 under VS2010
```
=> Fixed issue #2979

src/socks_connecter.cpp, src/stream_engine.cpp, src/tcp_connecter.cpp, src/tcp_listener.cpp
Problem: issues found during static code analysis.
This PR addresses 8 similar issues where method's 2nd argument is of zmq:fd_t type, and value passed is of the same type, but for some reason is cast to int, causing static analysis to tag it as suspicious cast for 64bit mode. 
Solution: remove cast
=> Partial fix for issue 2963

doc/zmq_msg_gets.txt, doc/zmq_setsockopt.txt
Documentation for ZMQ_METADATA socket option added to zmq_setsockopt and zmq_msg_gets.
=> Problem: Documentation missing for ZMQ_METADATA socket option

tests/CMakeLists.txt
Problem: VS2010 build is broken due to lack of VS2010's C99+ support require by bundled Unity
Solution: force VS2010 to compile Unity as C++
=> Fix for #2997

src/random.cpp
Solution: restrict it only to the original issue #2632, Tweetnacl on
*NIX when using /dev/urandom, ie: without the new Linux getrandom()
syscall.
Existing applications might use atexit to register cleanup functions
(like CZMQ does), and the current change as-is imposes an ordering
that did not exist before - the context MUST be created BEFORE
registering the cleanup with atexit. This is a backward incompatible
change that is reported to cause aborts in some applications.
Although libsodium's documentation says that its initialisation APIs
is not thread-safe, nobody has ever reported an issue with it, so
avoiding the global init/deinit in the libsodium case is the less
risky option we have.
Tweetnacl users on Windows and on Linux with getrandom (glibc 2.25 and
Linux kernel 3.17) are not …
=> Problem:  global random init/deinit breaks existing applications

NEWS, configure.ac, doc/zmq_ctx_get.txt, doc/zmq_ctx_set.txt, include/zmq.h, packaging/debian/changelog, packaging/debian/zeromq.dsc.obs, packaging/redhat/zeromq.spec, src/zmq_draft.h, tests/test_security_gssapi.cpp
Solution: mark them as stable and bump API versions (ABI stays the same as it's just preprocessor defines changes for now)
=> Problems: some APIs have met stable conditions

CMakeLists.txt
Fixed gcc-related build problem resulting from `-errwarn=%all` switch.
Fixes #3012.
=> Fix gcc build problem

doc/zmq_close.txt, doc/zmq_connect.txt, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt
=> Problem: some inaccuracies in manpages

src/null_mechanism.cpp, tests/test_security_null.cpp, tests/test_security_zap.cpp, tests/testutil_security.hpp
Solution: fix it like for other mechanism, add test
=> Problem: backward incompatible change to NULL with ZAP

NEWS, configure.ac, doc/zmq_ctx_get.txt, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, packaging/debian/changelog, packaging/debian/zeromq.dsc.obs, packaging/redhat/zeromq.spec, src/zmq_draft.h, tests/test_security_gssapi.cpp
Solution: temporarily revert API changes, restore next version to 4.2.5 and compile changelog
After tagging 4.2.5 I'll restore the API changes and 4.3
=> Problem: regression in 4.2.3 needs to be fixed before 4.3

CMakeLists.txt, NEWS, configure.ac, doc/zmq_ctx_get.txt, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, packaging/debian/changelog, packaging/debian/zeromq.dsc.obs, packaging/redhat/zeromq.spec, src/zmq_draft.h, tests/test_security_gssapi.cpp
Solution: revert the revert!
Revert "Problem: regression in 4.2.3 went unnoticed, want to release 4.2.5"
This reverts commit 5f17e26fa4c60c3de0282d1b6ad1e8b7037ed57a.
=> Problem: 4.2.5 is out, we need to restore API changes and 4.3.x

Makefile.am, builds/Makefile.am, ci_build.sh
Solution: Always run test builds from the result of `make dist`.
Ensures that tests will not pass if needed files are omitted from releases
closes #3023 by adding files required for cmake builds
I'm not sure exactly what files are needed to be added to fix these issues, but cmake tests shouldn't be passing if zeromq releases can't be installed with cmake, which is the current state of things.
=> Problem: `make dist` results are not tested

src/socket_base.cpp, src/socket_base.hpp, src/socket_poller.cpp, tests/test_ctx_destroy.cpp
=> Fix assertion failure when calling zmq_poller_destroy after zmq_ctx_term

src/tweetnacl.h
Solution: change missing comments in header file
Fixes: #3036 and adds on top of '15905c5'
Missing src/tweetnacl.h  on top of #3036
=> Problem: C++ style comments in header file breaks pedantic build

CMakeLists.txt
Problem: When CMake Visual Studio generators are used, the install rule for the linker PDB does not work.
Solution: Fixed install rules to work with single and multi-configuration generators under MSVC.
I previously opened the pull request #2988 to fix this problem. The solution back then included an update of the CMake version to 3.x which was not an option. Hence, I adapted the solution to work with CMake 2.8.12. Please note that the fix changes both the PDB of the shared library and of the static library. In the static case, I added /Z7 to add the compile info to the static lib directly. The reason for this was, that there are no CMake variables in 2.8.x that allow for a smooth installation of the PDB of the static lib.
This solves #2989
=> CMake: Linker PDB install rule does not work when Visual Studio generators are used

configure.ac
The original configure.ac tries to check for dladdr, but it actually needs
it only in case we have libunwind (which has a another section and checks for it
too).
This can fail the build on systems without dynamic linking support.
Therefore, the dladdr check has to be preformed only when checking libunwind.
Signed-off-by: Asaf Kahlon <asafka7@gmail.com>
=> configure.ac: serach for dladdr only on libunwind

src/tcp_listener.cpp
event_accepted() already accepts fd_t type and there is no reason to cast it to int type
Moreover, on Windows x64 this leads to truncation memsize -> int
=> Fix fd_t variable casting on Windows platform

CMakeLists.txt
**Problem**: When building libzmq with CMake, the installed `libzmq.dylib` has a relative install name (`otool -D libzmq.dylib`) on MacOS. This is a regression against building via autotools which sets an absolute install name. Effectively, the CMake-built `libzmq.dylib` is rendered useless if installed in non-system directories and used in environments without explicit `DYLD_LIBRARY_PATH` mgmt. For example running any of the installed executables currently fails:
``` 
$ /some_install_prefix/bin/inproc_lat
dyld: Library not loaded: libzmq.5.dylib
Referenced from: /some_install_prefix/bin/inproc_lat
Reason: image not found
Trace/BPT trap: 5
```
**Solution**: Best practice is to install relocatable dylibs. On MacOS this means setting an install name with a special prefix, e.g. …
=> Install relocatable dylibs (MacOS)

.github/PULL_REQUEST_TEMPLATE.md
Avoids the git instructions being all on one line.
=> Fix formatting in CONTRIBUTING

doc/zmq_setsockopt.txt, src/req.cpp, tests/CMakeLists.txt, tests/test_heartbeats.cpp
Solution: ignore commands in the REP session manager, as they are handled by the engine, and clarify default values in the documentation. Also add more test coverage for heartbeats.
Fixes: #3060
=> Problem: heartbeat commands break REP session, unclear documentation

CMakeLists.txt, Makefile.am, src/ip_resolver.cpp, src/ip_resolver.hpp, src/tcp_address.cpp, src/tcp_address.hpp, tests/testutil.hpp, unittests/CMakeLists.txt, unittests/unittest_ip_resolver.cpp
Solution: Factor the code into a different file with a well defined API and add
unit tests.
My Debian doesn't have a recent-enough `clang-format` to run `make clang-format-check` so apologies in advance if I messed up the coding style here and there (which is almost certain given the size of the patch).
I've attempted to match the previous implementation perfectly, including the arguable "quirks" such as the ones I've reported in #3069 (and a few others that I'm not sure about, such as specifying a %scope for an IPv4 address).
This is a pretty huge patch so I tried to be very comprehensive in the unit tests. I think the only path of the code that's not tested is when specifying an interface name as a bind point since the implementations to find the IP address associated with a network …
=> Problem: address parsing code is tied to the TCP code

src/ip_resolver.cpp, unittests/unittest_ip_resolver.cpp
Solution: return an error in this situation but still allow using an explicit
"0" if somebody really wants to connect to port 0.
This shouldn't break any existing code because a `*` port was already rejected
in an early test in the TCP path in `zmq::socket_base_t::connect`.
=> Problem: ip_resolver allows wildcard ports for non-bindable sockets

Makefile.am, src/udp_address.cpp, unittests/CMakeLists.txt, unittests/unittest_udp_address.cpp
This code contains two independent albeit related commits:
* The first adds unit tests for the `udp_address` code
* The 2nd replaces the current ad hoc parser with the new `ip_resolver` code
Let me know if you prefer to have two different PRs.
The new resolver code should not break any existing URLs, however it will allow things that didn't work previously such as connecting hostnames (`udp://zeromq.org:5555`), binding NIC names (`udp://eth0:1234`) and wildcard ports (`udp://127.0.0.1:*`).
=> Udp parser

acinclude.m4
On some cases, -latomic is needed for likning, and since the current
acinclude.m4 checks only compilation we can sometimes miss the need for -latomic
and the linking process will fail.
Therefore, the AC_CHECK_IFELSE was replaced with AC_LINK_IFELSE. If the first
try fails, we try to link again with -latomic and add LIBS="-latmoic" in case we
succeeded.
Signed-off-by: Asaf Kahlon <asafka7@gmail.com>
=> acinclude.m4: check if -latomic is needed.

builds/msvc/vs2015/libzmq/libzmq.vcxproj
Fixes #3079 for VS2015 Solution
Problem: VS2015 solution does not include ip_resolver.cpp and ip_resolver.hpp
Solution: added .cpp and .hpp to vcxproj
=> Add ip_resolver.cpp and ip_resolver.hpp for vs2015 libzmq project

tests/testutil_unity.hpp
I started looking into that because I wanted to silence a distracting warning. I don't know if the flags were ignored on purpose but I can't really imagine why that would be. At any rate the only code that actually passes non-0 flags is test_get_peer_state in test_router_mandatory.cpp:
https://github.com/zeromq/libzmq/blob/3c2656eb5233fea480a6ead357159d2ec85412e3/tests/test_router_mandatory.cpp#L138
=> Problem: test helper recv_string_expect_success ignores flags

doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, doc/zmq_udp.txt, include/zmq.h, src/options.cpp, src/options.hpp, src/udp_engine.cpp, src/zmq_draft.h, tests/test_radio_dish.cpp
I attempted to add multicast tests as well. I added a method `is_multicast_available` that attempts to send and receive a multicast datagram, if it fails the ZMQ multicast tests are not run.
=> Problem: ZMQ doesn't expose the MULTICAST_LOOP socket option

acinclude.m4, builds/cmake/Modules/ZMQSourceRunChecks.cmake
Solution: check return value in autoconf and CMake. On some platforms
the function is available but not implemented (eg: GNU/Hurd).
=> Problem: getrandom test does not check if it's working

src/ip_resolver.cpp, src/ip_resolver.hpp, src/mechanism.cpp
=> Problem: warnings in MSVC builds around size_t/int

Makefile.am, src/stream_engine.cpp, src/stream_engine.hpp, tests/test_heartbeats.cpp, tests/testutil_unity.hpp
Solution: if a PING message contains a context, echo it back in the
PONG message. In order to do so, create the PONG message when PING
is received and store it in the engine.
After the PING the engine goes straight to encoding and sending, so
there can always be at most one pending PING.
Add tests for various contexts.
Fixes #3061
=> ZMTP 3.1 PING Context not implemented

src/fd.hpp, src/zmq.cpp, tests/test_poller.cpp
Solution: check and return an error on invalid arguments. Fixes #3088
=> Problem: zmq_poller_[add/modify] accept invalid events arguments silently

src/atomic_ptr.hpp
Compilation fails with ZMQ_ATOMIC_PTR_MUTEX defined. Fixes issue #3042.
=> Fixed compilation with ZMQ_ATOMIC_PTR_MUTEX

src/ip.cpp, src/tcp.cpp, src/tcp_connecter.cpp, src/udp_engine.cpp
Problem: Aborts when iOS returns EBADF to indicate a socket was reclaimed while the app slept.
Solution: When compiling for iOS, remove asserts on EBADF.
EBADF behavior documented here: https://developer.apple.com/library/content/technotes/tn2277/_index.html#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION3
=> Allow EBADF on iOS #3046

.clang-tidy, .travis.yml, CMakeLists.txt, appveyor.yml, builds/cmake/ci_build.sh
I have added static analysis builds experimentally:
- Under Linux on travis-ci
-- clang-tidy/clang-static-analyzer (currently 6.0, but should be easy to update to 7.0)
-- sonar-scanner
- Under Windows on appveyor
-- Visual Studio 2017 Static Analyzer
-- Visual Studio 2017 C++ Core Guidelines Check
I would like to get some feedback on this? Does it make sense? I think it could be a good idea to run these as scheduled builds, e.g. on a weekly basis.
The sonar-scanner results are published to sonarcloud.io (https://sonarcloud.io/dashboard?id=libzmq-clang, but I am not sure if this is publicly accessible, if not and you have/create an account on sonarcloud.io, I can give you access).
The other results are currently only visible in the build log, e.g. here:
* …
=> Add static analysis

doc/zmq_setsockopt.txt, src/options.cpp, src/stdint.hpp, tests/test_heartbeats.cpp
Fixes https://sonarcloud.io/project/issues?id=zeromq-libzmq&issues=AWOS_NBc_Tl7jhO8m4MM&open=AWOS_NBc_Tl7jhO8m4MM en passant
Fixes #3136
=> Fix ZMQ_HEARTBEAT_TTL maximum value check

src/polling_util.hpp
Problem: optimized_fd_set_t computes required bytes wrongly
Solution: fix it
- vector type change from char to SOCKET
- take into account alignment padding bytes in struct fd_set
=> fix computation of winsock fd_set size

Makefile.am, src/epoll.cpp
- ensure all files in external/wepoll get bundled up in dist
- EPOLL_CLOEXEC inadvertently disabled in d326434b371b94c4a98f66df69566f5a28070fcd
=> wepoll integration fixes

unittests/CMakeLists.txt
Problem: 
use the `builds/cmake/ci_build.sh` build the project, and An error occurred.
can't found the unity.h
Solution: 
add the include path
=> use cmake compile the unittest

src/epoll.cpp, src/epoll.hpp
Solution: remove the mutex
Note: the mutex is unnecessary as all uses must come from the same thread anyway, and this is already checked by check_thread
=> Problem: epoll_t employs an unnecessary mutex

src/ipc_connecter.cpp, src/socks_connecter.cpp, src/tcp_connecter.cpp, src/tipc_connecter.cpp, src/vmci_connecter.cpp
Solution: Add guards to prevent a reconnect timer from starting if ZMQ_RECONNECT_IVL is -1
(Issue 3158)
=> Problem: connecter classes do not handle ZMQ_RECONNECT_IVL of -1

doc/zmq_socket.txt
Problem: ZMQ_PAIR not suitable all transports
Solution: Add documentation to discourage using ZMQ_PAIR for reconnecting transports
=> update pair doc

builds/cmake/platform.hpp.in
The define macro to detect whether or not an android compiler is being used is outdated and breaks on certain setups with certain API levels. 
This changes it to use the officially supported preprocessor macro.
=> Switched android platform check to official form

CMakeLists.txt
With autotools, the pkgconfig file goes into the correct lib/lib64
directory, but it always goes in lib with cmake. This fixes cmake to be
consistent with autotools.
=> cmake: Install pkgconfig in correct lib directory.

CMakeLists.txt
Solution: avoid exporting targets and installing files if neither BUILD_SHARED nor BUILD_STATIC is set
=> Problem: build system does not play nicely as a cmake subproject

doc/Makefile.am, doc/zmq_timers.txt, include/zmq.h, src/zmq_draft.h
Solutions: add a manpage, and mark the API as stable.
@somdoron are you OK with making this API stable? It has been there forever and hardly changed
Fixes #3005
=> Problems: no docs for zmq_timers_*, zmq_timers_* have been DRAFT for a long time

src/i_engine.hpp, src/norm_engine.cpp, src/norm_engine.hpp, src/pgm_receiver.cpp, src/pgm_receiver.hpp, src/pgm_sender.cpp, src/pgm_sender.hpp, src/stream_engine.cpp, src/stream_engine.hpp, src/udp_engine.cpp, src/udp_engine.hpp
Solution: prevent access to data if the object was deleted
Fixes issue detected by clang static analyzer-: https://travis-ci.org/zeromq/libzmq/jobs/411364097#L2126
=> Problem: stream_engine_t instance may access its fields after it deleted itself

src/client.cpp, src/client.hpp, src/dealer.cpp, src/dealer.hpp, src/dgram.cpp, src/dgram.hpp, src/dish.cpp, src/dish.hpp, src/fq.cpp, src/fq.hpp, src/gather.cpp, src/gather.hpp, src/pair.cpp, src/pair.hpp, src/pipe.cpp, src/pipe.hpp, src/pull.cpp, src/pull.hpp, src/router.cpp, src/router.hpp, src/server.cpp, src/server.hpp, src/socket_base.cpp, src/socket_base.hpp, src/xsub.cpp, src/xsub.hpp
Solution: remove them
These methods were added by #819, and subsequently in new socket types, since they were required by socket_base, but they are never called. They also use some fields, which are not used (read) anywhere else, so they can be removed as well.
=> Problem: unused get_credential methods and associated fields

Makefile.am, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, src/options.cpp, src/options.hpp, src/router.cpp, src/session_base.cpp, src/session_base.hpp, src/stream_engine.cpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_router_notify.cpp
This PR proposes a new feature for ROUTER sockets on stream oriented transports: configurable connect/disconnect notifications. Related issue/discussion: #3201 
The implementation follows the already existing ZMQ_STREAM_NOTIFY option, notifications are sent close  to the `handshake_succeded` and `disconnected` monitor events.
=> Add ZMQ_ROUTER_NOTIFY draft socket option

RELICENSE/WenbinHou.md, tests/CMakeLists.txt, unittests/CMakeLists.txt
When placing libzmq in a subdirectory, and use cmake `add_subdirectory` command to build libzmq as a sub-project (static build, with ZMQ_BUILD_TESTS ON), some header files are not found.
This is due to usage of `CMAKE_SOURCE_DIR`, `CMAKE_BINARY_DIR` in **unittests/CMakeLists.txt**, which does not refers to libzmq source directory now.
Use `ZeroMQ_SOURCE_DIR`, `ZeroMQ_BINARY_DIR` instead of `CMAKE_SOURCE_DIR`, `CMAKE_BINARY_DIR` in **unittests/CMakeLists.txt**, which allows libzmq to become an "add_subdirectory" target (with static build).
Currently minimum required CMake version (in unittests/CMakeLists.txt: 2.8.1) is enough to support this. See [https://cmake.org/cmake/help/v2.8.1/cmake.html](https://cmake.org/cmake/help/v2.8.1/cmake.html)
> project: Set a name for the entire project.
> …
=> Update unittests/CMakeLists.txt: use ZeroMQ_SOURCE_DIR, ZeroMQ_BINARY_DIR

src/pgm_receiver.cpp
```
```
Please try to have the code changes conform to our coding style. For your
convenience, you can install clang-format (at least version 5.0) and then
run ```make clang-format-check```. Don't fix existing issues, if any - just
make sure your changes are compliant. ```make clang-format-diff``` will
automatically apply the required changes.
To set a specific clang-format binary with autotools, you can for example
run: ```./configure CLANG_FORMAT=clang-format-5.0```
are impossible to fix once merged. Please rebase …
=> PGM receiver crash fix

src/atomic_counter.hpp
The variable `decrement` was changed to `decrement_` for consistency in naming style. 
(c581f43c9)
In -one- place, it had remained as `decrement`
and gives:
In file included from src/ctx.hpp:44:0,
from src/address.cpp:33:
src/atomic_counter.hpp: In member function 'bool zmq::atomic_counter_t::sub(zmq::atomic_counter_t::integer_t)':
src/atomic_counter.hpp:191:28: error: 'decrement' was not declared in this scope
Solution: Changing it to `decrement_` fixes the problem.
Fixes #3229
=> Fix build failure on ARM due to bad variable name

src/udp_engine.cpp
Problem: Binding UDP multicast ports more than once throws "Address already in use errors" [(referenced in this issue).](https://github.com/zeromq/libzmq/issues/3236)
Solution: Add SO_REUSEPORT socket option when binding UDP receive ports on platforms that support it.
=> Added SO_REUSEPORT socket option for UDP recv ports

CMakeLists.txt, tests/CMakeLists.txt, unittests/CMakeLists.txt
Problem: The `CMakeLists.txt` files give a very wildly grown impression
Solution: 
- Make files conform to [cmake-lint](https://github.com/richq/cmake-lint)
- While at it I fixed bad linker flags for `-G"Visual Studio 15 2017" -T"llvm"`
I can also implement changes according to [Effective Modern CMake](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1), if desired.
=> CMake cleanup

INSTALL
Solution: remove the reference
Fixes #3258
=> Problem: INSTALL refers to deprecated VS build instructions

RELICENSE/glemercier.md, src/v1_decoder.cpp
Problem: Compilation with strict AARCH64 compilers is broken
```
make[1]: Entering directory /opt/android/libzmq
CXX      src/src_libzmq_la-v1_decoder.lo
src/v1_decoder.cpp:114:28: error: comparison 'unsigned long' > 18446744073709551615 is always false [-Werror,-Wtautological-constant-compare]
if (payload_length - 1 > std::numeric_limits<size_t>::max ()) {
~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [src/src_libzmq_la-v1_decoder.lo] Error 1
make[1]: Leaving directory /opt/android/libzmq
make: *** [all-recursive] Error 1
```
Solution: ignore the condition when built with AARCH64 compilers. This test does not make sense on 64-bit architectures since 'size_t' and 'uint64_t' have the same size.
=> Problem: Compilation with strict AARCH64 compilers is broken

src/dgram.cpp
In the dgram socket we have a flag that indicates the next expected message type to ensure that always a pair of "address" + "body" messages gets sent. The first one MUST have the sendmore flag, the second MUST NOT.
In case the message does not get sent because of HWM full, then the function returns EAGAIN as it should. But unfortunately the next expected message type-flag gets flipped as well. When the socket_base::send function now tries to resend the message, it became the _wrong_ message type... If you don't stop sending pairs of messages here (like me) then the next message that gets through will be of the wrong type, which in turn crashes the udp_engine function as described in #3268 
This PR fixes the flag behavior and in turn all of the described problems...
=> Problem: The flag that indicates the next expected message gets set even if the send fails

CMakeLists.txt
Problem: CMake stop configuration on:
`zmq_check_noexcept()`
Solution: I added validation on CMake for Android
=> fix for android building

RELICENSE/hpsaturn.md
This is a statement by Antonio Vanegas that grants permission to relicense its copyrights in the libzmq C++ library (ZeroMQ) under the Mozilla Public License v2 (MPLv2).
A portion of the commits made by the Github handle "hpsaturn", with commit author "Antonio Vanegas", are copyright of Antonio Vanegas.
This document hereby grants the libzmq project team to relicense libzmq, including all past, present and future contributions of the author listed above.
Antonio Vanegas
2018/10/27
=> Relicense statement for Hpsaturn

RELICENSE/kfish.md, src/udp_engine.cpp
This adds support for setting the multicast TTL for UDP, allowing multicast traffic to be routed. This feature was already supported for PGM.
=> Add support for UDP multicast ttl (ZMQ_MULTICAST_HOPS)

src/pipe.cpp, src/pipe.hpp, src/socket_base.cpp
Solution: When pipe_t is freed (terminated) remove it from _endpoints member of zmq::socket_base_t. Resolves issue #3245.
In order to optimally search `_endpoints` multimap and find the pipe_t pointer to be removed (set to NULL), `std::string _endpoint_uri` is added into `zmq::pipe_t` class.
=> Problem: Use of pipe_t after free in zmq::socket_base_t::term_endpoint(). Issue #3245.

CMakeLists.txt, Makefile.am, RELICENSE/ssbl.md, src/radix_tree.cpp, src/radix_tree.hpp, src/xsub.hpp, unittests/CMakeLists.txt, unittests/unittest_radix_tree.cpp
Solution: use a radix tree instead of a trie to track subscriptions
This PR also adds unit tests and benchmarks. Based on the discussion
in #1400, the radix tree uses 1/10th of the memory that the trie uses
for the same set of subscriptions. The benchmarks also show upto 3x
speedups in inserting, deleting and looking up subscriptions. These
results are suspect until further code review, although I've tried to
make sure the benchmarks are valid and correct.
Currently the code is a bit inconsistent formatting and style-wise,
but I'm pretty sure that will be easy to fix once we've ironed out any
correctness/design issues! Also, I've excluded the benchmarks from the
build since they use C++11 and add an external dependency.
cc @bluca @sigiesec @jamesdillonharvey
=> Problem: potentially large memory footprint of trie as number of subscriptions increases (issue #1400)

NEWS, include/zmq.h, packaging/debian/changelog, packaging/debian/zeromq.dsc.obs, packaging/redhat/zeromq.spec
The NEWS is only half complete, I'll finish it in the next few days.
Yes, the version is going backwards, but such are the risks of using development versions! Also the ABI does not change so the filename is the same, and the packages built on OBS use the previous version (+date) so they are not affected.
=> Problems: wrong version and outdated NEWS

.github/stale.yml
Solution: enable Stale Bot to automatically mark an issue as stale
after 365 days of inactivity and close it after further 56 days.
Issues marked with the following labels are excluded:
- Help Request
- Feature Request
- Problem reproduced
- Critical
This was proposed on the mailing list in September:
https://lists.zeromq.org/pipermail/zeromq-dev/2018-September/032719.html
@somdoron is this OK with you?
=> Problem: stale issues linger on Github

RELICENSE/toonetown.md, src/tcp.cpp
If the buffer size is huge, `WSAENOBUFS` appears to be returned from `recv` - this is despite the fact that it's not explicitly listed at https://support.microsoft.com/en-us/kb/201213.  See https://github.com/zeromq/libzmq/issues/3263
This PR attempts to address that issue by expecting `WSAENOBUFS` as a valid error that may be returned.
=> Windows apparently returns `WSAENOBUFS` from `recv`

src/signaler.cpp
Solution: change it to the actual required number, 1
The fix to issue #2876, i.e. commit https://github.com/zeromq/libzmq/commit/7a9933f2e11a4cebd38f9aa942b56ccfd4629ebf, uses FD_SETSIZE (16384) for optimized_fd_set_t, although only a single descriptor is used in signaler::wait().
This fix avoids an unnecessary heap allocation of ~128KB.
=> Problem: using FD_SETSIZE for optimized_fd_set_t is a pessimization

README.md, RELICENSE/crocket.md
Solution: Add 'Contributing' section to README.md
Do I need a relicensing grant? I vaguely remember that I consented to MPLv2 in a github issue, but I'm not totally sure.
It fixes https://github.com/zeromq/libzmq/issues/3302
=> Problem: C4 process is not easily discoverable.

.gitignore, .travis.yml, NEWS, ci_build.sh, configure.ac, tests/test_app_meta.cpp, tests/test_router_notify.cpp, unittests/unittest_poller.cpp
=> Problems: some tests still use hard-coded TCP ports, wrong usage of CPPFLAGS, missing NEWS, no way to force C++98 builds and CI for it

acinclude.m4, configure.ac
Per discussions, lets merge the two checks for atomic @bluca  @ffontaine 
This from my perspective accomplishes the goal of the test, which is to show the linker has to include "latomic"
On compilation the same error is produced. (CXXFLAGS is reset so the result below is produced) 
In file included from ./src/ctx.hpp:44:
./src/atomic_counter.hpp:110:21: error: misaligned or large atomic operation may incur significant performance penalty
[-Werror,-Watomic-alignment]
old_value = __atomic_fetch_add (&_value, increment_, __ATOMIC_ACQ_REL);"
Ultimately I removed the save CXX flags citing the bug report previously mentioned.
https://bugs.llvm.org/show_bug.cgi?id=38593
Out of curiosity, what is the basis for using an atomic add operation in C++? Is the built in + not atomic?
=> Consolidation of libatomic checks

Makefile.am, src/libzmq.vers
Using symbol visibility tricks is a common practice to hide library internals from consumers.
Right now `-Wl,--version-script=...` is used on a few selected architectures to hide symbols not already handled by `-fvisibility=hidden`. This leads to clutter in configure.ac and an unmaintainable if/else/endif dance in Makefile.am.
libzmq uses libtool, which provides tools to address symbol visibility needs portably.  This merge request implements that and should improve the situation on all platforms not already using `-Wl,--version-script=...` (Windows, *BSD, Solaris, etc).  It has only been tested on OpenBSD, however.
This merge request does not remove now superfluous OS-specific code in Makefile.am and configure.ac.
=> Portable solution for library symbols visibility

RELICENSE/hgourvest.md, src/tcp_listener.cpp
Problem: Switching or desactivate wifi can lead to have EINVAL error code on Android
Solution: do not abort when this error happen
=> Switching or desactivate wifi can crash Android application

doc/zmq_setsockopt.txt
Noticed there was a small typo in the documentation.
=> Fix a typo - lenght to length

RELICENSE/jacquesg.md, src/ip.cpp
This is problematic on Windows.
Solution: Set TCP_NODELAY after connect()
Reference: https://mail.openvswitch.org/pipermail/ovs-dev/2014-October/290251.html
=> TCP_NODELAY is set prior to connecting

Makefile.am, configure.ac, m4/ax_check_vscript.m4, src/libzmq.vers
libtool -export-symbols-regexp used ld(1) --retain-symbols-file under
the hood, the latter lets some C++ weak symbols make their way into the
dynamic symbols table, along with the zmq_* interface.  This was discussed in #3322. The reason for such behavior is unknown to me.
However, this is a regression for platforms which were previously using -Wl,--version-script.
This pull request goes back to using --version-script or equivalent, extending its use on more platforms such as OpenBSD.
=> Go back to ld --version-script to hide private symbols

src/lb.cpp, src/socket_base.cpp, tests/test_spec_pushpull.cpp
Solution: if a multi-part message cannot be delivered by a PUSH socket
because the pipe is broken mid-way, drop the rest of the frames so that
the atomicity property is not broken.
Fixes https://github.com/zeromq/pyzmq/issues/1244
=> Problem: race condition in PUSH might break atomicity

src/v2_decoder.cpp
Solution: fix it with make clang-format-diff
@sigiesec would appreciate a speedy merge :-)
=> Problem: small formatting issue highlighted by clang

tests/test_pair_ipc.cpp, tests/test_rebind_ipc.cpp, tests/test_reconnect_ivl.cpp, tests/test_use_fd.cpp, tests/testutil_security.hpp
Solutions: use memcpy to avoid unaligned pointer access (SIGBUS on sparc) and use randomised endpoints to avoid races and failures with multiple concurrent runs
=> Problems: test failing on SPARC64 and hard-coded socket binds

NEWS
Solution: add it now that it's been assigned
=> Problem: NEWS for 4.3.1 does not mention CVE number

configure.ac
Solution: correctly enable the definition in platform.hpp so that the
gssapi support is actually built in if requested and available.
=> Problem: gssapi pkg-config check in configure.ac does not work

tests/test_inproc_connect.cpp, tests/test_issue_566.cpp
Solution: mostly false positives, but fix them
=> Problem: GCC warnings about string overflows in tests

doc/zmq_ctx_get.txt, src/ctx.cpp, tests/test_ctx_options.cpp
Solution: remove documents and tests for ZMQ_THREAD_PRIORITY getter. It
never worked and can never work as it has the same value as a get-only
option ZMQ_SOCKET_LIMIT. It cannot be changed without breaking ABI.
Note that the setter works fine as ZMQ_SOCKET_LIMIT is get-only.
Fixes #3362
=> Problem: ZMQ_SOCKET_LIMIT and ZMQ_THREAD_PRIORITY have the same value

CMakeLists.txt, Makefile.am, acinclude.m4, builds/cmake/platform.hpp.in, configure.ac, m4/ax_func_posix_memalign.m4, src/atomic_counter.hpp, src/atomic_ptr.hpp, src/yqueue.hpp
Solutions: fix posix_memalign detection, improve cache alignment for yqueue, prefer CXX11 atomics to compiler intrinsics, add wildcard test to XFAIL
=> Problems: test failures on PPC and GNU/hurd

ci_deploy.sh
Solution: instead of using a temporary release branch that gets
deleted after an arbitrary timer, which never matches the time OBS
actually takes to do a full git clone, keep the branch permanently
in place and simply move it forward to the latest tag on each
release.
=> Problem: race condition breaks automated OBS release

src/socket_base.cpp
Solution: change back the indentifier endpoint to the one passed by the
user rather than the resolved one, otherwise when the user passes the
same string to the disconnect call they do not match anymore
=> Problem: tipc disconnect does not work anymore

src/tcp_address.cpp
Solution: use sprintf instead of std::stringstream
Fixes #3385
=> Problem: tcp address strings are dependent on locale

src/mailbox_safe.cpp
Solution: for zero timeout, unlock and relock immediately instead of timedwait
=> Problem: invoking the conditional variable for zero time is expensive

Makefile.am, tests/CMakeLists.txt
Solution: define UNITY_SUPPORT_64 to force 64 bit support
@bluca this fixes the build for Win32, hope it does also for other 32 bit environments
=> Problem: test build fails on 32 bit systems

perf/benchmark_radix_tree.cpp
Solution: measure the time taken by each lookup call instead
Other changes:
- show average time taken and reduce other output
- show number of keys, queries and key size before running the benchmark
- use steady_clock as high_resolution_clock might not be steady
- increase size of query set to 1M
The output now looks like this:
```
keys = 10000, queries = 1000000, key size = 20
[trie]
Average lookup time = 405.6 ns
[radix_tree]
Average lookup time = 183.4 ns
```
=> Problem: trie benchmarks count loop times instead of lookup calls

RELICENSE/bluca.md
Solution: add it - I realised only now that I only submitted a
statement for the copyright owned by a previous employer, and not
my own.
=> Problem: missing relicensing statement from bluca

RELICENSE/Kymetacorp.md, src/ctx.cpp, src/ctx.hpp, src/io_thread.cpp, src/poller_base.cpp, src/poller_base.hpp, src/reaper.cpp, src/thread.cpp, src/thread.hpp
```
```
Please try to have the code changes conform to our coding style. For your
convenience, you can install clang-format (at least version 5.0) and then
run ```make clang-format-check```. Don't fix existing issues, if any - just
make sure your changes are compliant. ```make clang-format-diff``` will
automatically apply the required changes.
To set a specific clang-format binary with autotools, you can for example
run: ```./configure CLANG_FORMAT=clang-format-5.0```
are impossible to fix once merged. Please rebase …
=> An alternative approach to threads naming

RELICENSE/prarrot.md
Solution: add the one received by email
Message-ID: <CAHPFjttticWbCuZ93r55gGRDBMxAgNn==4r70op4LnQNEJM23Q@mail.gmail.com>
=> Problem: missing relicense statement from Prarrot

RELICENSE/Eelis.md, doc/zmq_poller.txt
=> Document that zmq_poller_new can return NULL.

doc/zmq_poller.txt, src/socket_poller.cpp, src/socket_poller.hpp
=> Don't crash if memory allocation in socket_poller_t::rebuild fails.

.gitignore, CMakeLists.txt, Makefile.am, RELICENSE/emtr.md, perf/proxy_thr.cpp, src/config.hpp, src/proxy.cpp, tests/test_proxy.cpp
As suggested by user somdoron on zeromq-dev mailing list, I implemented the zmq_recv with DONT_WAIT and a benchmark for proxy throughput.
The benchmark shows an important increase of forwarding performance, on my system from ~290kpps to >3Mpps.
Moreover the amount of calls to syscall poll is much lower:
```
Before: 
% time    syscall 
------ -- ------------ 
81.77    poll 
18.22    write
```
After: 
```
% time    syscall 
------ -- ------------ 
96.88    write 
3.11    poll
```
=> Proxy performance fix

tests/test_xpub_nodrop.cpp
Solution: use XPUB and wait for the subscription message rather than
using a sleep which might or might not be enough
=> Problem: text_xpub_nodrop sometimes fails

README.md, src/devpoll.cpp, src/devpoll.hpp, src/epoll.hpp
Restore support for ```/dev/poll``` on Solaris, remove one unused class variable from ```epoll_t```.
=> Restore /dev/poll support

CMakeLists.txt, builds/cmake/platform.hpp.in, configure.ac, src/ipc_address.cpp
Solution: Provide an implementation
I wasn't quite sure where to put the implementation, there is only 1 caller at this stage.
=> Problem: strnlen may not be available

RELICENSE/panlinux.md, tests/test_filter_ipc.cpp, tests/testutil.hpp
Validate the group before using it
This makes the test a bit more robust in scenarios where, probably due  to a misconfiguration in the environment, a group present in the list of supplementary groups is not really a valid choice. This was seen in the Launchpad builders (where `getgrgid(supgroup)` returned `NULL`), and possibly elsewhere (see https://github.com/habitat-sh/core-plans/blob/master/zeromq/plan.sh#L22-L25)
This fixes issue #1462
=> Validate group before using it

.gitignore, tests/test_stream_exceeds_buffer.cpp, tests/test_zmq_poll_fd.cpp, tests/testutil.hpp
Solution: move ephemeral port code to header and use it in both tests
=> Problem: TCP and UDP test sockets use hard-coded port

RELICENSE/ericsson.md
Received via email on 2019/03/27, message-id:
BL0PR1501MB2003AF12CCA96A583B16D10F9A590@BL0PR1501MB2003.namprd15.prod.outlook.com
=> Relicensing grant from Ericsson

RELICENSE/SergheiNovac.md, src/socket_base.cpp, src/vmci_connecter.cpp, src/vmci_listener.cpp
Problem: GCC 5 support was broken
Solution: Some explicit endpoint type changes were made and tested in GCC 5.5.0 and GCC 8.3.0
=> Some explicit endpoint type changes to support GCC 5

packaging/debian/rules
Solution: set hardening=+all in Debian packaging rules
=> Problem: immediate binding hardening not used by debian package

src/socket_base.cpp
Solution: fix it
Yes it looks weird, but it's a known problem in clang-format
=> Problem: CI format check fails

CMakeLists.txt, RELICENSE/omegastick.md
When LIbzmq is used with `add_subdirectory` in CMake, it can't find the includes for the Radix Tree benchmarks because they are found using `CMAKE_SOURCE_DIR`, which points to the source of the whole project, not the libzmq source.
This changes that to `CMAKE_CURRENT_LIST_DIR` which works as expected.
=> Fix Radix Tree benchmark includes when used as submodule

CMakeLists.txt, RELICENSE/ipa.md, builds/qnx/ToolchainQNX6.6_x86.cmake, tests/CMakeLists.txt, unittests/CMakeLists.txt
Solution to #3479 : 
- libm and libsocket have to be linked explicitely
- QNX crosscompiler needs a toolchain file to crosscompile to qnx 
With these modifications libzmq-static could be built. The shared libraries are still not working.
The following CMake command was used to 
```
cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=debug,release -DCMAKE_TOOLCHAIN_FILE="../builds/qnx/ToolchainQNX6.6_x86.cmake" -DBUILD_SHARED=OFF -DPOLLER=poll ..
cmake --build .
```
The unit tests ran without errors on QNX 6.6
[test_output.txt](https://github.com/zeromq/libzmq/files/3094200/test_output.txt)
=> Zeromq 3479: fixed build for QNX 6.6 with CMake

RELICENSE/neheb.md, src/blob.hpp
Under uClibc++, streamoff is defined in <ios>. This header is needed to fix compilation.
=> Add <ios> include to fix uClibc++ compilation

src/signaler.cpp
Solution: remove it since sleep_ms isn't used on Windows
=> Problem: unused Windows-specific code in sleep_ms

RELICENSE/jean-airoldie.md, include/zmq.h, src/socket_poller.cpp, src/socket_poller.hpp, src/zmq.cpp, src/zmq_draft.h
This is based on [somdoron's comment](https://github.com/zeromq/libzmq/issues/2941#issuecomment-366983640).
This partially fixes #2941 by adding a way to retrieve the fd from the zmq::socket_poller_t signaler, if it exists. This allows integration of thread-safe socket types into event loops by creating a poller instance for each thread safe socket and polling the poller's fd.
=>  Problem: Cannot get thread safe socket fd 

RELICENSE/normano.md, doc/zmq_socket_monitor.txt
Solution: Added HANDSHAKE_SUCCEEDED Before MONITOR_STOPPED event on client and before CLOSED event on server.
=> Problem: zmq_socket_monitor example did not include HANDSHAKE_SUCCEEDED event causing assert failure

doc/zmq_poller.txt, src/zmq.cpp, tests/test_poller.cpp
Solution: Add doc & unit tests
This adds unit tests and doc for #3484. I also added `zmq_poller_wait` signature to the doc since it was missing.
=> Problem: Missing doc & unit tests for zmq_poller_fd

configure.ac
Solution: use AC_COMPILE_IFELSE instead of AC_CHECK_FUNCS to check for
strnlen, as the latter does not work anymore.
=> Problem: build broken on Fedora 30

CMakeLists.txt, RELICENSE/moretromain.md
Problem: a small typo in the root CMakeLists.txt for PCH handling in MSVC
Solution: replace wrong variable "soruce" with the expected one "source"
=> Fix a typo in root CMakeLists.txt

include/zmq.h, src/socket_poller.cpp, src/socket_poller.hpp, src/zmq.cpp, src/zmq_draft.h
Solution: use proper fd_t type, and also define and use a zmq_fd_t in the API
=> Problem: syntax error on Windows related to socket descriptor type

doc/zmq_socket_monitor_versioned.txt, include/zmq.h, src/socket_base.cpp, src/socket_base.hpp, src/zmq.cpp, src/zmq_draft.h, tests/test_monitor.cpp
Solution: Allow ZMQ_PUB and ZMQ_PUSH sockets types for the monitoring.
This way someone could create a ZMQ_PULL socket connected to multiple monitoring
sockets at the same time. Or event better, create a ZMQ_PUB monitor socket with `ZMQ_EVENT_ALL` specified and then let the subscribers decide what events they want to receive.
This is especially helpful if someone wants to dedicate only one thread to globally log events.
=> Problem: Socket monitoring only allows ZMQ_PAIR

src/ctx.cpp, src/io_thread.cpp, src/thread.cpp, src/thread.hpp, src/windows.hpp, tests/test_security_curve.cpp, tests/testutil.hpp, tests/testutil_unity.hpp
Problem: thread_t::setThreadName() is not implemented on windows
Solution: implement setThreadName() by using the exception method (compatible with all win32 versions)
More info here: https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2019
=> Implement thread_t::setThreadName() on windows

RELICENSE/ackalker.md, acinclude.m4, configure.ac
Use `test` with `=` operator instead of `==` operator to make POSIX-like shells happy.
This fixes #3517 .
=> acinclude.m4, configure.ac: Fix several non-portable uses of `test`

RELICENSE/jackpimbert.md, doc/zmq_pgm.txt
Problem: PGM doc missing info on high data rates
Solution: Include a new section on configuring both ZMQ and the host
OS tx/rx buffers to facilitate sending large messages at a high data
rate with the PGM protocol.
---
Issue #2076 discusses problems that were encountered when attempting to multicast high data rates with the PGM protocol. There are some settings on both ZMQ and the host OS that must be changed in order to successfully multicast with higher rates. These setting changes have been added to the docs on PGM.
Please let me know if anything should be reformatted/moved to another place in the doc file.
=> Add missing information on multicasting with high data rates to PGM docs

doc/zmq_msg_send.txt
Solution: Explicitly explain message ownership semantics when the call
fails.
Fixes #3526.
=> Problem: Unclear `zmq_msg_send` failure semantics

RELICENSE/guillon.md, src/socks_connecter.cpp
Two issues where introduced by commit 12c4b55a:
- the proxy connection was done to the target address instead of
the proxy address
- on error the proxy connection status was not reset to unplugged
=> Fix issues with SOCKS5 proxy connection

doc/zmq_setsockopt.txt, include/zmq.h, src/options.cpp, src/options.hpp, src/session_base.cpp, src/socks.cpp, src/socks.hpp, src/socks_connecter.cpp, src/socks_connecter.hpp, src/zmq_draft.h
Implement SOCKS5 basic authentication with username/password.
This adds two new setsockopt options ZMQ_SOCKS_USERNAME, and ZMQ_SOCKS_PASSWORD.
Refer to the documentation part for details.
Note that the choice has been done to add username/password through socket options as is done for some other level of authentication (for instance ZMQ_PLAIN_USERNAME/ZMQ_PLAIN_PASSWORD options).
Another choice (or an additional method) could be to augment the ZMQ_SOCKS_PROXY options (currently: "server:port") in order to include authentication information, for instance: "user:password@server:port".
=> Implement SOCKS5 basic authentication

src/thread.cpp
I am trying to port ZeroMQ to z/OS USS and I faced several problems. One of them is this function "is_current_thread" trying to compare two thread ids with operator "==". I've changed the code to use the official function "pthread_equal" to compare thread ids and now it's working fine.
This is a statement by Philippe Leite that grants permission to
relicense its copyrights in the libzmq C++ library (ZeroMQ) under the
Mozilla Public License v2 (MPLv2) or any other Open Source Initiative
approved license chosen by the current ZeroMQ BDFL (Benevolent
Dictator for Life).
A portion of the commits made by the Github handle "philippeleite", with
commit author "Philippe Leite <philippe.leite@gmail.com>", are
copyright of Philippe Leite.  This document hereby grants the libzmq
project team to …
=> pthread_equal to compare thread ids

tests/testutil_unity.cpp, tests/testutil_unity.hpp
Solution: pass the line number as part of the testutil functions
=> Problem: test assertions not reporting the right line number

Makefile.am, tests/test_socks.cpp
This pull request adds tests/test_socks.cpp for testing socks proxy support.
Please do not merge yet, until I can check if the coverage report is what I should expect.
Also I added the test to Linux only for now as I do not have the possibility to test on other hosts.
=> Add tests for SOCKS proxy support

doc/zmq_disconnect.txt, doc/zmq_unbind.txt
This closes #3529.
I also made it explicit that `zmq_disconnect` is the preferred option.
This documentation is inferred from my usage of the `Server` and `Client` socket. However, I am unsure if it can be generalized to all socket types.
=> Problem: disconnect & unbind doc is misleading

tests/test_heartbeats.cpp
Solution: Add heatbeat tests for RADIO, DISH, CLIENT, SERVER, GATHER and SCATTER
socket types.
Note that currently there are two failures, which are consistent with my experience. I'll open an issue concerning this.
```
test_heartbeat_notimeout_dish_radio:FAIL
test_heartbeat_notimeout_dish_radio_with_curve:FAIL
```
=> Problem: missing heartbeat test for draft sockets

doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, src/config.hpp, src/norm_engine.cpp, src/norm_engine.hpp, src/options.cpp, src/options.hpp, src/pgm_socket.cpp, src/stream_engine.cpp, src/zmq_draft.h
Solution: Added a socket option to configure them at runtime.
This is especially helpful when dealing with small messages to improve throughput.
=> Problem: {in,out}_batch_size must be configured at compiled time

src/radix_tree.cpp, src/radix_tree.hpp
Solution: use more descriptive names
This commit also improves comments related to some of the changes.
Names in the `zmq` namespace aren't modified, the code still has some inconsistencies with the naming conventions.
=> Problem: variable and type names are not descriptive

builds/cmake/ZeroMQConfig.cmake.in
https://github.com/microsoft/vcpkg/pull/7203
=> Problem: Missing ZeroMQ_INCLUDE_DIR when only static lib is built

src/curve_client.cpp
Problem: Malicious clients can cause arbitrary amounts of memory to leak (well, fixed amout an arbitrary number of times).
Solution: Free memory in the error case.
=> Free memory when curve_client sends invalid ready message.

builds/abi-compliance-checker/ci_build.sh, src/udp_engine.cpp, tests/testutil_monitoring.cpp
@TomMD it seems the tool doesn't see when variables are used for array sizes, these are false positives:
1. DEAD_STORE
- At [src/tcp_address.cpp(121,5)](https://github.com/zeromq/libzmq/blob/90ff30c086bc299d619346a04d9eb5a02e96636e/src/tcp_address.cpp#L121)
- The value written to &max_port_str_length (type unsigned long const ) is never used.
1. DEAD_STORE
- At [src/tcp_address.cpp(288,5)](https://github.com/zeromq/libzmq/blob/90ff30c086bc299d619346a04d9eb5a02e96636e/src/tcp_address.cpp#L288)
- The value written to &max_mask_len (type unsigned long const ) is never used.
These are also false positives, the struct is initialized by the systemcall:
1. UNINITIALIZED_VALUE
- At [src/stream_engine.cpp(79,13)](https://github.com/zeromq/libzmq/blob/90ff30c086bc299d619346a04d9eb5a02e96636e/src/str …
=> Static analysis warnings

src/curve_client.cpp, src/curve_client_tools.hpp, src/curve_mechanism_base.cpp, src/curve_server.cpp
Solution: use std::vector instead, simplify control-flow
=> Problem: use of malloc is error-prone

.clang-format, CMakeLists.txt, Makefile.am, perf/benchmark_radix_tree.cpp, src/curve_client.cpp, src/curve_client_tools.hpp, src/curve_mechanism_base.cpp, src/curve_mechanism_base.hpp, src/curve_server.cpp, src/secure_allocator.hpp, tests/test_security_curve.cpp
=> Use libsodium based allocator

.gitignore, CMakeLists.txt, Makefile.am, external/sha1/sha1.c, external/sha1/sha1.h, include/zmq.h, src/address.cpp, src/address.hpp, src/session_base.cpp, src/session_base.hpp, src/socket_base.cpp, src/stream_connecter_base.cpp, src/stream_connecter_base.hpp, src/ws_connecter.cpp, src/ws_connecter.hpp, src/ws_decoder.cpp, src/ws_decoder.hpp, src/ws_encoder.cpp, src/ws_encoder.hpp, src/ws_engine.cpp, src/ws_engine.hpp, src/ws_listener.cpp, src/ws_listener.hpp, src/ws_protocol.hpp, tests/test_ws_transport.cpp
Solution: implement ZWS 2.0 which is websocket transport for zeromq
Tasks:
=> problem: browser cannot communicate with zeromq directly

src/stdint.hpp, tests/test_security_curve.cpp
Solution: move the definition of __STDC_LIMIT_MACROS somewhere the test actually uses
=> Problem: build on centos6/ubuntu12 still broken

CMakeLists.txt, RELICENSE/inuik.md
Problem: When installing msvc debug builds via CMake, the corresponding system debug libraries (dll) like msvcp140d.dll, vcruntime140d.dll ... are not copied to the install path instead only the release versions are copied. This is not a problem if Visual Studio is installed on the target machine, otherwise one has to copy these system libraries manually.
Solution: Configure CMake module InstallRequiredSystemLibraries to install debug libraries in case of debug builds.
=> CMake: Install debug libraries for debug msvc builds

doc/zmq_ctx_set.txt
Solution: update the doc with the correct default value
The doc incorrectly reports this constant to be `1024`.
https://github.com/zeromq/libzmq/blob/a84ffa12b2eb3569ced199660bac5ad128bff1f0/include/zmq.h#L228
=> Problem: incorrect ZMQ_MAX_SOCKETS default value in doc

RELICENSE/mancasg.md, src/stream_engine_base.cpp
Solution: Don't allow concurrent heartbeat timers
=>  Problem: stream_engine use after free

RELICENSE/aixxe.md, src/udp_address.cpp
Encountered the following error when compiling with `ZMQ_WIN32_WINNT` set to `0x0501`.
```
libzmq/src/udp_address.cpp: In member function 'int zmq::udp_address_t::resolve(const char*, bool, bool)':
libzmq/src/udp_address.cpp:107:31: error: 'if_nametoindex' was not declared in this scope
107 |             _bind_interface = if_nametoindex (src_name.c_str ());
|                               ^~~~~~~~~~~~~~
```
Wrapping a `ZMQ_HAVE_WINDOWS_TARGET_XP` check around the call seems to fix this.
I've used the same condition [as the one here](https://github.com/zeromq/libzmq/blob/b8b1b8def349f448f0861c6deeecae914213914c/src/ip_resolver.cpp#L707). Hope this all looks good.
=> Problem: Usage of 'if_nametoindex' not supported in Windows XP.

RELICENSE/latchmoor-services-carcich.md, include/zmq.h
how it declares the file descriptor (fd) of a socket
in struct zmq_pollitem_t vs. struct zmq_poller_event_t
Solution:  Make include/zmq.h consistent in this matter
=> Problem:  include/zmq.h is not so much broken as inconsistent in

src/thread.cpp
```__try``` and ```__catch``` isn't available, push/pop an exception handler manually.
Fixes #3586
=> mingw thread name fix

CMakeLists.txt, RELICENSE/bl0x.md
Problem: Build of bundled unity would not succeed on Scientific Linux 6.9 because of insufficient compiler flags.
Solution: Add -std=gnu99 flag in case -std=gnu11 is no supported.
=>  Fix build on SL6.9. Fix #3603. 

perf/generate_csv.sh, perf/generate_graphs.py, perf/proxy_thr.cpp
This PR adds 2 scripts:
- generate_csv.sh to generate a set of .csv files by running all existing ZMQ benchmark apps
- generate_graphs.py to actually generate .png files from those .csv files
This PR is still work in progress but I'm creating this to start get some feedback if any.
=> Add scripts to ease performance graph generation

builds/cmake/platform.hpp.in, configure.ac, src/ip.cpp
On DragonFly the zmq::enable_ipv4_mapping in ip.cpp fais with a not supported error
So handle this case the same as for OpenBSD
Also update configure files to set the correct definitions for DragonFly OS
This includes all patches from the dports/net/libzmq/dragonfly patches directory
=> [DragonFlyBSD] fix for IPv4 mapping not supported

.travis.yml, RELICENSE/fanquake.md
solution: remove `sudo:false` usage from `travis.yml`
Travis has deprecated the usage of `sudo:false` in `travis.yml`.
See this blog post for more details: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Also: https://docs.travis-ci.com/user/reference/trusty/#container-based-infrastructure
=> problem: sudo:false has been deprecated by Travis CI

CMakeLists.txt
Problem: Builds fails with `ninja: error: build.ninja:995: multiple rules generate precompiled.hpp [-w dupbuild=err]` (Ninja is extremely strict with build rules).
Solution: Add a flag `ENABLE_PRECOMPILED` to disable precompiled headers for MSVC. Defaults to `On` to avoid changes in behavior for other users.
License was singed in #3247
=> [CMake] Add ENABLE_PRECOMPILED option

RELICENSE/atomashpolskiy.md, src/ip.cpp, src/ip.hpp, src/tcp.cpp, src/tcp.hpp, src/udp_engine.cpp, src/udp_engine.hpp
This refactoring is supposed to prevent ZeroMQ from terminating upon UDP engine tuning errors (in `zmq::udp_engine_t::plug`). As far as I was able to figure out, the session will terminate silently on `protocol_error`, which isn't good, probably. Not really sure, where to go from here...
=> UDP engine aborts on networking-related errors from socket syscalls #2862

appveyor.yml
Solution: include all *.lib files
Fixes #3635
=> Problem: appveyor binary archives do not contain import libraries

src/ip.cpp, src/ip.hpp, src/tcp.cpp, src/udp_engine.cpp
Follow-up for UDP send/receive. Also updated `plug` function to terminate session only when `setsockopt` failed, and request reconnection otherwise. Still haven't looked into how socket monitoring events work, so error handling happens silently.
Note that I added EAGAIN/EWOULDBLOCK and EPIPE in the list of "recoverable" errors.
=> UDP engine aborts on networking-related errors from socket syscalls (2) #2862

doc/zmq_ctx_get_ext.txt, doc/zmq_ctx_set_ext.txt, include/zmq.h, src/ctx.cpp, src/ctx.hpp, src/zmq.cpp, src/zmq_draft.h, tests/test_ctx_options.cpp
Problem: today we can only set/get numeric options on the ZMQ contexts. This is no good for an existing option (ZMQ_THREAD_NAME_PREFIX) which naturally takes on string values. Moreover it does not allow future developments e.g. the ones discussed in #3631 where a complex data structure should be set on the ZMQ context.
Solution: Introduce DRAFT zmq_ctx_set_ext() and zmq_ctx_get_ext() methods. Change ZMQ_THREAD_NAME_PREFIX to allow for non-numeric thread name prefixes.
NOTE: this PR is missing docs. If it looks fine I can write them.
=> Introduce extended set/get methods for ZMQ contexts

RELICENSE/msune.md
Add RELICENSE document for msune contributions, both for:
* marcdevel at gmail dot com
* marc at voltanet io
=> RELICENSE: add relicense agreement from msune

src/xpub.cpp, tests/test_xpub_manual.cpp
Solution: fix regression introduced by:
https://github.com/zeromq/libzmq/pull/3168
Correctly fall back to user message if the first byte is neither 0 nor
1, and add a simple unit test
Fixes https://github.com/zeromq/libzmq/issues/3656
=> Problem: can no longer send user data from XSUB to XPUB

Makefile.am
Solution: add libtestutil.a before libzmq.a in LDADD listings, as the
linker will complain about undefined symbols otherwise
Fixes https://github.com/zeromq/libzmq/issues/3646
=> Problem: static-only test run fails

CMakeLists.txt, RELICENSE/straubar.md
In our project, we include libzmq via the FetchContent mechanism and add it using add_subdirectory. In the already set CMAKE_CXX_FLAGS_DEBUG and CMAKE_CXX_FLAGS_RELWITHDEBINFO, we have multiple flags set, such as /Zc:twoPhase-. By applying the regex replace, this was converted to /Z7:twoPhase-, which caused the compilation to fail. The now proposed regex replace is a bit safer, as it does not touch flags containing a ":".
=> Safer regex replace, keeping options like "/Zc:twoPhase-" intact

.travis.yml, CMakeLists.txt, Makefile.am, builds/cmake/Modules/FindNSS3.cmake, builds/cmake/platform.hpp.in, ci_build.sh, configure.ac, src/address.cpp, src/address.hpp, src/ctx.cpp, src/session_base.cpp, src/socket_base.cpp, src/ws_engine.cpp
Solution: use external library for sha1.
Part of this commit is making websocket transport optionable
=> problem: sha external file conflict with czmq

RELICENSE/dimpase.md, configure.ac
Allow "configure --disable-maintainer-mode" to disable timestamp checking.
This is useful for one-off builds, in particular on e.g. clusters, where slightly skew clocks force aclocal and friends to kick in for no good reason.
=> Allow "configure --disable-maintainer-mode"

doc/zmq_msg_send.txt, doc/zmq_send.txt, doc/zmq_send_const.txt, doc/zmq_sendmsg.txt, doc/zmq_socket.txt
Sockets that block in mute state only block when no peer is available if the transport is connection-oriented and the ZMQ_IMMEDIATE socket option is set.
May provide clarification for #3248.
=> Fix documentation about sockets blocking on send operations

src/dbuffer.hpp
This commit actually solves two problems that originated in `dbuffer::write`:
- only one subscriber could receive messages: since the pending message was moved to the back buffer, it was closed and further writes of the same message to other conflate pipes were writes of an empty message.
- leaking messages when one subscriber is not responsive: the front buffer being not closed because of this, swapping the front buffer with the back buffer does not release its enclosed pending message. `msg_t::move` is more indicated in that case.
As such, provides a fix for #3323.
=> Fix behavior of ZMQ_CONFLATE on PUB sockets

.gitignore, .travis.yml, Makefile.am, builds/valgrind/ci_build.sh, ci_build.sh, configure.ac, include/zmq.h, src/address.cpp, src/address.hpp, src/ctx.cpp, src/options.cpp, src/options.hpp, src/session_base.cpp, src/session_base.hpp, src/socket_base.cpp, src/stream_engine_base.cpp, src/stream_engine_base.hpp, src/ws_connecter.cpp, src/ws_connecter.hpp, src/ws_engine.cpp, src/ws_engine.hpp, src/ws_listener.cpp, src/wss_engine.cpp, src/wss_engine.hpp, src/zmtp_engine.cpp, tests/test_wss_transport.cpp
Solution: support websocket with tls (wss)
=> problem: unsecured websocket is rarely used in production

README.md, RELICENSE/ThePrez.md, configure.ac
IBM i uses zeromq in a runtime called PASE (self-identifies as 'os400' due to historical complexities), which is a variant of AIX.
=> Add IBM i build support

src/wss_engine.cpp
Solution: disable handshake timeout
=> problem: GNUTLS handshake is getting blocked because of timeout on some versions

src/curve_mechanism_base.cpp
Solution: when a zero-sized message is encoded or decoded avoid mem copy
=> problem: zero-sized messages cause assertion when glibc assertion are on

tests/test_wss_transport.cpp
=> Problem: test_wss_transport doesn't compile without DRAFT

RELICENSE/yan12125.md, src/libzmq.pc.in
* Problem: pkg-config file cannot be used for static linking on CentOS 7
Solution: add -lm to Libs.private of libzmq.pc so that the std::ceil
usage in src/decoder_allocators.cpp is satisfied during static linking
on CentOS 7.
See https://github.com/zeromq/libzmq/issues/3710 for a reproducer.
* Add relicense note for @yan12125
Based on RELICENSE/templates/relicense-template-mplv2.txt. MPLv2 is
definitely fine, but I'm not sure if I'm OK with other licenses.
Both commits are signed with my PGP key. The public key can be found at https://keybase.io/yan12125/pgp_keys.asc.
=> Fix linking to libzmq.a statically on CentOS 7

RELICENSE/benjaminderoche.md, builds/android/android_build_helper.sh, builds/android/ci_build.sh
Solution: Migrate build scripts from Android NDK r11c to r20.
- Standalone toolchain
- Migration from GCC to Clang
- Migration from libgnustl to libc++
- Dropped support for API level below 16 (Android 4.1), previously it was API level 9 (Android 2.3)
- Dropped support for mips architecture
- The build script now start the build of all 4 Android architectures (arm, arm64, x86, x86_64)
This bring the changes made on android build scripts from zproject to libzmq zeromq/zproject#1210
=> Problem: Android build script is severely outdated

packaging/debian/control, packaging/debian/zeromq.dsc.obs
Solution: add alternative dependency as libgnutls-dev | libgnutls28-dev,
so that the resolver can break the tie, as libcurl4-nss-dev depends on
libgnutls-dev which conflicts with libgnutls28-dev
=> Problem: libzmq-dev not installable with libczmq-dev on Ubuntu 16.04

src/select.cpp
WSAEventSelect is used on Windows (when select is the polling method)
only if waiting for more than one socket family, excluding IPv4/6.
It is then passed FD_OOB, which means it can be woken by OOB messages,
but select later on never checks for it.
Remove FD_OOB as it's not actually used for anything.
=> Problem: WSAEventSelect checks for FD_OOB, but select does not

RELICENSE/viciious.md, packaging/redhat/zeromq.spec
The following lines in the .spec file ensure that the necessary packages are present on the system in case the rpm is being built with libsodium support enabled:
```
%bcond_with libsodium
%if %{with libsodium}
BuildRequires:  libsodium-devel
%define SODIUM yes
%else
%define SODIUM no
%endif
```
```
%{?_with_libsodium:BuildRequires: libsodium-devel}
%{?_with_libsodium:Requires: libsodium}
```
Unconditionally requiring libsodium-devel makes it impossible to build the spec file with default arguments if the aforementioned package is not installed. This merge request amends that.
=> Remove the superfluous build requirement of libsodium-devel

CMakeLists.txt, RELICENSE/eldruin.md
Internally we rename the libraries we integrate as to avoid interference with the library versions already available on the target systems by giving them a prefix.
This PR allows users to specify, for example:
```
-DZMQ_OUTPUT_BASENAME:STRING=MYORG_zmq
```
I used `BASENAME` as the flavor and/or version are appended later.
Alternatively, it would be also fine for us to add a prefix variable like `OUTPUT_NAME_PREFIX` or so but I was unable to find a good name that cannot be confused the target `PREFIX` property (e.g. `lib`)
=> Allow library output name to be changed externally

RELICENSE/drolevar.md, src/select.cpp, src/xpub.cpp, src/xpub.hpp, src/xsub.cpp, src/xsub.hpp, tests/test_xpub_manual.cpp
Now only the first part in a multipart message will be treated as subscribe/unsubscribe.
The rest will be considered user messages regardless of the first byte.
=> Change XSUB -> XPUB multipart message processing.

doc/zmq_setsockopt.txt, include/zmq.h, src/xpub.cpp, src/xpub.hpp, src/xsub.cpp, src/xsub.hpp, src/zmq_draft.h, tests/test_xpub_manual.cpp
Now if the first frame in a multipart message is not subscribe/unsubscribe,
the rest of the parts are also considered to be not subscribe/unsubscribe.
=> Change XSUB -> XPUB message processing.

RELICENSE/kanonet.md, src/ip.cpp
Hi,
this fixes compiling the lib under msys2-mingw.
Tests need further commits to be able to get compiled.
=> mingw: add missing namespace

acinclude.m4
Add -latomic to PKGCFG_LIBS_PRIVATE so applications linking statically
with libzmq (such czmq) will know that they have to link with -latomic
and the following build failure will be avoided:
```
CCLD     src/czmq_selftest
/home/buildroot/autobuild/run/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/7.4.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: /home/buildroot/autobuild/run/instance-3/output-1/host/sparc-buildroot-linux-uclibc/sysroot/usr/lib/libzmq.a(src_libzmq_la-ctx.o): in function `zmq::ctx_t::create_socket(int)':
ctx.cpp:(.text+0x1710): undefined reference to `__atomic_fetch_add_4'
```
Fixes:
- http://autobuild.buildroot.org/results/4a12f1ede260cd956a0b5ccb4eec6ca8b44cb04f
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> acinclude.m4: add -latomic to PKGCFG_LIBS_PRIVATE

RELICENSE/std-any-emplace.md, doc/zmq_poll.txt, doc/zmq_poller.txt
See https://github.com/zeromq/libzmq/issues/3778.
=> Documentation fix regarding thread-safety of zmq_poll/zmq_poller.txt.

doc/zmq_ctx_shutdown.txt, doc/zmq_socket.txt, src/ctx.cpp, tests/test_ctx_destroy.cpp
Solution: fix handling of _starting and _terminate flags
Add tests for this situation.
Clarify documentation of zmq_ctx_shutdown and zmq_socket.
Fixes #3792
=> Problem: sockets can be created after calling zmq_ctx_shutdown

CMakeLists.txt
Else the flag gets joined with the flag following this and clang-cl does not like that.
=> Add an extra space after "/Z7" in CMakeLists.txt.

CMakeLists.txt, Makefile.am, src/curve_client.cpp, src/curve_mechanism_base.cpp, src/curve_mechanism_base.hpp, src/curve_server.cpp, src/msg.cpp, src/msg.hpp, tests/testutil.hpp, unittests/CMakeLists.txt, unittests/unittest_curve_encoding.cpp
I did a few runs on my desktop machine and average throughput via TCP loopback increases from ca. 5800 MB/s to 6100 MB/s for a 10k message size. Not statistically validated, but seems promising.
As a follow-up to this, performance can still be further optimised as discussed by saving one remaining extra memory allocation and copy on the encoding side, and by saving one copy on the decoding side.
=> CURVE: Reduce number of memory allocations and message copies

tests/test_heartbeats.cpp, tests/testutil.cpp, tests/testutil.hpp
Solution: increase number of retries when reading monitor event
=> Problem: intermittent timeouts on test_heartbeats

tests/test_monitor.cpp, tests/testutil_security.cpp
@bluca @somdoron Adding the additional loop in `test_monitor_versioned_basic` seems to fix the intermittent failures. We might add this to the test, but I think that it shouldn't really be required for a user to always wait for ZMQ_EVENT_MONITOR_STOPPED. I can show you tomorrow what happens in the bad case without this addition.
=> Fix intermittent test_monitor and test_security_zap timeouts/deadlocks for now

RELICENSE/cwsmith.md, src/err.hpp
Compiling libzmq 4.3.2 (via spack) with the IBM XL 16.1.1 results in the following errors:
```
CXX      src/src_libzmq_la-address.lo                                                                         
In file included from src/address.cpp:33:                                                                                                                                                                                       
In file included from ./src/ctx.hpp:38:                                                                                                                                                                                         
In file included from ./src/mailbox.hpp:39: …
```
=> support compiling with IBM XL 16.1 w/ clang front end

CMakeLists.txt, Makefile.am, src/msg.cpp, src/msg.hpp, src/sub.cpp, src/v1_encoder.cpp, src/v2_encoder.hpp, src/v3_1_encoder.cpp, src/v3_1_encoder.hpp, src/xpub.cpp, src/xsub.cpp, src/zmtp_engine.cpp, src/zmtp_engine.hpp, tests/test_mock_pub_sub.cpp, tests/test_stream.cpp
Thanks @somdoron for the suggestion to move the handling of the flag/command to the engine. Backward compatibility is retained. The drawback is that if a single sub/unsub is sent on a sub connected to many pubs, the work will be redone everytime. But it's a one byte or 7/11 bytes fixed size buffer, so it shouldn't make much of a difference, as it's just adding to an existing 2 bytes buffer.
=> Implement ZMTP 3.1 subscribe/cancel via commands

.gitignore, CMakeLists.txt, Makefile.am, doc/Makefile.am, doc/zmq_connect_peer.txt, doc/zmq_socket.txt, include/zmq.h, src/mechanism.cpp, src/peer.cpp, src/peer.hpp, src/session_base.cpp, src/socket_base.cpp, src/socket_base.hpp, src/zmq.cpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_peer.cpp
Solution: a new socket type, called PEER. Very similar to SERVER, but can only connect to other PEERs. Also, a new zmq_connect_peer method, that connects and return a routing-id in a thread-safe and atomic operation.
I created this around two years ago for a crypto project that used NetMQ for the network protocol.
=> problem: zeromq doesn't has a thread-safe peer to peer socket

RELICENSE/lstacul.md, perf/proxy_thr.cpp
The PR fixed the unused-variable warning/error in perf/proxy_thr.cpp:
```
perf/proxy_thr.cpp: In function ‘int main(int, char**)’:
perf/proxy_thr.cpp:335:9: error: unused variable ‘rv’ [-Werror=unused-variable]
335 |     int rv = zmq_ctx_set (context, ZMQ_IO_THREADS, 4);
|         ^~
perf/proxy_thr.cpp:403:9: error: unused variable ‘rc’ [-Werror=unused-variable]
403 |     int rc = zmq_ctx_term (context);
|         ^~
```
=> Fix unused-variable warning in perf/proxy_thr.cpp

Makefile.am, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, src/command.hpp, src/object.cpp, src/object.hpp, src/options.cpp, src/options.hpp, src/session_base.cpp, src/session_base.hpp, src/stream_connecter_base.cpp, src/stream_connecter_base.hpp, src/tcp_connecter.cpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_reconnect_options.cpp
Problem: reconnecting to disconnected endpoint continues "forever"
ZeroMQ's automatic reconnection works reasonably well for processes that bind to "well-known" ports, but it works less well for processes that bind to "wildcard" ports, which are satisfied by the OS choosing an available ephemeral port.
Solution: With @somdoron's help, we've implemented a solution to this problem. This change will cause ZeroMQ to stop reconnecting (and "forget" the endpoint), under the following conditions:
1. If a connection attempt returns ECONNREFUSED, that indicates that the host received the connect, but that there is no code listening at that port.  In that case, we know that the original process has terminated (either normally or abnormally), and stop trying to reconnect.
=> add option to stop trying to reconnect on ECONNREFUSED

README.md, RELICENSE/mjvk.md
Problem: QNX 7.0 is not listed as being possible to compile on
Solution: Add to list with active users
=> Adds QNX as possible to compile on

RELICENSE/Ricardicus.md, src/ip_resolver.hpp
I was building libzmq 4.3.2 and I came across this C++ warning: 
>  warning: ‘class zmq::ip_resolver_t’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
There is a class named **ip_resolver_t** that has virtual functions but
no virtual destructor.  That can cause undefined behavior if someone deletes a derived-class via a base-class pointer
I made a change to silence the warning, and I though maybe
perhaps you would like to have this change.
=> ip_resolver_t: Silencing C++-warning -Wnon-virtual-dtor

INSTALL, RELICENSE/jsyoo5b.md
Solution: Add troubleshooting guidelines to resolve
In OS X, generating man pages by asciidoc and xmlto may not work correctly.  
This issues were mentioned in other projects which supports build in OS X.
Following files are captured logs in OS X.
[configure.log](https://github.com/zeromq/libzmq/files/4270188/configure.log)
[make-failed.log](https://github.com/zeromq/libzmq/files/4270189/make-failed.log)
Also checked on Ubuntu 18.04 and archlinux.  They didn't have any similar problem.
=> Problem: building on OS X may failed

doc/zmq_bind.txt, doc/zmq_connect.txt, doc/zmq_unbind.txt
Problem: UDP is not mentioned as avaliable transports in zmq_bind() and zmq_connect()
I've found zmq_udp(7) has been added with RADIO-DISH describing commit fee84134e7c1f30578bb8b013e911b7dbde79ea6  
I think this commit missed referencing UDP in zmq_bind(7) and zmq_connect(7)
I think UDP also need to be mentioned in wild-card addressing parts (zmq_bind and zmq_unbind)
=> Add UDP transport to related docs

src/address.hpp, src/session_base.cpp, src/socket_base.cpp, src/zmq.cpp
Protcol string for PGM, EPGM and NORM is still represented in literal strings.
While changing literals into constants, I also applied conditional compile for them.  
Some code blocks didn't covered with conditional compile, and the others is using both PGM and NORM.  
I tried to change those code blocks as simple as possible, but some code blocks seems messy.
I want someone review and comment especially for following code blocks. (I've marked WiP just for review)
[Code block1](https://github.com/JSYoo5B/libzmq/blob/5a933a0/src/socket_base.cpp#L371-L385)
[Code block2](https://github.com/JSYoo5B/libzmq/blob/5a933a0/src/socket_base.cpp#L556-L563)
[Code block3](https://github.com/JSYoo5B/libzmq/blob/5a933a0/src/socket_base.cpp#L1038-L1046)
=> [WiP] Refactor protocol literals into constants

CMakeLists.txt, RELICENSE/ferdnyc.md
Using `share/cmake/${PROJECT_NAME}` as `DESTINATION` for installing `ZeroMQConfig.cmake` et al works for arch-independent configs (like cppzmq's header-only package), but is wrong for arch-dependent packages when installed on multiarch systems.
The `...Config.cmake` file is the _library interface_ definition, and in arch-dependent multiarch builds is specific to the architecture currently being built. Each build of a library should have its interface installed below the arch-dependent LIBDIR.
This PR sets the default `ZEROMQ_CMAKECONFIG_INSTALL_DIR` to `"${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"`, using the GNUInstallDirs `${CMAKE_INSTALL_LIBDIR}` variable to target the correct arch-dependent dir.
See e.g. Daniel Pfeifer's "Effective CMake" ([PDF of slides from CPPNow …
=> Install CMake config to LIBDIR by default, to correctly support multiarch

.gitignore
Source files in tools/ must be tracked.  
But exception marking was missing.  
It was mistake in commit 2478887.
=> Fix gitignore tracking file list

doc/zmq_getsockopt.txt
Solution: Change documentation value type to int
The tests for this option do use `int` as value type.
=> Problem: ZMQ_THREAD_SAFE is not bool

Makefile.am, builds/gyp/project-tests.gypi, builds/gyp/project-tests.xml, doc/Makefile.am, doc/zmq.txt, doc/zmq_msg_close.txt, doc/zmq_msg_copy.txt, doc/zmq_msg_data.txt, doc/zmq_msg_init.txt, doc/zmq_msg_init_buffer.txt, doc/zmq_msg_init_data.txt, doc/zmq_msg_move.txt, doc/zmq_msg_size.txt, include/zmq.h, src/msg.cpp, src/msg.hpp, src/zmq.cpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_msg_ffn.cpp, tests/test_msg_init.cpp
Solution: Add zmq_msg_init_buffer to construct
a message by copying memory from buffer.
See issue https://github.com/zeromq/libzmq/issues/3858
=> Problem: boilerplate when init msg from data copy

doc/zmq_poller.txt, src/socket_poller.cpp, tests/test_poller.cpp
Solution: Fail with error if no events are active and timeout is infinite
=> Problem: poller sleeps forever if no events

Makefile.am, doc/zmq_setsockopt.txt, include/zmq.h, src/client.cpp, src/ctx.cpp, src/dealer.cpp, src/options.cpp, src/options.hpp, src/peer.cpp, src/pipe.cpp, src/pipe.hpp, src/router.cpp, src/server.cpp, src/session_base.cpp, src/session_base.hpp, src/socket_base.cpp, src/zmq_draft.h, tests/test_hello_msg.cpp
When using ZMQ_HEARTBEAT one still needs to implement application-level heartbeat in order to know when to send a hello message.
For example, with the majordomo protocol, the worker needs to send a READY message when connecting to a broker. If the connection to the broker drops, and the heartbeat recognizes it the worker won't know about it and won't send the READY msg.
To solve that, the majordomo worker still has to implement heartbeat. With this new option, whenever the connection drops and reconnects the hello message will be sent, greatly simplify the majordomo protocol, as now READY and HEARTBEAT can be handled by zeromq.
=> problem: ZMQ_HEARTBEAT is not useful without sending an hello message

doc/zmq_poller.txt, include/zmq.h, src/zmq.cpp, src/zmq_draft.h, tests/test_poller.cpp
Solution: Add zmq_poller_size that queries the number
of objects registered, allowing safer usages of poller
to avoid livelock situations.
=> Problem: No support to query poller size

Makefile.am, doc/zmq_setsockopt.txt, include/zmq.h, src/ctx.cpp, src/options.cpp, src/options.hpp, src/peer.cpp, src/pipe.cpp, src/pipe.hpp, src/router.cpp, src/server.cpp, src/session_base.cpp, src/session_base.hpp, src/socket_base.cpp, src/stream_engine_base.cpp, src/udp_engine.cpp, src/zmq_draft.h, tests/test_disconnect_msg.cpp
ZMQ_ROUTER_NOTIFY doesn't have a context and doesn't play nice with protocols. with ZMQ_DISCONNECT_MSG we can set it to a protocol message, like DISCONNECT in majordomo. Router will send it when a peer is disconnected. Another advantage of ZMQ_DISCONNECT_MSG is that it also works on inproc.
Together with ZMQ_HEARTBEAT it allows to build very reliable protocols, and much simpler as well.
=> problem: router doesn't know when peer disconnected 

unittests/unittest_poller.cpp
Solution: Add a sleep in the loop. Some versions of
valgrind may hang when spinning on atomic variables.
See e.g. https://bugs.kde.org/show_bug.cgi?id=336435
This may be a solution to https://github.com/zeromq/libzmq/issues/3873
=> Problem: Spinning on atomics can cause hangs

src/socket_poller.cpp
I noticed that an application of mine behaved weirdly when using `-fsanitize=address`, and I traced the problem to an out-of-bounds array index in ZeroMQ.
As far as I can tell, the logic error is that:
- For fd items, the [loop in rebuild()](https://github.com/zeromq/libzmq/blob/d882e807dd3125e8edece749de04ee403b30d2ab/src/socket_poller.cpp#L321) that sets the `pollfd_index` field only sets it for items that have nonzero event mask.
- But the [loop in check_events()](https://github.com/zeromq/libzmq/blob/d882e807dd3125e8edece749de04ee403b30d2ab/src/socket_poller.cpp#L461) accesses the `pollfd_index` field of *all* fd items, even the ones that do *not* have a nonzero event mask!
- For those items, their `pollfd_index` still has the value that it was initialized with in …
=> Problem: out-of-bounds array access in socket_poller::check_events.

.github/workflows/CI.yaml
Solution: move to github actions
Only visual studio 2019 and 2017 are available. I didn't port all the matrix yet.
Anyway, ctest is failing on win32 build:
```
Test project D:/a/libzmq/libzmq/build_libzmq
Start  1: test_ancillaries
1/75 Test  #1: test_ancillaries .................Exit code 0xc000007b
***Exception:   0.16 sec
```
@sigiesec any idea?
=> problem: appveyor is very slow

Makefile.am, configure.ac, tests/CMakeLists.txt, tests/test_bind_curve_fuzzer.cpp, tests/test_bind_fuzzer.cpp, tests/test_bind_null_fuzzer.cpp, tests/test_connect_curve_fuzzer.cpp, tests/test_connect_fuzzer.cpp, tests/test_connect_null_fuzzer.cpp, tests/test_heartbeats.cpp, tests/test_mock_pub_sub.cpp, tests/test_security_curve.cpp, tests/test_security_gssapi.cpp, tests/test_security_null.cpp, tests/test_security_plain.cpp, tests/test_shutdown_stress_tipc.cpp, tests/test_socks.cpp, tests/test_stream_exceeds_buffer.cpp, tests/test_use_fd.cpp, tests/test_z85_decode_fuzzer.cpp, tests/testutil.cpp, tests/testutil.hpp, tests/testutil_unity.cpp, tests/testutil_unity.hpp
Solution: add some tests that can run as part of the test-suite with trivial input so that they don't break, and that can be built standalone with a fuzzing engine with a specific configure option, that can be used by oss-fuzz.
Partially fixes https://github.com/zeromq/libzmq/issues/3867
=> Problem: no fuzz testing

src/socket_poller.hpp
Solution: simply use zmq_poller_event_t
=> Problem: unnecessary event struct and UB

tests/test_hello_msg.cpp
Solution: use the common wildcard bind pattern instead
=> Problem: test_hello_msg binds to hard-coded port and fails when it's in use

ci_deploy.sh, packaging/obs/_service
Solution: now that tar_scm supports @PARENT_TAG@ as a revision to
automatically fetch the most recent tag on the default branch, use
it to simplify everything
https://github.com/openSUSE/obs-service-tar_scm/pull/359
=> Problem: release script for OBS build fails often

builds/abi-compliance-checker/ci_build.sh
Solution: clone latest tag instead
=> Problem: removing latest_branch breaks ABI CI job

src/generic_mtrie_impl.hpp
Solution: wrap generic_mtrie_t in zmq namespace
Fixes #3917
=> Problem: build fails with Clang 10

CMakeLists.txt, RELICENSE/serg06.md
This prevents a bug where:
- Parent has a `sources` variable
- Parent does `add_subdirectory("libzmq")`
- LibZMQ does `list(APPEND sources ...)` and proceeds to use that list even though it has some of the parent's value inside of it
=> Initialize some CMake variables as empty before build

CMakeLists.txt
I include libzmq in my cmake project, and I don't want clang-related targets popping up in Visual Studio's solution explorer.
=> Make including Clang optional

src/ip.cpp
Solution: Incorrect operator used. Correct the operator.
=> Problem: The code is wrong, socket option is never set.

tests/test_bind_fuzzer.cpp
Solution: move to /tmp before running the test
=> Problem: test_bind_fuzzer clobbers working directory with random socket files

doc/zmq_setsockopt.txt
Solution: use more descriptive, accurate and welcoming terms like allowing
and blocking
https://www.ietf.org/archive/id/draft-knodel-terminology-01.txt
=> Problem: documentation uses unfriendly language

doc/zmq_socket.txt
Solution: change it to categorically state that non-thread-safe
sockets are not thread safe, ever
=> Problem: thread safety documentation is misleading

src/session_base.cpp, src/stream_connecter_base.cpp, src/vmci_connecter.cpp
If ZMQ_RECONNECT_IVL is set to 0, any reconnection attempt will crash with a FPE:
```
[btorpey@bt-brix test]$ file core.17653
core.17653: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from './listenTest -quiet', real uid: 8177, effective uid: 8177, real gid: 8177, effective gid: 8177, execfn: './listenTest', platform: 'x86_64'
[btorpey@bt-brix test]$ gdb listenTest core.17653
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as …
```
=> resolve FPE when ZMQ_RECONNECT_IVL == 0

packaging/debian/changelog, packaging/debian/zeromq.dsc.obs
Solution: change the version format to non-native as a hack, to match
OBS' debstransform usage of 1.0 format
=> Problems: OBS build on sid fails, test_req_relaxed occasionally fails

doc/zmq_poller.txt
Fixed three things:
1. Moved asterisks by variable names into the single quotes (to match [zmq_poll](https://github.com/zeromq/libzmq/edit/master/doc/zmq_init.txt) and other pages.)
2. Fixed variable name in example.
3. Fixed extra & in example.
=> Fix zmq_poller.txt

tests/test_req_relaxed.cpp
Solution: instead of relying on timing to get the order
of connected rep sockets just right, wait for each connection
=> Problem: test_req_relaxed occasionally fails

src/condition_variable.hpp
Solution: fix rounding error and assert if the clock_gettime fails
=> problem: pthread_cond_timedwait sometimes fail with EINVAL

src/session_base.cpp
Solution: check if a session's _pipe has been allocated before using
it, since as a consequence of creating the pipes after the handshake
it's no longer guaranteed to be there.
Fixes #3971
=> Problem: test_security_zap occasionally segfaults

configure.ac
This flag has been enabled for Darwin targets since the initial commit
in [4ed70a930202b103e7e80b8dc925e0aaa4622595](https://github.com/zeromq/libzmq/commit/4ed70a930202b103e7e80b8dc925e0aaa4622595). However, aside from the
fact that we likely no longer want to suppress uninitialized warnings,
this flag wont suppress them anyways, as it's included in the
CXX flags before -Wall (which enables -Wuninitialized). i.e:
```bash
g++ -std=gnu++11 ... -Wno-uninitialized ... -Wall <rest of flags>
```
=> build: don't compile with -Wno-uninitialized on darwin

configure.ac
Some compilers, like GCC, will only warn about unknown -Wno-* options when other warnings are being thrown, i.e:
```bash
CXX      src/libzmq_la-address.lo
src/address.cpp: In function 'zmq::zmq_socklen_t zmq::get_socket_address(zmq::fd_t, zmq::socket_end_t, sockaddr_storage*)':
src/address.cpp:137:9: warning: unused variable 'unused' [-Wunused-variable]
137 |     int unused;
|         ^~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-tautological-constant-compare' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
CXX      src/libzmq_la-channel.lo
```
They will also seem to accept the -Wno-* variant when it's tested for
using …
=> build: test for warning options before enabling -Wno-* variant

configure.ac
Master doesn't currently compile when cross-compiling using autotools and mingw-w64. i.e:
```bash
./autogen.sh
./configure --host=x86_64-w64-mingw32
make src/libzmq.la
....
CXX      src/libzmq_la-curve_server.lo
In file included from src/address.cpp:37:
src/ipc_address.hpp:40:10: fatal error: sys/socket.h: No such file or directory
40 | #include <sys/socket.h>
|          ^~~~~~~~~~~~~~
compilation terminated.
```
I assume this hasn't been caught because appveyor is using CMake, and  has been the case since #3717.
Mingw also does not have an `afunix.h` header. There is a thread upstream, but there doesn't seem to have been any discussion: https://sourceforge.net/p/mingw-w64/discussion/723797/thread/4c8ecdbe0d/.
=> build: disable IPC when cross-compiling with mingw

CMakeLists.txt
This looks like a typo introduced by 2d8ef84760b673d90db331e077fac369665cdbbd.
=> build: fix gethrtime() function check in CMake

configure.ac
Using `-Werror` has been disabled for Darwin since very early on in the
codebase. However at this point, I can't see an obvious reason why it
should still be disabled compared to when building for the other
operating systems. Unless this was specifically for cross-compiling?
I've tested compiling on macOS using Apple Clang 11.0.3, LLVM Clang
10.0.0 and GCC 10.1.
=> build: compile with -Werror by default on Darwin

RELICENSE/tarmo.md, src/xpub.cpp
Solution: always unmatch all pipes before matching for an initial message part.
When using non-blocking and non-lossy (ZMQ_XPUB_NODROP enabled) sends with XPUB, if at least one pipe is full due to HWM, causes `xsend` to return EAGAIN while keeping the pipes matched. This means if another send is made to a different subscription the previously matched pipes remain matched although they might not have any relationship to the later subscription.
There are two issues with this behaviour:
1. the previously matched pipes might not be subscribed to the later message and thus should not receive it (though the sub socket would filter it after it's been transferred)
2. if the previously matched pipes that hit HWM are still full the send to an unrelated subscription will also block regardless of how …
=> Problem: XPUB keeps matched pipes between failed non-blocking sends

Dockerfile, RELICENSE/kaczmarj.md
The Dockerfile for this project has not been updated in several years, so I tried to improve it in this PR. This PR updates the Dockerfile to use multiple stages. In the first stage, compile-time dependencies are installed, and libzmq is compiled and tested. The second stage starts with a fresh, slim Docker image, and the compiled outputs of the first stage are copied over. Runtime dependencies, like libsodium and kerberos, are installed as well. The resulting Docker image is 28% the size of the original image.
=> make Docker image smaller + use `debian:buster-slim` base

RELICENSE/kalantar.md, src/clock.cpp
[why]
In order to compile ZMQ related software on WINDOWS ARM
[how]
Replaced code in the file clock.cpp around the line 240.
Added intrinsics for ARM to replace '__rdtsc'
[todo]
Find proper tick counter query for ARM64 (see file:clock.cpp,line:~250)
=> Modifications to compile code for WINDOWS ARM and ARM64

src/clock.cpp, src/ws_decoder.cpp
Solution: check for it before reusing it to avoid overflows
@somdoron not sure where the handshake buffer gets passed along, but the pointers match
=> Problem: WS might use handshake buffer for data

configure.ac
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix build with openpgm-5-3-128

src/zmq.cpp, tests/test_ctx_options.cpp
Solution: restore EINVAL as errno on unknown option.
Broken by https://github.com/zeromq/libzmq/pull/3642 which started to
return EFAULT instead
=> Problem: zmq_ctx_get API broken

RELICENSE/C-Sir.md, doc/zmq_setsockopt.txt, include/zmq.h, src/ipc_connecter.cpp, src/socket_base.cpp, src/socket_base.hpp, src/zmq_draft.h
When the server does not exist(Never started), the client is disconnected after the request receive timeout,
but the client socket is still reconnecting in the background.
expected result:
the client socket stop reconnect after called zmq_disconnect().
so,I add a disconnect flag for mark disconnect action,
if user set option ZMQ_RECONNECT_STOP:ZMQ_RECONNECT_STOP_AFTER_DISCONNECT for socket,
it will stop reconnet if disconnect flag is true.
=> stop reconnect after called zmq_disconnect()

src/thread.cpp
in our project we have to use VS2010 Win64 compiler and we have fixed the stack overflow by using this suggestion:
https://github.com/zeromq/libzmq/issues/2876#issuecomment-601434808
=> fix stack overflow on windows x64

CMakeLists.txt, configure.ac, src/compat.hpp
Don't include bsd/string.h if strlcpy is also defined in string.h to avoid the following build failure on uclibc:
```
In file included from src/compat.hpp:41:0,
from src/ipc_address.cpp:31:
/tmp/instance-0/output-1/host/mips64el-buildroot-linux-uclibc/sysroot/usr/include/bsd/string.h:44:54: error: declaration of 'size_t strlcpy(char*, const char*, size_t)' has a different exception specifier
size_t strlcpy(char *dst, const char *src, size_t siz);
^
In file included from src/compat.hpp:34:0,
from src/ipc_address.cpp:31:
/tmp/instance-0/output-1/host/mips64el-buildroot-linux-uclibc/sysroot/usr/include/string.h:424:15: error: from previous declaration 'size_t strlcpy(char*, const char*, size_t) throw ()'
extern size_t strlcpy(char *__restrict dst, const char *__restrict src,
^
```
Fixes:
- …
=> src/compat.hpp: fix build with libbsd and strlcpy

RELICENSE/zoedberg.md, autogen.sh
this PR contains a small fix to `autogen.sh`
before this fix the logged autoreconf exit status (`echo "autogen.sh: error: autoreconf exited with status $?" 1>&2`) was always equal to `0`, because it referred to the exit code of the `if` espression (`if [ $? -ne 0 ];`)
=> autogen.sh: fix autoreconf exit code log

.github/workflows/CI.yaml, tests/test_req_correlate.cpp, tests/test_req_relaxed.cpp, tests/test_spec_dealer.cpp, tests/test_spec_pushpull.cpp, tests/test_spec_rep.cpp, tests/test_spec_req.cpp, tests/test_spec_router.cpp
Solution: remove arbitrary timeouts, as they are testing reliable pipes
with no contention, so if it can connect eventually it has to
work. The overall test timeout covers cases where it doesn't.
If tests want to use receive timeouts, they need to handle EAGAIN
properly.
=> Problem: tests fails to receive with EAGAIN on slow architectures

builds/android/android_build_helper.sh
Solution: Update the android build helper to locate readelf binary included in android ndk.
As the `project.xml` was not part of the repository `android_build_helper.sh` was manually updated to resolve the issue being faced.
=> Problem: Android build fails.

RELICENSE/zedalaye.md, src/ip.cpp
Avoid filling Temp directory with temporary files.
=> Cleanup socket FD after pair is established. Fix #4086

src/stream_engine_base.cpp
Solution: fix refactor mistake introduced by:
091df743a81f3899bd70166060c2082ea0cbd57c
Fixes https://github.com/zeromq/libzmq/issues/4113
=> Problem: build broken on kFreeBSD

src/stream_engine_base.cpp
Solution: fix refactor mistake introduced by:
091df743a81f3899bd70166060c2082ea0cbd57c
Fixes https://github.com/zeromq/libzmq/issues/4113
=> Problem: build still broken on kFreeBSD

.travis.yml, RELICENSE/MartinGrigorov.md
More and more software development is being done on ARM64 CPU architecture.
It would be good if libzmq is being regularly tested on ARM64!
Adds an extra TravisCI job that runs `ci_build.sh` on arm64/aarch64 CPU architecture.
There is one test failure on ARM64:
```
FAIL: tests/test_monitor
========================
WARNING: Forced closure of 4 sockets, this is an implementation error unless the test case failed
WARNING: Forced closure of 6 sockets, this is an implementation error unless the test case failed
../../tests/test_monitor.cpp:444:test_monitor_invalid_protocol_fails:PASS
../../tests/test_monitor.cpp:445:test_monitor_basic:PASS
../../tests/test_monitor.cpp:450:test_monitor_versioned_invalid_socket_type:PASS
../../tests/test_monitor.cpp:451:test_monitor_versioned_basic_tcp_ipv4:PASS …
```
=> Build and test on ARM64 CPU architecture (#1)

RELICENSE/c-zhao-3g.md, src/thread.cpp
Problem: exception thrown when debugging cl.exe x64 build with LLDB
Solution: Use __try __except with cl.exe anduse pthread_setname_np with MinGW.
Remove usage of pushing exception handler to TIB->ExceptionList.
=> Problem: exception thrown when debugging cl.exe x64 build with LLDB

src/dist.cpp, src/dist.hpp, src/xpub.cpp
Solution: Avoid setting pipe as _last_pipe if it has been terminated
When using XPUB with manual subscriptions the scheme is to:
1. read one subscription notification from the socket at a time
2. and then call an arbitrary number of `zmq_setsockopt` with `ZMQ_SUBSCRIBE` to add subscriptions for the pipe from which the most recent subscription notification (or other message) was read by the application. This works because the socket remembers the `_last_pipe` it read a message from and uses that as a target for adding subscriptions.
A serious problem however appears if the pipe has been terminated before the application has had a chance to read and process the messages associated with that pipe.
If the application reads a pending message from a pipe that has already been terminated, and …
=> Problem: XPUB socket allows manual subscription on terminated pipe

RELICENSE/jlsantiago0.md, acinclude.m4
getconf LEVEL1_DCACHE_LINESIZE reports 'undefined' on Fedora33 s390x. This pull request fixes the build on that platform.
=> Fix Fedora33 s390x build.

.clang-tidy
a couple of problems:
- missing comma on comment line hides following line
- misspelled suppression for "-fuchsia-default-arguments-calls"
=> fix formatting problems in .clang-tidy options

.clang-tidy
As a followup to https://github.com/zeromq/libzmq/pull/4155, these addl. suppressions reduce the noise level with clang-tidy-10 on ubuntu.  Two duplicate existing suppressions that have been rendered ineffective with new rules in clang-tidy.
=> add more suppressions

tests/testutil.hpp
There is a macro that redefines close to closesocket, but then close is
later defined in unistd.h which is included in testutil_unity.cpp which
then causes the regular close() prototype to be defined with the new
function name closesocket which does not match the signature of the
original closesocket in winsock2.h from the toolchain.
We can work around this issue, by making sure that unistd.h is included
before the macro is defined. HMM> Yes macro substitution is the root of
evil.
=> MINGW Build Fix.

src/mutex.hpp
ZeroMQ works with MINGW and pthread conditional variables if pthread
mutexes are used. POSIX conditional variables require POSIX mutexes, but
ZeroMQ unconditionally uses WIN32 critital sections even when configured
with pthread conditional variables. This of course does not work. This
patch fixes the build so that MINGW builds do not use WIN32 critical
sections and instead use POSIX mutexes when configured with pthread
conditional variables.
Tested with:
```
CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ ../libzmq/configure --host=x86_64-w64-mingw32 --prefix=`pwd`/stage --enable-debug --disable-Werror --enable-libunwind=no   --with-cv-impl=pthread --enable-libbsd=no
```
```
x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 10.2.0.....
```
=> Fix MINGW with pthread cv

include/zmq.h, src/zmq_draft.h
(i.e., can be OR'ed together),  and so values must be powers of two
=> ZMQ_RECONNECT_STOP options are intended to be inclusive

src/clock.cpp
Fixes compilation as -Werror is passed.
=> fix unused variables under windows

RELICENSE/yitzchak.md, doc/zmq_poll.txt
The documentation for `zmq_pollitem_t` lists the type of the `fd` field as `int` but it changed to `zmq_fd_t` in v4.3.2
Please note that the documentation for previous versions is also incorrect in that it lists the type as `int` when it was `SOCKET` on Windows and `int` elsewhere. Is the documentation for previous releases corrected for errors?
=> Update fd slot type to zmq_fd_t

appveyor.yml
now that bintray is gone.
Should address #4191 after the windows files are uploaded. This can be done by either making and pushing a 4.3.4.post0 tag to this repo, or manually copying the files from [my test run of this pr](https://github.com/minrk/libzmq/releases/tag/v4.3.4.post0) to the existing [4.3.4 release](https://github.com/zeromq/libzmq/releases/tag/v4.3.4). The only thing not tested is the upload credentials, which is the only difference between what ran on my fork and this pr.
=> [appveyor] upload windows artifacts to GitHub releases

include/zmq.h
These are redundant with the ones in windows.hpp and aren't needed for the public interface.
Since 4.3.3 zmq.h no longer includes windows.h and so these defines have no effect on zmq besides potentially interfering with what the user is doing.
Built on Windows VS 16.9.6, all tests passed.
=> Remove Windows-specific defines from zmq.h.

Makefile.am, doc/zmq_setsockopt.txt, include/zmq.h, src/client.cpp, src/dealer.cpp, src/options.cpp, src/options.hpp, src/pipe.cpp, src/pipe.hpp, src/session_base.cpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_hiccup_msg.cpp
This is important in order to send the login sequence of a client to the server.
Solution: add ZMQ_HICCUP_MSG to a socket, socket would send that message whenever a connection get temporarly disconnected
=> problem: no way to know when connection is temporarly dropped

src/curve_client_tools.hpp
Solution: ignore false positives due to compiler bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578
Fixes https://github.com/zeromq/libzmq/issues/4206
=> Problem: build with curve fails on GCC 11

tests/test_inproc_connect.cpp
Solution: actually send a message rather than just opening/closing
the sockets, as connecting is asynchronous.
tests/test_inproc_connect.cpp:341:test_bind_before_connect:PASS
tests/test_inproc_connect.cpp:342:test_connect_before_bind:PASS
tests/test_inproc_connect.cpp:343:test_connect_before_bind_pub_sub:PASS
tests/test_inproc_connect.cpp:344:test_connect_before_bind_ctx_term:PASS
tests/test_inproc_connect.cpp:345:test_multiple_connects:PASS
tests/test_inproc_connect.cpp:346:test_multiple_threads:PASS
Assertion failed: _state == active || _state == waiting_for_delimiter (src/pipe.cpp:504)
0  0xffffa015d3e4 in /usr/src/packages/BUILD/src/.libs/libzmq.so.5 (zmq::zmq_abort(char const*)+0xc)
1  0xffffa017b208 in /usr/src/packages/BUILD/src/.libs/libzmq.so.5 …
=> Problem: test_inproc_connect occasionally fails on slow archs

RELICENSE/NLeScienceCenter.md, src/polling_util.hpp
When the build is performed with cmake option `-DPOLLER=select`, the following warning is triggered from 4 locations that import `polling_util.hpp`:
```
[...]/src/polling_util.hpp:115:50: warning: unused parameter 'pollset_' [-Wunused-parameter]
inline size_t valid_pollset_bytes (const fd_set &pollset_)
^
1 warning generated.
```
This is fixed here.
=> fix unused parameter warning when POLL_BASED_ON_SELECT

RELICENSE/sabotagebeats.md, src/clock.cpp
`unused variable 'nsecs_per_usec'`
https://github.com/zeromq/libzmq/issues/4231
=> fix: building libzmq fails with error src/clock.cpp

RELICENSE/saschavv.md, src/ip.cpp
Closes #4201 The create_ipc_wildcard_address can return a string that is inappropriate for the bind call that follows.
The bind requires an utf8 string and the create_ipc_wildcard_address with tmpnam_s that returns a string based on the oem code pages. The fix uses the wide character alternatives and uses a to utf8 conversion routing to fix the bind problem.
=> Fix crash in context with wide characters in path

CMakeLists.txt, configure.ac, src/random.cpp
**Problem:** When using libsodium, calling `zmq::random_close()` closes a shared resources that may still be in use.
See #4241 for details and repro, but this is called unconditionally on every `curve_keypair()` and every context destructor, since #3001. Closing any context and/or issuing a new curve keypair can crash another context if it is working with curve-enabled sockets at the time, as it is still a consumer of a now-closed resource. libsodium will try to reinitialize the source, so it doesn't crash every time; instead, certain race conditions must be met to result in a crash.
**Solution:** Do not close this shared resource while it is still in use, as suggested by the libsodium [documentation](https://doc.libsodium.org/generating_random_data#usage).
For implementations using …
=> Problem: calling randombytes_close with libsodium can crash Contexts in other threads

RELICENSE/analogist.md, tests/testutil.cpp
Fixes ~2~ 1 build issue~s~ under mingw-w64 and `ZMQ_HAVE_WINDOWS` in general:
winsock `socket()` calls return an `fd_t` / `handle_t` that is uint64_t for 64-bit systems and uint32_t for 32-bit systems, which throws `-Werror=sign-compare` when compared against -1 in test:
> ```
>   CXX      tests/libtestutil_a-testutil.o
> In file included from ./external/unity/unity.h:16,
>                  from tests/testutil_unity.hpp:36,
>                  from tests/testutil.cpp:30:
> tests/testutil.cpp: In function 'fd_t connect_socket(const char*, int, int)':
> ./external/unity/unity.h:134:130: error: comparison of integer expressions of different signedness: 'int' and 'const fd_t' {aka 'const long long unsigned int'} [-Werror=sign-compare]
>   134 | #define TEST_ASSERT_NOT_EQUAL(expected, actual) …
```
=> mingw-w64 10.3 build fix - winsock socket() return unsigned

Makefile.am, RELICENSE/PaulThiele.md, doc/zmq_setsockopt.txt, include/zmq.h, src/xsub.cpp, src/xsub.hpp, src/zmq_draft.h, tests/CMakeLists.txt, tests/test_xsub_verbose.cpp
consider the following case:
all XPUB sockets have `ZMQ_XPUB_VERBOSER = true`
```
:                                                   /--> SUB :
App     : XPUB ---> XSUB/proxy/XPUB ---> XSUB/proxy/XPUB -->+--> SUB :    App
:                                                   \--> SUB :
<-sub   :     <-sub      <-sub     <-sub      <-sub       <-sub      : 
<-sub   :     <-sub      <-sub     <-sub      <-sub       <-sub      : 
<-sub   :     <-sub      <-sub     <-sub      <-sub       <-sub      : 
:                                    <-unsub     <-unsub     : 
:                                    <-unsub     <-unsub     : 
:               <-unsub   <-unsub    <-unsub     <-unsub     : 
```
Problem: the app never receives a unsubscribe message and thus keeps sending although all subscribers …
=> Problem: if ZMQ_XPUB_VERBOSER is used with proxies unsubscribe messages are lost

RELICENSE/niyassait.md, src/clock.cpp
This patch removes a temporary workaround to get the cycle count on windows on arm64 devices. Many of the unit tests were failing and with this patch, all the tests are passing now.
=> Get cycle count from ARM64 PMCCNTR_EL0 register

RELICENSE/hewlett_packard_enterprise.md, configure.ac
Solution: When compiling with gcc 7 and newer, the program produced by
AC_CHECK_FUNCS(fork) produces a warning, which results in configure
incorrectly disabling fork support. Fix the issue by using an
AC_COMPILE_IFELSE which correctly detects fork availability.
Tested by running configure and make check on a system with gcc 7
installed, and verifying that HAVE_FORK was defined correctly.
See issue #3313.
=> Problem: Fix fork detection on gcc 7

src/windows.hpp
The definition of sockaddr_un should be protected by the include guard to avoid redefinition.
Reported here: https://github.com/microsoft/vcpkg/issues/21623#issuecomment-978144984
=> Problem: struct sockaddr_un redefinition

RELICENSE/patrickvolante.md, src/epoll.cpp
Problem inside the event array, epoll return an event with invalid data pointer which create a segmentation fault.
Tests to prevent segmentation fault due to null pointer are added.
=> Issue 4312 : Fix epoll invalid event data pointer

src/router.cpp, tests/test_metadata.cpp
Solution: copy metadata on prefetch to the first frame.
=> Problem: ROUTER loses first frame metadata on message prefetch

CMakeLists.txt, RELICENSE/boscosiu.md, builds/cmake/platform.hpp.in
Solution: Add the definition to the relevant CMake targets in public scope.  Fixes #4194
=> Problem: ZMQ_BUILD_DRAFT_API define is not propagated to dependent CMake projects

configure.ac, src/kqueue.cpp
solution: check for the `intptr_t` variant in configure.
Building libzmq master (ee09926cbd089cec780896cf7aa65f8bfd4b1b86) on NETBSD Current fails with:
```bash
gmake[1]: Entering directory '/home/ec2-user/libzmq'
CXX      src/libzmq_la-kqueue.lo
In file included from /usr/include/errno.h:42,
from src/../include/zmq.h:56,
from src/precompiled.hpp:57,
from src/kqueue.cpp:30:
src/kqueue.cpp: In member function 'void zmq::kqueue_t::kevent_add(zmq::fd_t, short int, void*)':
src/kqueue.cpp:79:5: error: invalid 'static_cast' from type 'intptr_t' {aka 'long int'} to type 'void*'
79 |     EV_SET (&ev, fd_, filter_, EV_ADD, 0, 0, (kevent_udata_t) udata_);
|     ^~~~~~
gmake[1]: *** [Makefile:5652: src/libzmq_la-kqueue.lo] Error 1
```
As of …
=> problem: kevent udata is now void* on NetBSD Current (10)

RELICENSE/Jasper-Bekkers.md, src/precompiled.hpp
This fails when compiling x86_64-pc-windows-msvc targets on a case sensitive file system.
=> Fix minor casing issue in include files

builds/android/android_build_helper.sh, builds/android/build.sh
This reverts commit 9c6f09cbe551e08782b67fae367b56dc69f656f7.
=> Revert "Problem: Libs crash at runtime on Android when built with NDK 23+

RELICENSE/abaelhe
Permission to Relicense under MPLv2 or any other OSI approved license chosen by the current ZeroMQ BDFL
By Abael He<abaelhe@icloud.com>
=> Permission to Relicense under relevant approved license

RELICENSE/nevalsar.md, doc/zmq_udp.txt
Solution: Replace incorrect underline pattern in zmq_udp.txt that
makes part of the text show up as pre-formatted code block with
regular underline pattern.
http://api.zeromq.org/master:zmq-udp
=> Problem: Incorrect formatting of documentation in zmq_udp.txt

RELICENSE/tongsong-cai.md, src/ctx.cpp
Solution: use scoped lock to prevent them from being modified during reading
=> Problem: get_opt function read the options value not thread safe

src/secure_allocator.hpp
Build all projects
```
** BUILD SUCCEEDED **
bash-3.2# cd  bin/Debug/
bash-3.2# for x in ./* ; do ./$x 1> /dev/null 2>/dev/null  || echo $x ; done
./test_bind_curve_fuzzer
./test_bind_fuzzer
./test_bind_null_fuzzer
./test_connect_curve_fuzzer
./test_connect_fuzzer
./test_connect_null_fuzzer
Segmentation fault: 11
./test_security_curve
./test_z85_decode_fuzzer
bash-3.2# ./test_bind_curve_fuzzer
bash-3.2# ./test_bind_curve_fuzzer
bash-3.2# ./test_bind_fuzzer 
bash-3.2# ./test_bind_null_fuzzer 
bash-3.2# ./test_connect_curve_fuzzer 
bash-3.2# ./test_connect_fuzzer 
bash-3.2# ./test_security_curve 
Segmentation fault: 11
bash-3.2# lldb ./test_security_curve 
(lldb) target create "./test_security_curve"
Current executable set to '/Users/abaelhe/Downloads/libzmq-master/build/bin/Debug/test_secur …
```
=> secure release memory to avoid free null pointer

src/ip.cpp, src/norm_engine.cpp
closes #4386
Following discussion in #4386, this is a more specific check [requested](https://github.com/zeromq/libzmq/pull/4386#issuecomment-1132078805) by @bluca rather than a catch-all. Only failures up to the initial bind are considered for fallback to tcpip.
I can't reproduce the error, so I don't know exactly what errno to check for to make the condition even more specific.
Also adds the missing check of the returned rc from make_fd_pair, which should have raised the actual error instead of the cryptic `src\epoll.cpp:100` reported in https://github.com/zeromq/pyzmq/issues/1505
=> Problem: bind can fail after open_socket succeeds on Windows without AF_UNIX

README.md
`libzmq` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `libzmq` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `libzmq`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/zeromq/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)
=> [document] add vcpkg instruction

builds/android/build.sh, builds/cmake/ci_build.sh, builds/valgrind/ci_build.sh, config.sh
How to reproduce:
```
prompt> git clone libzmq
prompt> cd libzmq/builds/android
prompt> export CURVE=libsodium
prompt> ./ci_build.sh
Cloning into 'libsodium'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
Cloning into 'libsodium'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
Cloning into 'libsodium'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
Cloning into 'libsodium'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
prompt>
```
Reason: Invalid URL to download libsodium:
```
prompt> grep -s 'git clone' libzmq/builds/android/*.sh
libzmq/builds/android/build.sh:70:        (cd "${cache}" …
```
=> Problem: builds/android/build.sh fails with CURVE=libsodium

builds/android/README.md, builds/android/android_build_helper.sh, builds/android/build.sh, builds/android/ci_build.sh
Solution: Set NDK r25 as the default. No compatiblity changes required.
=> Problem: Default Android NDK version is not aligned with zproject

tests/test_spec_req.cpp
We're trying to automate running the unit tests, but an intermittent timeout error in `test_spec_req` is causing problems.  This is particularly troublesome when running the tests under sanitizers (e.g., ASAN).
```
Start  32: test_spec_req
32/117 Test  #32: test_spec_req ....................***Timeout  10.01 sec
```
Running the test stand-alone is not much more informative:
```
[btorpey@bt-brix7 master]$ ./build/bin/test_spec_req
/home/btorpey/work/libzmq/master/src/tests/test_spec_req.cpp:230:test_round_robin_out_inproc:PASS
Alarm clock
[btorpey@bt-brix7 master]$
```
OTOH, the test succeeds when run under gdb.
In any case, the patch below appears to eliminate the timeout by multiplying `SETTLE_TIME` by the number of peers.
=> avoid intermittent timeouts in test (esp. when run w/ASAN etc.)

builds/android/android_build_helper.sh
Seen in the code:
```
function android_build_verify_so {
...
for dep_soname do
if [[ $elfoutput != *"library: [${dep_soname}]"* ]]; then
ANDROID_BUILD_FAIL+=("Library ${soname} was expected to be linked to library with soname:")
ANDROID_BUILD_FAIL+=("  ${dep_soname}")
fi
done
```
The `for xxx` syntax is wrong, most probably a typo somewhere.
Solution: Fix & complete the `for xxx` loop.
Tested with & without LIBSODIUM (only available dependent library for LIBZMQ).
Note: The same has to be done in ZPROJECT, for CZMQ & ZYRE.
=> Problem: Android helpers no not validate dependent libraries.

builds/android/build.sh, builds/android/ci_build.sh
Solution: Use `set -e`
Note:
To be reported in ZPROJECT, when generating the same scripts.
Note:
`make clean` may fail when Makefile is not yet generated (case of 1st call of build.sh after git clone).
Additionnaly, cleaned the dependency folder
(report of CZMQ & ZYRE similar scripts).
=> Problem: Android build script may fail silently

builds/android/android_build_helper.sh, builds/android/build.sh
With the help of the dump of ./configure options (former PR):
```
LIBZMQ (arm) - ./configure options to build 'LIBZMQ':
> --quiet
> TOOLCHAIN=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
> CC=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
> CXX=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++
> LD=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/ld
> AS=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as
> AR=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
> RANLIB=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
> STRIP=/tmp/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
> …
```
=> Problem: Android APP fails to load ZMQ since NDK r25.x

builds/android/build.sh, builds/android/ci_build.sh
Cleanup:
Seen when someone has to relaunch `ci_build.sh` manually, for troubleshooting, or experiment(s), ci_build.sh stops as libraries are already built.
Solution: Clean more temporary/build folders before build.
Note:
To be reported in ZYRE/CZMQ via ZProject.
Traces:
When called from ZYRE/CZMQ, it's difficult to identify which build script is being executed
Solution: Modify each `echo` trace to show the project name and Android architecture in progress.
Note:
To be reported in ZYRE/CZMQ via ZProject.
=> Problem: Android CI build scripts need minor enhancements (traces & cleanup)

builds/android/build.sh
Scenario:
```
export CURL=libsodium
cd zyre/builds/android
./ci_build.sh
```
Result:
```
Android (arm) build failed for the following reasons:
Found no library named libzmq.so libsodium.so
/home/stephan/git/zproject-android-testing/libzmq/builds/android/prefix/arm/lib/libzmq.so libsodium.so
```
Caused by PR #4437, where the 2nd commit was to fix Sonatype findings.
Lesson learnt: Not always a good idea to add double quotes around variables ...
Solution: Make VERIFY an array, so that Sonatype won't complain.
=> Regression: Android build fails with libsodium.

builds/android/android_build_helper.sh
Seen with physical Android devices running ARM64.
Not seen with ARM, X86 or X86_64.
Any Android APP loading ZMQ fails with:
```
[FATAL] Couldn't load library library zmq from jar. Dependency is required!
```
Unpack zyre-android-2.0.1.jar, find libzmq.so for ARM64 and look for missing symbols:
```
prompt> unzip zyre-android-2.0.1.jar
prompt> cd lib/arm64-v8a
prompt> nm --undefined-only ./libzmq.so | head
U __aarch64_ldadd4_acq
U __aarch64_ldadd4_acq_rel
U __aarch64_ldadd4_rel
U __aarch64_ldadd4_relax
U __aarch64_ldadd8_acq_rel
U __aarch64_ldadd8_relax
U __aarch64_swp8_acq
U __aarch64_swp8_acq_rel
U __aarch64_swp8_rel
U __aarch64_swp8_relax
prompt>
```
Some more symbols are missing, but those are relevant for this issue.
OK.
These symbols are present in libc++_shared, but not exported ...: …
=> Problem: Android APP fails to load ZMQ (ARM64 only)

builds/android/android_build_helper.sh, builds/android/build.sh, builds/android/ci_build.sh
Reason: All are spread and initialized throughout the code.
Solution: Declare, initialize and document environment variables on top of build.sh.
Benefit: This participates to documentation.
=> Problem: Android build environment variables need clarifications.

builds/android/android_build_helper.sh, builds/android/build.sh, builds/android/ci_build.sh
Due to the PR to support NDK 23.
With NDK 23, the archive file name has changed.
This change is handled by the PR to support NDK23, but now, only 23 and after
are supported.
Also, NDK 23 support introduced a 2nd occurence of the variable
HOST_PLATFORM, with another value. One occurence being exported,
this may confuse next developpers (and it actually confused me).
Solution: Code review
1st occurence is simply dropped, and the algorithm around is changed so that
there is no need of a 'host_platform' kind of stuff.
2nd occurrence is renamed to ANDROID_BUILD_PLATFORM.
Note that 'HOST' is replaced by 'BUILD', as this is the common naming
when talking about the build/compilation machine, when cross compiling.
A dedicated function is created in the helpers, to actually download
the NDK. As …
=> Problem: Android NDK 22 download broken since support of NDK 23.

builds/android/android_build_helper.sh, builds/android/build.sh
Solution: Add a trace function.
Requires to move the CI build helper code/check/init/... at the end of helper file.
This new function is available for (and also used by) build.sh. Output is like:
LIBZMQ (x86_64) - Blah ...
To be reported to CZMQ/ZYRE via ZProject.
=> Problem: Android CI build helper has no trace function.

builds/android/Dockerfile
Solution: Update Dockerfile.
Added references to tested versions (Ubuntu & Debian)
Added references to tested NDK. 
Carefull though, with NDK: Android have changed there NDK naming, between 22 and 23.
=> Problem: Android docker image is outdated.

builds/android/android_build_helper.sh
Last PRs introduced a duplicate code in Android helper file. Duplicate "Initialisation" sequence can be observed after the helper functions:
########################################################################
...
ANDROID_BUILD_FAIL=()
Seen when trying to report last LIBZMQ Android PRs to CZMQ & ZYRE.
Solution: Remove the duplicate code.
=> Problem: Android helpers have duplicate init code.

src/secure_allocator.hpp
`gcc-13` added an assert to standard headers to make sure custom allocators have intended implementation of rebind type instead of inherited rebind. gcc change:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=64c986b49558a7
Without the fix build fails on this week's `gcc-13` as:
[ 92%] Building CXX object tests/CMakeFiles/test_security_curve.dir/test_security_curve.cpp.o
In file included from /<<NIX>>/gcc-13.0.0/include/c++/13.0.0/ext/alloc_traits.h:34,
from /<<NIX>>/gcc-13.0.0/include/c++/13.0.0/bits/stl_uninitialized.h:64,
from /<<NIX>>/gcc-13.0.0/include/c++/13.0.0/memory:69,
from tests/../src/secure_allocator.hpp:42,
from tests/../src/curve_client_tools.hpp:49,
from tests/test_security_curve.cpp:53:
/<<NIX>>/gcc-13.0.0/include/c++/13.0.0/bits/alloc_traits.h: In instantiation of …
=> src/secure_allocator.hpp: define missing 'rebind' type

RELICENSE/nfware.md, src/socket_base.cpp
Issue caught in Golang runtime, which widely uses signal SIGURG for scheduling. Sometimes messages cannot be received. Technically socket_base_t::process_commands() returns failure even if some commands were processed, but next message from mailbox could not be received during interrupt.
Solution: retry receiving from mailbox with zero timeout after EINTR.
Signed-off-by: Ilya Kondrashkin <ikondrashkin@nfware.com>
=> Problem: message can't be received due to signal

src/tcp_address.cpp, src/udp_engine.cpp, tests/test_inproc_connect.cpp, tests/test_issue_566.cpp, tests/test_proxy.cpp, tests/test_reqrep_tcp.cpp, tests/test_setsockopt.cpp, tests/test_stream_disconnect.cpp, tests/test_unbind_wildcard.cpp, tests/test_ws_transport.cpp, tests/testutil.cpp
Problem: Latest OSX deprecates using sprint resulting is failure to build
Fix by switching to snprint.
As tried by #4481 and fixing #4478
=> deprecate sprint and replace with snprintf

RELICENSE/sergeyfedorov.md, tests/CMakeLists.txt
GCC can be used on macOS, therefore correct condition is on Apple and not on Clang.
(Sure enough, otherwise building with GCC you get a lot of warnings about non-existent folders after -L.)
=> tests: use NOT APPLE instead of NOT MATCHES Clang

RELICENSE/daira.md, src/tcp_address.cpp, src/udp_engine.cpp
If snprintf truncates, it returns the number of characters that would have been written without truncation. Add assertions to cover this case.
See also https://github.com/zeromq/libzmq/pull/4494/files#r1092829210
=> #4494 added calls to snprintf, but did not take into account that snprintf can truncate

src/udp_engine.cpp
Solution: treat bind errors as a protocol_error instead of connection_error preventing an infinite loop of trying to create the udp socket as through the protocol_error the creation of the socket fails and the engine is terminated
Up for discussion, should we preserve the errno var like done with tcp sockets?
https://github.com/zeromq/libzmq/blob/a666cb1b409d059e9f844994fe2d9d7b6b7e8f91/src/tcp_listener.cpp#L165-L169
This fixes #4504
=> Problem: infinite loop binding a dgram socket if it fails

CMakeLists.txt, RELICENSE/chachoi.md, build_qnx/Makefile, build_qnx/common.mk, build_qnx/nto/Makefile, build_qnx/nto/aarch64/Makefile, build_qnx/nto/aarch64/le/Makefile, build_qnx/nto/x86_64/Makefile, build_qnx/nto/x86_64/o/Makefile, build_qnx/qnx.nto.toolchain.cmake, tests/CMakeLists.txt
I added support for QNX 7.1 build.
All QNX build related files are under build_qnx.
Build instructions for QNX 7.1 on Ubuntu:
```bash
source <path-to-qnxsdp-env.sh>/qnxsdp-env.sh
git clone https://github.com/chachoi/libzmq.git && cd libzmq/build_qnx
make -j 4 install
```
=> Add support for QNX 7.1 build

RELICENSE/weston-nrl.md, doc/zmq_getsockopt.txt, doc/zmq_setsockopt.txt, include/zmq.h, src/norm_engine.cpp, src/options.cpp, src/options.hpp, src/zmq_draft.h
NORM transport is currently hard-coded to particular NORM settings and modes.  This pull request adds some NORM configuration parameters as socket options to allow for more flexibility in configuring NORM transport for different use cases.  Default values and modes remain the same.  The pull also makes use of existing socket options ZMQ_RATE (for NORM fixed-rate operation, not used in congestion control modes) and ZMQ_TOS.
=> Add NORM Transport configuration sockopts

CMakeLists.txt, RELICENSE/panicgh.md
The pkg_config_defines variable was only set in configure.ac, but not in CMake. This lead to the `-DZMQ_BUILD_DRAFT_API=1` flag to be omitted from the generated pkg-config file.
configure.ac contains this to set the variable accordingly:
https://github.com/zeromq/libzmq/blob/532b61275e93a8f7e0f2dee4ee1a83f075325926/configure.ac#L1056-L1063
=> Add missing pkg_config_defines when built with CMake

src/norm_engine.cpp
It is unclear to me why the current TTL is hard-coded, but this change makes TTL user-configurable using the existing sockopt to allow for more flexibility.  Effectively changes default NORM TTL from 255 to 1.
=> Change NORM to set TTL using MULTICAST_HOPS sockopt

src/options.cpp, src/options.hpp, src/stream_connecter_base.cpp
Solution: reimplement support for ZMQ_RECONNECT_IVL_MAX without knowledge of the previous code.
=> Problem: relicensing forced to remove support for ZMQ_RECONNECT_IVL_MAX option

doc/zmq_ctx_set.txt, src/thread.cpp
This PR fixes the issue #4512 by checking that the priority set on non-real time threads is strictly positive before doing the `nice` system call. The documentation is updated accordingly.
It also fixes a following remark on errors when a thread is created with the scheduling policy OTHER, but without indicating the priority. The priority must be set to 0, as it cannot inherit the priority of the creator thread if that thread has a real-time priority.
=> Setting ZMQ_THREAD_PRIORITY to 0 shouldn't nice the threads. #4512

src/tcp_address.cpp, src/udp_address.cpp
This PR fixes the needs behind the issue #4514 by enabling fallback to hostname resolution if interface resolution fails.
When resolving addresses, there is already a fallback to getaddrinfo when interface resolution fails.
When allow_dns is set to false, the AI_NUMERICHOST flag is added to getaddrinfo to disable hostname resolution.
The fact we are binding is currently used to disable hostname resolution in TCP and UDP. To enable the fallback to hostname resolution, the allow_dns option should be set to true in all cases.
=> Fallback to hostname resolution in TCP and UDP.

Makefile.am, src/v3_1_encoder.cpp, tests/CMakeLists.txt, tests/test_xpub_topic.cpp
Solution: fix V3.1 encoder to calculate long flag after evaluating the subscribe and cancel commands
Fixes zeromq/libzmq#4367
=> Problem: long flag isn't set for subscriptions if topic has between 246 and 255 characters

src/norm_engine.cpp
Fix assert error that can happen on a late-joining NORM subscriber.  Assert error can happen once publisher has filled its NORM buffer and begun to discard old data it was caching for potential repairs.
=> Fix NORM Assert Error

Jenkinsfile, builds/zos/runtests, version.sh
For the GNU Grep package version >= 3.8, the `egrep` command emits:
```
egrep: warning: egrep is obsolescent; using grep -E
```
which makes the `./autogen.sh` script very noisy.
=> Replace `egrep` with `grep -E`

AUTHORS, Makefile.am, doc/zmq_proxy_steerable.txt, src/proxy.cpp, src/proxy.hpp, src/zmq.cpp, tests/CMakeLists.txt, tests/test_proxy_steerable.cpp
Here is my attempt to provide #4597 
This is my first real dive into the internals of libzmq so there may be some problems that need to be ironed out.
=> A clean room re-implementation of zmq_proxy_steerable()

doc/zmq_proxy_steerable.txt, src/proxy.cpp, tests/test_proxy_steerable.cpp
Continuing Brett's work on zmq_proxy_steerable here: https://github.com/zeromq/libzmq/pull/4598
2 problems addressed (split into 2 commits):
1. PAUSE/RESUME commands were seemingly mixed up and the test didn't cover it.
2. The reimplementation changed behaviour by always replying for the simple commands PAUSE, RESUME, TERMINATE, so ZMQ_PAIR usage would have to change when migrating.
I agree that REP makes the most sense for the control socket type, but prior semantics of the control socket pretty much dictated the use ZMQ_PAIR, so this just restores backwards compatibility.
New test assertions with existing src/proxy.cpp:
```
steer: sending STATISTICS - post-pause                                             
stats: client pkts out: 15 worker pkts out: 32 { 30 345 64 736 64 736 30 345 } …
```
=> Fix zmq_proxy_steerable

tests/test_proxy_steerable.cpp
Problem: test_proxy_steerable flakiness on slow CI VMs
> The test is flacky and fails on slow architectures:
> 
> [ 2361s] FAIL: tests/test_proxy_steerable
> [ 2361s] ================================
> [ 2361s] 
> [ 2361s] tests/test_proxy_steerable.cpp:458:test_proxy_steerable:FAIL: Expression Evaluated To FALSE
> 
> https://build.opensuse.org/build/network:messaging:zeromq:git-stable/Fedora_Rawhide/s390x/libzmq/_log
_Originally posted by @bluca in https://github.com/zeromq/libzmq/issues/4600#issuecomment-1760402811_
Solution: fewer worker threads, poll rather than thrash, consistent timings. user cpu ~300% -> 15%.
=> test_proxy_steerable: reduce cpu and thread count

src/msg.cpp
the init message of vsm size should be <= max_vsm_size include equal size.
=> allow the max_vsm_size of data can init as vsm type msg

Makefile.am, tests/CMakeLists.txt
test_pubsub.cpp was not included anywhere.
=> Add forgotten test_pubsub.

src/poller.hpp
Was `ZMQ_IOTHREAD_POLLER_POLL` but should be `ZMQ_IOTHREAD_POLLER_USE_POLL`
=> poller.hpp: fix incorrect ZMQ_IOTHREAD_POLLER_* usage

doc/Makefile.am, doc/asciidoctor.css
* make unordered lists look at bit more compact to shorten the length of the index page
=> Documentation: improve the look of landing page

src/endpoint.hpp
Removes unused qualifier `const` from function returning a bool.
=> Fix 4629 compile warning in endpoint.hpp

src/ip.cpp, src/ipc_listener.cpp, src/windows.hpp
Problem: Using non-ascii characters in unix domain socket path doesn't work on Windows.
Solution: Convert utf-8 socket paths to utf-16 file names when using filesystem calls to delete files and directories as Windows doesn't have any filesystem calls that take utf-8 path.
rmdir_utf8() and unlink_utf8() static functions were created which substitute rmdir() and unlink() when building on Windows.
Fixes #4641
=> Non-ASCII characters support in ipc:// socket paths

src/pipe.cpp
When socket monitoring is active a segmentation fault can occur when the pipepair has entered the mutual termination procedure. When this process is ongoing the pipe should not send or request any stats to or from the pipepair, because the pipepair could already be deleted. The conditions and the occurance of the SEGV are shown and explained in the image. 
**I'm happy to provide additional explanation.**
=> Fixing SEGV #4524. Pipe should only send to peer when active.

configure.ac
There is no such thing as `+=` unless you happen to be using the Bash programming language, i.e. your script shebang is /bin/bash.
However, configure scripts are run via /bin/sh instead, which may or may not be be bash, usually depending on whether the system in question preferred to have one less package installed (in which case it is bash) vs. have a faster /bin/sh installed (in which case it is probably the dash shell).
=> configure: fix basic syntax errors in the shell script programming language

CMakeLists.txt
Result: on some BSD platforms (at least openbsd 7.4), cmake build will default to POLLER=poll instead of POLLER=kqueue.
Solution: include sys/types.h and sys/time.h as [documented by kqueue](https://man.openbsd.org/kqueue.2) and [used in autotools](https://github.com/zeromq/libzmq/blob/3b264019a24b08246e8a75f5014f893d7b6ffef9/acinclude.m4#L930-L932)
fixes kqueue detection on openbsd. This _avoids_ the error in #3957, but the error remains when building with explicit -DPOLLER=poll, or `./configure --with-poller=poll` .
=> Problem: cmake search for kqueue missing headers

CMakeLists.txt
Problem: It's frustrating to attempt to build libzmq with curve, only to find out _after build has completed_ that it wasn't found and the request was ignored.
Solution: respect user input and fail if their choice cannot be satisfied instead of ignoring it.
now builds where requested configuration is not found fail rather than proceeding without requested features
changes:
Previously, to enable curve, you needed the redundant config:
```
-DENABLE_CURVE=ON -DWITH_LIBSODIUM=ON
```
Whereas the following would not attempt to enable CURVE:
```
-DENABLE_CURVE=ON
```
and the required configuration would also proceed to build without CURVE, ignoring user request with a message.
Since ENABLE_CURVE and WITH_LIBSODIUM really represent the same thing now (there is no CURVE without sodium), we could …
=> halt build if CURVE requested but not found

configure.ac
On the master branch @ 481cc3fa2c4414e407d863b4428f1efd5441e97d, cross-compiling for Windows with static linking fails when relying on the `libzmq.pc` file.
Consider the minimum reproducible `zmq_win_demo.cpp` source file:
```
$ cat zmq_win_demo.cpp 
#include <zmq.h>
int main()
{
auto ctx = zmq_ctx_new();
zmq_ctx_term(ctx);
}
```
and steps to reproduce the bug as follows:
```
$ ZMQ_INSTALL_PATH=<set_any_path_at_your_choice>
$ ./autogen.sh
$ ./configure --host=x86_64-w64-mingw32 --prefix="$ZMQ_INSTALL_PATH" --disable-shared --disable-drafts --disable-libbsd --disable-perf --disable-Werror
$ make install
$ x86_64-w64-mingw32-g++-posix -static zmq_win_demo.cpp -DZMQ_STATIC $(env PKG_CONFIG_PATH="${ZMQ_INSTALL_PATH}/lib/pkgconfig pkg-config --static --cflags --libs libzmq) -o zmq_win_demo.exe …
```
=> Fix Autotools-generated `libzmq.pc` file

CMakeLists.txt
On macOS, mkdtemp is in `unistd.h`. Fix the CMake check so that is works. This was discovered when comparing the output of the Autotools an CMake build systems.
=> build: fix mkdtemp check on macOS

CMakeLists.txt
The builtin SHA1 (`ZMQ_USE_BUILTIN_SHA1`) is only used in the websocket engine (`ws_engine.cpp`), so if websockets are disabled, i.e `-DENABLE_DRAFTS=OFF`, don't add `sha1.c` to the sources list.
=> cmake: don't use builtin sha1 if not using ws

src/ipc_address.hpp, src/ipc_connecter.cpp, src/ipc_listener.cpp, tests/testutil.cpp
This fixes several instances where _MSC_VER was used to determine whether to use afunix.h or not. For example, MinGW requires the use of afunix.h but does not define _MSC_VER. The correct behavior is checking ZMQ_HAVE_WINDOWS.
=> Do not use _MSC_VER if windows

.github/workflows/CI.yaml
Solution: Install `libtool`. This seems to be the issue, given the CI output of a recent run, i.e:
```bash
configure.ac:1023: the top level
configure.ac:80: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
configure.ac:81: error: possibly undefined macro: AC_PROG_LIBTOOL
configure:7350: error: possibly undefined macro: AC_DISABLE_STATIC
configure:7354: error: possibly undefined macro: AC_ENABLE_STATIC
autoreconf: error: /opt/homebrew/Cellar/autoconf/2.72/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 1
+ exit 1
```
For example, a CI run from the recent opened #4699: https://github.com/zeromq/libzmq/actions/runs/9841129190/job/27167025854?pr=46 …
=> Problem: macos-latest CIs both failing

CMakeLists.txt
Solution: don't use `rt` if not `RT_LIBRARY`
This currently causes the check to fail on macOS:
```bash
/Library/Developer/CommandLineTools/usr/bin/c++  -std=c++11 -Wno-tautological-constant-compare  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_8466b.dir/CheckSymbolExists.cxx.o -o cmTC_8466b  -lrt
ld: library 'rt' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
even though `clock_gettime` is available.
Move the `clock_gettime` check up with the other librt related checks, and don't set `CMAKE_REQUIRED_LIBRARIES` if not `RT_LIBRARY`.
=> problem: trying to link against librt on macOS

Makefile.am
Solution: Add libsodium dependencies to Makefile.am file.
Fixes #4716
=> Problem: macos-latest with libsodium compilation failed

src/socket_base.cpp, tests/test_reconnect_options.cpp
Solution: Specify `_disconnected` as `false` in initialize list to solve this problem, and add tests to cover this scenario.
Fixed #4720
=> Fix issue with ZMQ_RECONNECT_STOP_AFTER_DISCONNECT option

src/clock.cpp
This closes #4723
This seems fairly portable across all aarch64 systems, be it Windows or Linux.
The arm 32bit intrinsic seems to be Microsoft-Specific, so I don't know how to implement this for arm32.
I don't think either gcc or clang support 32bit arm Windows though, so at least the issue with the undefined variable is solved.
=> Fix reading cycle count on non-msvc win-on-aarch64

.github/workflows/CI.yaml
Solution: Fixed the NDK version to android-ndk-r25 to avoid using unsupported NDK version on ubuntu-latest.
Fixes #4725
=> Problem: CI build android on ubuntu-latest failed

CMakeLists.txt
This PR mirrors the Autotools-based build system behavior for cross-compiling for Windows with static linking:
https://github.com/zeromq/libzmq/blob/ee29bcd64ac257e3e8c20ffa0fe8093f697fe429/configure.ac#L365
and properly populates the `Libs.private` section in the CMake-generated `libzmq.pc` file.
Addresses the unresolved issue in https://github.com/zeromq/libzmq/pull/4667:
> Please note that CMake-generated `libzmq.pc` file is also broken as its "Libs.private" section contains only `-lstdc++` when cross-compiling for Windows. I leave this problem out of this PR scope.
=> Fix CMake-generated `libzmq.pc` file

src/ip.cpp
check and handle failure as a fallback to tcp
I _believe_ this is the cause of #4730
There may be a better underlying fix to prevent the failure in the first place, but this treats failure to create the path for the ipc socket as a condition for falling back on tcp, just like failing to create the AF_UNIX socket itself, rather than ignoring the error and assuming success, which may fail later in epoll with EBADF.
I haven't been able to explain why this failure occurs in very peculiar scenarios (see #4730 and various linked issues through pyzmq), but this patch causes at least one of those cases to succeed, if I've done my tests correctly. Setting `$env:TMP` to a nonexistent or non-writable directory seems to provoke it _sometimes_ as well.
=> Problem: create_ipc_wildcard_address can fail

src/ip.cpp
Solution:
- move tcpip fallback to after connect instead of assuming successful ipc bind means ipc works (it's very weird and possibly a Windows bug that this can happen, but I can at least confirm that it does in very specific scenarios - Python from Windows Store + non-ascii username + default `$env:TMP`)
- correct some Windows error code checks
- set errno when connect fails (missing errno resulted in treating failure as success, leading to #4730)
- make sure to clear `_w` back to `retired_fd` after closing it
Also addresses todo item to remember the tcpip fallback after ipc has failed once, so the failing path doesn't get retried every time. I can back that out if folks want.
I believe this actually closes #4730, though after some debugging, I do believe there are still missing checks …
=> Problem: ipc connect can fail on Windows, even after bind

CMakeLists.txt
This change:
1. Makes the `libzmq.pc` files generated by Autotools and CMake more aligned.
2. Allows the `prefix` variable to be redefined if the package is relocated.
=> cmake: Refer to `prefix` variable in generated `libzmq.pc`

src/ip.cpp
Fixes error: jump to label 'try_tcpip' crosses initialization of 'const SOCKET listener'
=> Fix compilation with modern compilers

CMakeLists.txt
* Without this CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded (MT) Windows builds still produced incompatible MultiThreadedDLL (MD) output.
* Resolves following warning:
CMake Warning (dev) at CMakeLists.txt:2 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.
* Use ${CMAKE_HOST_SYSTEM_NAME} as ${CMAKE_SYSTEM_NAME} not set before project().
=> cmake_minimum_required() before project()

builds/android/android_build_helper.sh
This fix has to be reported in LIBZMQ as well and will fix https://github.com/zeromq/libzmq/issues/4744.
Close #4744
=> ANDROID: Support NDK r27x.

builds/cmake/NSIS.template32.in, builds/cmake/NSIS.template64.in
The latest version of NSIS (3.11) gives an error with the included NSIS templates. Renaming the RemoveSection macro seems to solve this issue.
=> Rename RemoveSection macro to avoid duplicate conflict with NSIS3

CMakeLists.txt, tests/CMakeLists.txt, unittests/CMakeLists.txt
setting an upper bound improves forward-compatibility as legacy version support is dropped. Without an upper bound, the minimum version is used as the policy version, which means that setting a version lower than 3.5 will result in warnings starting with cmake 3.27 and errors starting in 4.0 (release candidate out now). This change allows zeromq to build with cmake 4.
- 3.5 compat is deprecated in 3.27 (2023), removed in 4.0 (2025)
- 3.10 compat is deprecated in 3.31 (2024)
=> set upper bound in cmake_minimum_required

tests/test_radio_dish.cpp
The tests/test_radio_dish test implements is_multicast_available() to verify that multicast is working on the system before running tests that relies on this, or skipping those test otherwise.
In some circumstances this check itself hangs due to the recvfrom() call being blocking waiting for data. The test is eventually killed with a SIGALARM signal.
./config/test-driver: line 112: 1227308 Alarm clock             "$@" >> "$log_file" 2>&1
FAIL: tests/test_radio_dish
FAIL tests/test_radio_dish (exit status: 142)
$ tests/test_radio_dish
tests/test_radio_dish.cpp:511:test_leave_unjoined_fails:PASS
tests/test_radio_dish.cpp:512:test_join_too_long_fails:PASS
tests/test_radio_dish.cpp:513:test_long_group:PASS
tests/test_radio_dish.cpp:514:test_join_twice_fails:PASS …
=> Make failing test not hang

CMakeLists.txt
You have configured zeromq with CMake.
Build environment is MinGW.
When you install the the package config files, they are copied into a "CMake" directory into the sysroot, but this is a nonsense. 
Instead, they should be copied under ${LIBDIR}/cmake, as GNU tools require.
Hopefully, the solution is very easy.
This tiny PR fixes this error.
=> CMake: fix installation of config files on MinGW
